### ISSUE TITLE
using nginx proxy to enable HTTPS will lead following requests to HTTP

### ISSUE THREAD

**Issue by s-a** [panva/node-openid-client#100]
I try to setup HTTPS protocol using NGINX proxy. But following requests will point to HTTP protocol.
![image](https://user-images.githubusercontent.com/1270662/41702975-28ab6670-7532-11e8-9f11-b77eaf51770c.png)

Any idea how to work around this?

**Comment by panva** [comment]
Check the provider configuration page.

**Comment by s-a** [comment]
Thank you for the fast response. My project is based on the example in this repo. Can point me to the part of the configs ? I believe I have to configure https://github.com/panva/node-openid-client#proxy-settings but not sure how.

**Comment by panva** [comment]
It's not about the client configuration. It's the provider you need to configure right.

**Comment by s-a** [comment]
Thank you!
