### ISSUE TITLE
Essential ACR Claims

### ISSUE THREAD

**Issue by apowers313** [panva/node-openid-client#101]
Related to panva/node-oidc-provider#232 I'm trying to figure out how to set "phrh" and "phr" as essential `acr` claims. Based on reading [OIDC Core 5.5.1](http://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.5.1) I've tried several variations of this:

``` js 
    var options = {
        claims: {
            acr: {
                essential: true,
                values: [
                    "phrh",
                    "phr"
                ]
            }
        }
    };
    app.get("/auth", passport.authenticate("oidc", options));
```

But `oidc-provider` never fails when the essential claims can't be met. Any hints on how to set essential `acr` claims?

---

On a related note, is there any way to print out the raw messages that are being sent / received so that I can see how the messages are being formatted? Printing them out on either the client or provider side would be fine.

PS - thanks for the code and the examples, getting this setup was super easy and I'm impressed with the quality of the project

**Comment by apowers313** [comment]
Thanks for the quick reply.

Code now looks like this; server still doesn't return an error when it can't fulfill the essential claim...

``` js
    var options = {
        claims: {
            id_token: {
                acr: {
                    essential: true,
                    values: [
                        "phrh",
                        "phr"
                    ]
                }
            }
        }
    };
    app.get("/auth", passport.authenticate("oidc", options));
```

I'll start looking at inserting debug messages to make sure that the request looks right.

**Comment by panva** [comment]
I have a conformance and integration test saying its working as intended. Must be a configuration issue.

**Comment by apowers313** [comment]
Hmm... my code is pretty simple. Not sure where it could be going wrong.

https://gist.github.com/apowers313/a7e55adba6792a2d297f0b7da7535ff9

**Comment by panva** [comment]
Yeah your provider isnt configured to support claims parameter and neither these values if it’s as you posted. Please check the configuration. 

To make sure check the discovery document for claim_parameter_supported and acr_values

**Comment by apowers313** [comment]
Thanks, I'll fix that now.

**Comment by apowers313** [comment]
Enabling the claims parameter did the trick. 

For anyone that finds this in the future, the answer was:

``` js
const configuration = { features: { claimsParameter: Boolean[false] } };
const oidc = new Provider("http://localhost:3000", configuration);
```

Which can be verified as set by viewing http://localhost:3000/.well-known/openid-configuration and ensuring that `claims_parameter_supported` is `true`.

(Note: this still isn't setting ACR values -- I'm currently making sure that it fails when essential claims fail)
