### ISSUE TITLE
How to save client session into a database

### ISSUE THREAD

**Issue by anupvarma** [panva/node-openid-client#104]
Hi,

I'm using express session with connect-mongo as session store. So when the session gets stored into the database the client object has only CLOCK_TOLERANCE property and the rest all attributes and not present.

Also when I try to console log client object it just has one property i.e CLOCK_TOLERANCE 

A sample of session object save in database:
```
{
    "_id" : "dCJz3FWxFZaB0R8WUKZShTaMc6ANpI60",
    "session" : {
        "cookie" : {
            "path" : "/",
            "_expires" : null,
            "originalMaxAge" : null,
            "httpOnly" : true,
            "expires" : null,
            "maxAge" : null,
            "data" : {
                "originalMaxAge" : null,
                "expires" : null,
                "secure" : null,
                "httpOnly" : true,
                "domain" : null,
                "path" : "/",
                "sameSite" : null
            }
        },
        "keystore" : null,
        "tokenset" : null,
        "client" : {
            "CLOCK_TOLERANCE" : 0
        },
        "authorization_params" : {
            "scope" : "openid profile email address phone offline_access",
            "prompt" : "consent"
        },
        "state" : "cf720580747bebec62b398644adebbb3",
        "nonce" : "52d94b4ab53a7a6d1410b5ab36bc14e0"
    },
    "expires" : ISODate("2018-07-24T11:18:36.419Z")
}
```

**Comment by panva** [comment]
> How to save client session into a database

But you're describing storing the Client, why?

**Comment by anupvarma** [comment]
I'm using pm2 to run my client application. So need client object reference for almost every request. That is to do authorization checks in an express middleware. This is why i wanted to save the client object instead of calling `const client = await new issuer.Client({ client_id: process.env.CLIENT_ID, client_secret: process.env.CLIENT_SECRET });` on every request.

**Comment by panva** [comment]
Usually you have your client(s) defined in the process, not in the session, but since i need my public example to work for multiple users at the same time the session is in LRU memory and contains objects rather then their serialized form (which you shouldn't need either).

Please handle your sessions how you normally would, for backend sessions you just need to store the tokens from the tokenset and clients either hold in LRU cache (if you have infinite amount of them) and instantiate them using their serialized metadata.

**Comment by anupvarma** [comment]
Not sure how LRU cache would work in a clustered environment where, a process manager like PM2 is used? Also is it ok if I instantiate client at every request?

**Comment by panva** [comment]
> Also is it ok if I instantiate client at every request?

Again, not sure why having client instances for each request is ever needed or how pm2 plays into this...

Is it the same client for every request? Why not just have a singleton exported or something to the same efect.

**Comment by anupvarma** [comment]
Yes client is same for every request. Let me try making my process as a singleton export.

Thanks for your advice.
