### ISSUE TITLE
kid mismatch with auth server

### ISSUE THREAD

**Issue by abustya** [panva/node-openid-client#109]
Hi!

I am using the node-openid-client lib public/private key authentication and with signed request objects.

The problem is, that my auth server (keycloak 3.4) when registering a client with a public key, generates a kid for the key, but it is a different one than the one generated by the node-openid-client lib. Authentication fails after this because of kid mismatch.

If the client_assertion doesn't include a kid, it works. 

My idea is: a client option could be added to the lib to exclude the kid from every request (by setting reference:false at jose.JWS.createSign). I'm willing to make a PR if you think it makes sense.

**Comment by panva** [comment]
First and foremost Keycloak should respect the kid you provide in your jwks or jwks_uri.

Or if keycloak does not respect this, provide the same kid they generate for your key?

I’m reluctant to provide IdP specific workarounds in favor of idps fixing their implementation. Interoperability rocks.

**Comment by panva** [comment]
For reference. Please provide your public key as registered and the kid(s) that get generated on both sides?

What if you register with a custom kid? (Again both client and server)

**Comment by abustya** [comment]
Yes, I see your point about this just being a workaround.

A little more background:
Clients currently register on a developer portal and they only provide a public key, no jwks, no kid. So they don't even know what kid value the auth server generated for them. (Keycloak doesn't even show the generated value on it's UI, just in the mismatch error logs.)

Fixing the issue on the server side could be:
-pregenerating kid values for the public keys using node-jose before submitting the registration to the auth server
-allowing the clients to specify a kid value, or to allow them to submit jwks

I guess I'll do one of the above.
Disposing of the kid from the assertion just seemed like the easiest thing to do.

**Comment by abustya** [comment]
The different kid values:
By node-openid-client/node-jose: Evx52K1KKDs-RWGmktEmshMrjHGhfICvSgtDvF2SkP8
By keycloak: 74VbHzzFgmkkkAGukC-eQ8mU_y9Dn_b-N5RMPNtDuAU

**Comment by panva** [comment]
Yup. For the record [this](https://tools.ietf.org/html/rfc7638) is how the kid is generated if falsy. Please let others passing by know how you solved this keycloak-side.

**Comment by panva** [comment]
Now that you know keycloak’s kid you can instantiate your client to use that one. Right?

**Comment by abustya** [comment]
Well, yes. But I'm building the system for third party clients who register themselves. What I'm doing right now is looking for libraries I can recommend them to connect with, and making a demo application using these libraries.

This is the public key:
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArJVrnFNRvuARWLmtk9o4
nD7hUECq/y8nNQ+/TFr/zxq2uhVlzS1vfBbK04eGwO35PWFQa8N+qUxeRb8hOutc
MwyPpapTXkhdSMwhygu+ohrExDKuVDyYVKmTYmowMO1hJ8u2gBnaBXzh2dHXJ9I6
mzBaUralZuOr4MIr1wX8moIVGWCUgiQ4Fib8QvZhCMqVH/vxsZfnKOCvdbymWx0v
uuKa46NmlGpj8sjVkXoo2dszO7fXmcX+BZuuxwxI4HJvXl+ay6XZk8wmJI5Xe/5W
e04GeqMRpXLPO6C0TXkurx+vGakplDL4jMMztweDmk3Z/1k9aLqU+OhAD1R3e5V3
SLC4UxPZrbBAXsvOoKesG2xSZXwKFDOVsWRbQSCW08HqJi3m88j/cJL0bSi5eXIc
pr/gcI5U4//oeXn9agk/UKnCtn1VSkjd99m99bItm+57hnvdpmC8XEYkjuMCAR6c
59B1ZiSZxFxl8sAcWdVytA3K3xDfsYDWAEdGqU2lYuOntMUWn53EvlBuO2bq8KIm
G+eAaOvcTRZ/lXP1CaFN35ihd0nDnO0zLdsruM9hmxNB4lIOhffDeSY/2XPeXqGx
y7AjyIPNtaMjg6fJU7jn8yL/bOO9QjZ/34Hbx4XNpazr+RBzr47Eom1EgI7xFCi7
lCcORfs4haxWyAyXw8aUETcCAwEAAQ==
-----END PUBLIC KEY-----
