### ISSUE TITLE
invalid_grant while client.refresh

### ISSUE THREAD

**Issue by s-a** [panva/node-openid-client#110]
I try to refresh an expired token with `client.refresh` which throws an error `invalid_grant (grant request is invalid)` .

```javascript
router.get('/refresh', async (ctx, next) => {
	ctx.type = 'json'
	try {
		if (!TOKENS.has(ctx.session.id)) {
			ctx.session = null
			ctx.body = JSON.stringify({
				error: true,
				errorDetails: ['NO_SESSION']
			})
		} else {
			const tokens = TOKENS.get(ctx.session.id)
			const client = CLIENTS.get(ctx.session.id)

			/*
			const r = {
			refresh_token : tokens.id_token,
			grant_type : 'refresh_token'}
			*/
			const refreshed = await client.refresh(tokens.id_token)
			refreshed.session_state = tokens.session_state

			TOKENS.set(ctx.session.id, refreshed)
			ctx.body = JSON.stringify({
				error: false,
				payload: refreshed
			})
		}
	} catch (error) {
		ctx.body = JSON.stringify({
			error: true,
			errorDetails: [error.toString()]
		})
	}

	return next()
})
```

The server client configuration contains
``` "grant_types": ["refresh_token", "authorization_code"],```

I tried different variants like 
```
				tokens.refresh_token = tokens.id_token
				const ts = new TokenSet(tokens)

				tokens.refresh_token = tokens
				const refreshed = await client.refresh(ts)
```

Any idea what i am doing wrong here?

**Comment by panva** [comment]
check you IdP for errors.

**Comment by s-a** [comment]
Well I figured out the problem is that the submited token string was not found by the oip at https://github.com/panva/node-oidc-provider/blob/master/lib/actions/grants/refresh_token.js#L24. So far no idea why . `RefreshToken` is using the `MongoAdapter`.

**Comment by panva** [comment]
> const refreshed = await client.refresh(tokens.id_token)

And yet you're passing an ID Token. Why? You're supposed to pass in the full tokenset or just the `refresh_token`.

**Comment by s-a** [comment]
Yes I tried this. I am still not an open id expert. So far I thought this have to be the token I want to refresh. The point is I do not know how to get a `refresh_token` to pass. The `TokenSet` I have here in memory have no `refresh_token` property.
I guess I missed some configuration or implementation yet.

**Comment by panva** [comment]
> Yes I tried this. I am still not an open id expert. So far I thought this have to > be the token I want to refresh. The point is I do not know how to get a refresh_token to pass. The TokenSet I have here in memory have no refresh_token property.
> I guess I missed some configuration or implementation yet.


You might want to read up on the OIDC/OAuth 2.0 flows first then.

**Comment by denchen** [comment]
> The TokenSet I have here in memory have no refresh_token property.

@s-a I actually just ran into this issue too. Caveat: I'm also new the world of OIDC authentication. What I had to do was include the scope `offline_access` in the params passed to `Strategy()`. So my final scope looked something like: `openid profile email offline_access`

**Comment by panva** [comment]
With a conform OP this applies http://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

**Comment by s-a** [comment]
@denchen I figured this out at the day @panva mentioned to read the docs. Thank you for sharing your effords :+1:

**Comment by Gautami12** [comment]
I am trying to use openid for grant_type= authorization_code. I have done following steps:-
const express = require('express');
const Provider = require('oidc-provider');
const app = express();
const clients = [{
    client_id: 'test_oauth_app',
    client_secret: 'super_secret',
    grant_types: ['authorization_code'],
    response_types: ['code'],
    redirect_uris: ['https://testapp/signin-oidc'],
    token_endpoint_auth_methods_supported: ['client_secret_basic']
}];
const oidc = new Provider('http://localhost:3000',{
//console.log("HII");
claims: {
        email: ['email', 'email_verified'],
        phone: ['phone_number', 'phone_number_verified'],
        profile: ['birthdate', 'family_name', 'gender', 'given_name', 'locale', 'middle_name', 'name', 'nickname', 'picture', 'preferred_username', 'profile', 'updated_at', 'website', 'zoneinfo']
    },
scopes: ['openid'],

async findById(ctx, id) {
        return {
            accountId: id,
            async claims() { return { sub: id }; },
        };
    }


});
oidc.initialize({clients}).then(function () {
 app.use('/', oidc.callback);
app.listen(3000);
});
When tested by using endpoint - http://localhost:7003/auth - 
Request - 
redirect_uri:https://testapp/signin-oidc
response_type:code
scope:openid profile
nonce:123
state:321
client_id:test_oauth_app

Response :- http://localhost:3000/auth/bcd70b66-d4f9-438a-b595-2dcdec4f6658

Step2 )
When i am trying to access /token endpint i am getting following error
Request - http://localhost:3000/token
code:643b3e5e-588b-4b43-9018-f848ae738f0c
grant_type:authorization_code
redirect_uri:https://testapp/signin-oidc

Error Response -
{
    "error": "invalid_grant",
    "error_description": "grant request is invalid"
}
Can anyone help with the issue.

**Comment by panva** [comment]
debug?

**Comment by panva** [comment]
@Gautami12 I'm not sure what you're doing with the client but `bcd70b66-d4f9-438a-b595-2dcdec4f6658` taken from an AS interaction redirect is definitely not an authorization code.
