### ISSUE TITLE
Issuer discover returns empty object

### ISSUE THREAD

**Issue by gadzet** [panva/node-openid-client#111]
Opening the well known configuration returns an empty object. Opening it in broswer or json returns json object of the configuration. 

```
Issuer.discover('https://*****/.well-known/openid-configuration') // => Promise
    .then(function (issuer) {
        console.log('Discovered issuer %s', JSON.stringify(issuer));
    });
```

**Comment by panva** [comment]
Intended. Will update the docs, if you want the metadata object use `issuer.metadata`
