### ISSUE TITLE
client_id not sent correctly during PKCE token call from client.authorizationCallback

### ISSUE THREAD

**Issue by djdduty** [panva/node-openid-client#112]
Just as the title says, PKCE calls to the OIDC provider's token endpoint are failing due to the client_id not being specified properly.

This is causing an invalid_client being returned from my OIDC provider (based on your own oidc-provider framework for node) with the message `client authentication failed`. This seems to be a flaw even using the passport strategy implementation when usePKCE is true.

Edit:
Alright so upon further investigation, new info is revealed.

The client.authorizationCallback is sending the client ID base64 encoded in the Authorization header, which should be what /token expects, but for whatever reason it is failing with the message "client authentication failed", I suspect because there's no client secret since this is a PKCE request, either I've configured something wrong or this is a bug in oidc-provider and not openid-client. I'll keep investigating.

Edit 2:
I may have just figured it out, decoding the Authorization header gives me `client_id:undefined`, so that's definitely not right. I'll try setting client_secret to an empty string.

Edit 3:
Using an empty string or explicitly declaring null didn't work. After doing some reading it seems like for PKCE token requests, the Authorization header should be left off and client_id should be specific as part of the request body.

**Comment by djdduty** [comment]
Alright so upon further investigation, I may have jumped the gun.

The client.authorizationCallback is sending the client ID base64 encoded in the Authorization header, which should be what `/token` expects, but for whatever reason it is failing with the message "client authentication failed", I suspect because there's no client secret since this is a PKCE request, either I've configured something wrong or this is a bug in oidc-provider and not openid-client. I'll keep investigating.

**Comment by djdduty** [comment]
Alright, I feel like this was sort of obvious in hindsight, but it wasn't documented anywhere. I needed to set `token_endpoint_auth_method: 'none',` on my client properties object when instantiated it from the issuer. I found this out by digging through the code (makes sense, since the exact same configuration is needed for the client on the server side).

I'll go ahead and close this, but if anyone else should encounter the issue, that is the solution it seems.

**Comment by panva** [comment]
> Alright, I feel like this was sort of obvious in hindsight, but it wasn't documented anywhere.

Hi @djdduty I would very much welcome your thoughts on documentation updates.

> **Now you can create your Client.**
> 
> ### manually (recommended)
> You should provide at least the following metadata: `client_id`, `client_secret`, `id_token_signed_response_alg` (defaults to `RS256`) and `token_endpoint_auth_method` (defaults to `client_secret_basic`) for a basic client definition, but you may provide any IANA registered client metadata.


https://github.com/panva/node-openid-client#manually-recommended

**Comment by djdduty** [comment]
I suppose I did word that in a rather inconvenient way. As of creating this issue I had already been buried neck deep in learning as much as possible about OpenID connect providers and authorization patterns to implement on top as well as getting it to all work in our existing ecosystem since Friday. Most of my experience was rather frustrating trying to picture how everything was going to work together until I decided to just go trial by fire earlier in the day and implement it all; which lead to my rather hasty skimming about code samples to get it all working.

I think most of my confusion thus far isn’t because of lack of documentation on what to provide, but rather what each specific configurable option means(this is particularly true with oidc-provider configuration). It wasn’t immediately clear to me that specifying none would cause the client_id to be sent in the request body, which is necessary when there is no client secret, without having a greater understanding of the entire OpenID spec which admittedly IS expected before using these libraries. I understand that implementing oidc isn’t a trivial thing and a developer doing so should fully understand the spec first particularly because this is security related too.

I think what would have helped me out the most in this situation would be minimal client configuration examples for different use cases (server RP, native client RP, using different flows etc). I even had to dissect the passport strategy code in order to implement my front end only client which isn’t using passport.

Apologies that this is all anecdotal, I’m a bit too context scoped on all of this to look at the bigger picture currently.

**Comment by panva** [comment]
@djdduty 

> ... without having a greater understanding of the entire OpenID spec which admittedly IS expected before using these libraries. I understand that implementing oidc isn’t a trivial thing and a developer doing so should fully understand the spec first ...

I fully agree. That being said - let's make it simpler for beginners one step at a time.

fe3c78a, helps?

**Comment by djdduty** [comment]
@panva That helps a lot, I even learned a few things which I didn't already know from it, especially linking to the relevant section of the openID connect spec (which believe it or not I looked for during this and couldn't easily find, kept finding auth0 or okta docs for some reason).
