### ISSUE TITLE
System incorrect time issue

### ISSUE THREAD

**Issue by anupvarma** [panva/node-openid-client#113]
He have an electron app which Authenticates using OIDC client against OIDC provider. In a scenario where user have incorrect date / time set on his local machine this error occur when we try to get tokenset using **client.authorizationCallback()** method.  We have set token expire time to 60 mins on our provider.

Is there a way to handle this issue without increasing the expiring time? 

```
Error occurred in Login AuthClient.getAuthTokens() while genrating token { AssertionError [ERR_ASSERTION]: id_token expired
    at Client.validateIdToken (C:\Program Files\Neutrinos Studio\resources\app.asar\node_modules\openid-client\lib\client.js:498:7)
    at grant.then.then.tokenset (C:\Program Files\Neutrinos Studio\resources\app.asar\node_modules\openid-client\lib\client.js:348:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

**Comment by panva** [comment]
Detect the skew (e.g. with a server side call comparing the date you get back with what's on the client) and set the appropriate [CLOCK_TOLERANCE](https://github.com/panva/node-openid-client/tree/v2.3.1#allow-for-system-clock-skew)?

But I don't recommend the latter if it's beyond the realm of seconds/few minutes and would error instead asking that a proper time is configured first.

**Comment by anupvarma** [comment]
Okay will handle it this way. Thank you.
