### ISSUE TITLE
[ERR_ASSERTION]: multiple matching keys, kid must be provided

### ISSUE THREAD

**Issue by rubentacastro02** [panva/node-openid-client#114]
I am trying to use openid-client in identityServer 3 and I get the following error:

`AssertionError [ERR_ASSERTION]: multiple matching keys, kid must be provided`
Seems to be coming from here:

```
key(def, allowMulti) {
    const { cache } = instance(this);

    // refresh keystore on every unknown key but also only upto once every minute
    const freshJwksUri = cache.get(def) || cache.get('throttle');

    return this.keystore(!freshJwksUri)
      .then(store => store.all(def))
      .then((keys) => {
        assert(keys.length, 'no valid key found');
        if (!allowMulti) {
          assert.equal(keys.length, 1, 'multiple matching keys, kid must be provided');
          cache.set(def, true);
        }
        return keys[0];
      });
  }
```

How can I set `allowMulti` to `true`? 

Many thanks!

**Comment by panva** [comment]
That is the wrong question to ask. It’s an internal method, you can’t set it. You’re receiving an assertion error because of s non-conform behaviour. 

In cases where there is ambiguity in the OP’s jwks_uri, ie. there are two keys suitable for RS signature validation, the OP is required to push an ‘kid’ header claim.

**Comment by rubentacastro02** [comment]
Ok many thanks.

But how I can pass 'kid' to client instance?
To make one quick fix.

**Comment by panva** [comment]
You don’t get it. The kid is missing from the validated token’s header. You can’t pass or push or anything.

**Comment by singlewind** [comment]
Some OIDC provider support key rotation. So, they array can have two keys exactly the same in case the new key and old key is the same.

**Comment by panva** [comment]
Even in rotation scenarios [this](https://github.com/panva/node-openid-client/issues/114#issuecomment-417559115) still applies.

**Comment by rjoaopereira** [comment]
The language of the RFC has a significant impact in this case.

The [spec](https://tools.ietf.org/html/rfc7517#section-4.5) states that it **SHOULD** (not **MUST**) not contain duplicate keys with the same kid.

I have asked this in the [ietf mailing list](https://mailarchive.ietf.org/arch/msg/jose/D1D0lqcTeVF2hw_kKPfClyW4lSM)

Would you please consider making _allowMulti_ configurable? Or better yet, make it the default?

**Comment by panva** [comment]
@rjoaopereira 

> One example in which different keys might use the same "kid" value is if they have different "kty" (key type) values but are considered to be equivalent alternatives by the application using them.

Is this the condition you're running into? because that one should work just fine even without `allowMulti`. Can you provide the JWKS you have an issue with?

**Comment by rjoaopereira** [comment]
It is not the same case. Both type and id are the same.
[JWKS](https://pastebin.com/zGUAxyZL)
The first and last are the same

**Comment by panva** [comment]
@rjoaopereira can you try with this branch? https://github.com/panva/node-openid-client/tree/test-multi

**Comment by rjoaopereira** [comment]
@panva Tested and it works

**Comment by panva** [comment]
@rjoaopereira see [3.10.1](https://github.com/panva/node-openid-client/releases/tag/v3.10.1)

**Comment by rjoaopereira** [comment]
@panva Thank you very much!
