### ISSUE TITLE
id_token_signing_alg_values_supported is not respected

### ISSUE THREAD

**Issue by qwelias** [panva/node-openid-client#115]
When validating a tokenSet issuer's _id_token_signing_alg_values_supported_ openid required config property is ignored and a default value is used

For reference: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

**Comment by panva** [comment]
If the IdP signs a token using a key that is in fact in its `jwks_uri` I don't see why it's discovery `id_token_signing_alg_values_supported` factor in in any way. It is in fact [not normative requirement](http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation) to compare the used alg with what's discovered. Discovery's purpose is to help negotiate algs, not enforce them.

In any case, please provide more details, logs, keys, id tokens, etc...

**Comment by qwelias** [comment]
OpenID config: https://secureidentity.schneider-electric.cn/accessmanager/oauth2/se/.well-known/openid-configuration

Test user token set
```json
{"access_token":"hidden","refresh_token":"hidden","scope":"openid profile","id_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdF9oYXNoIjoidF9OaGYySkZxaDVDZUxwSHBjaWJIdyIsInN1YiI6ImNuMDBDU0VDLWQzdlUtUGlBci1VajFILU9rZDdhOEc1ZU1OWCIsImxhc3ROYW1lIjoiTXQiLCJFbWFpbCI6Im10N0BtYWlsaW5hdG9yLmNvbSIsImF1ZGl0VHJhY2tpbmdJZCI6ImRmZjMzZmY0LWE4MGUtNDA0NC04NTMyLTFjMGVhZGU2OTAwMy0xMDA0NDQ5MSIsImlzcyI6Imh0dHBzOi8vc2VjdXJlaWRlbnRpdHkuc2NobmVpZGVyLWVsZWN0cmljLmNuOjQ0My9hY2Nlc3NtYW5hZ2VyL29hdXRoMi9zZSIsInRva2VuTmFtZSI6ImlkX3Rva2VuIiwiY3VzdG9tX2F0dHJpYnV0ZXMiOnsiZW1haWwiOiJtdDdAbWFpbGluYXRvci5jb20iLCJFbWFpbCI6Im10N0BtYWlsaW5hdG9yLmNvbSIsIkNvdW50cnkiOiJDTiIsIkZpcnN0TmFtZSI6Ik10IiwiZmlyc3ROYW1lIjoiTXQiLCJsYXN0TmFtZSI6Ik10IiwiTGFzdE5hbWUiOiJNdCIsImNsYXNzTGV2ZWwxIjoiTEMiLCJjbGFzc0xldmVsMiI6IkxDMiJ9LCJ1cGRhdGVkX2F0IjoiMTUzNDMzODk5MSIsImF6cCI6IjNNVkc5eVouV05lNmJ5UUF2bEouSHdEOTRQWGdJcGd3Um9yMnhsQjVpNkpvMVhqMFA0VU1QWnV6MzVXaGlYdVZQN20wUDdZSlc4T18wQklZQXdwX1QiLCJhdXRoX3RpbWUiOjE1MzYxNjI2MTQwMDAsImV4cCI6MTUzNjE2NjM4MCwiaWF0IjoxNTM2MTYyNzgwLCJlbWFpbCI6Im10N0BtYWlsaW5hdG9yLmNvbSIsImNsYXNzTGV2ZWwxIjoiTEMiLCJjbGFzc0xldmVsMiI6IkxDMiIsIkZpcnN0TmFtZSI6Ik10IiwiZ2l2ZW5fbmFtZSI6Ik10IiwiRmVkZXJhdGVkSWQiOiJjbjAwQ1NFQy1kM3ZVLVBpQXItVWoxSC1Pa2Q3YThHNWVNTlgiLCJhdWQiOiIzTVZHOXlaLldOZTZieVFBdmxKLkh3RDk0UFhnSXBnd1JvcjJ4bEI1aTZKbzFYajBQNFVNUFp1ejM1V2hpWHVWUDdtMFA3WUpXOE9fMEJJWUF3cF9UIiwiZmlyc3ROYW1lIjoiTXQiLCJvcmcuZm9yZ2Vyb2NrLm9wZW5pZGNvbm5lY3Qub3BzIjoiODU3Mzg5ZjMtODNiNC00ZWI1LWJjZjItMzAyM2NhMjkxNzBhIiwiZmVkZXJhdGVkSWQiOiJjbjAwQ1NFQy1kM3ZVLVBpQXItVWoxSC1Pa2Q3YThHNWVNTlgiLCJuYW1lIjoiTXRNdCIsInByZWZlcnJlZGxhbmd1YWdlIjoiZW4iLCJDb3VudHJ5IjoiQ04iLCJyZWFsbSI6Ii9zZSIsIkxhc3ROYW1lIjoiTXQiLCJ0b2tlblR5cGUiOiJKV1RUb2tlbiIsImZlZGVyYXRpb25JRCI6ImNuMDBDU0VDLWQzdlUtUGlBci1VajFILU9rZDdhOEc1ZU1OWCIsImZhbWlseV9uYW1lIjoiTXQifQ.Lri_C9L21paKiv5JB6OpsYmmh3rpFkCNy7ko_lOXCvg","token_type":"Bearer","expires_at":1536166379}
```

Also I've tweaked source code a bit to use `id_token_signing_alg_values_supported` in https://github.com/qwelias/node-openid-client/tree/qwelias/respect-id-token-signing-values, but it fails later on `jose.JWS.createVerify(key).verify(idToken)`, however I was able to validate it on https://jwt.io using my `client_secret`

**Comment by panva** [comment]
I'm not seeing any non-conform behaviours. The OP's discovery `id_token_signing_alg_values_supported` isn't relevant for validating an ID Token's signature. 

Only the client-registered `id_token_signed_response_alg` (defaulting to RS256) and the keys from OP's discovery `jwks_uri` are.

**Comment by panva** [comment]
Well why don't you set the correct `id_token_signed_response_alg` you have configured on the OP then?

**Comment by qwelias** [comment]
The problem is that people who configure and support OP, and people who consume OP might not be the same. So I, as a consumer, might not want to hardcode that value into a Client instance because OP  may or may not change the `id_token` signing alg in the future to a different supported one -- I'd rather rely on a range of algs OP says it supports.

**Comment by panva** [comment]
That is not how the specification defines this functionality. A client has a signing alg communicated, or self-registered from the range that is `_supported`. 

Changing the default or registered signing algorithm on the OP would be a breaking change and no provider would do this.

There's no freeplay in which alg the OP should be sending down your path. It's gonna be the one fixed that you configure.

**Comment by qwelias** [comment]
Thanks for clarification!
