### ISSUE TITLE
OP End Session Endpoint url helper

### ISSUE THREAD

**Issue by sero323** [panva/node-openid-client#116]
Hey,

Just curious if there is an implementation of the End Session endpoint i can get, similar to 
`this.client.authorizationUrl(this.config);`. Maybe something like `this.client.endSessionUrl(this.config);`

I know i can build the url manually with the parameters...but I was hoping for an existing solution.

I am using `openid.Issuer.discover(this.issuerHost))` to get the endpoints from [https://demo.identityserver.io/.well-known/openid-configuration](url)

**Comment by panva** [comment]
> I know i can build the url manually with the parameters

Yup, pretty much. Accessed via client.issuer.end_session_endpoint or issuer.end_session_endpoint you get the discovered value, appending query params or running it through `url.parse` and `url.format`.

But since this is a reoccurance of the same request, i yield, will do eventually.

**Comment by sero323** [comment]
Cool! Thanks!

**Comment by CrowdHailer** [comment]
Would it be possible to add a link to this specification in the README?
https://openid.net/specs/openid-connect-session-1_0.html#RPLogout

I assumed this feature was not part of the library because it wasn't listed. 
Pleased to see it is though

**Comment by panva** [comment]
@CrowdHailer 

![BAF20687-F584-4D93-BF77-477AC67B7C5A](https://user-images.githubusercontent.com/241506/73823958-9cb8b180-47f9-11ea-9858-1c8c3d73af4e.jpeg)

**Comment by CrowdHailer** [comment]
On this page? https://github.com/panva/node-openid-client/blob/master/README.md
on master?

**Comment by panva** [comment]
:( messed up, thought this was open on the oidc-provider repo ;)
