### ISSUE TITLE
OpenID Implict Flow - Client Secret Required? 

### ISSUE THREAD

**Issue by NickLiffen** [panva/node-openid-client#117]
I see that in the documentation it says that this module supports the “implicit flow” which is fantastic. By implicit flow; I assume it roughly adheres to these standards: 

https://openid.net/specs/openid-connect-implicit-1_0.html

I read the documentation and see that it recommends passing a “client secret”, whereas the implicit flow doesn’t require a secret rather just a Client ID and a nonce (with a few other parameters).

I just want to make sure that I’m looking at the right implicit flow documentation and this module supports the flow that I need :) 

Thanks for the help. 

Happy to make a PR to make any chances if needed 😊

**Comment by panva** [comment]
Its not required.
