### ISSUE TITLE
Confusion regarding the lib/passport_strategy.js file

### ISSUE THREAD

**Issue by willmccullough** [panva/node-openid-client#119]
I’m not quite sure if this is a bug or a misunderstanding on my part, but I think this is worth mentioning. I noticed that in lib/passport_strategy.js, line 67, the params.redirect_uri defaults to the client object’s ‘redirect_uris[0]’ property. However, this property is found nowhere else in the documentation or source code, except for parts pertaining to the passport strategy (i.e., test/passport/passport_strategy.test.js and the README). The issue for me is that even when I construct the OpenIDConnectStrategy object with a valid params object, it still somehow defaults to {} no matter what I do. This caught me off guard for a while, and my only solution was to create with client object with both a redirect_uri and redirect_uris parameter. This feels hacky, and I’d like to believe that I shouldn’t need to do this in order to interface with passport (which I can’t get to work at all due to an error being thrown during the authorizationCallback function from client.js . This error says that a check is missing from the response).

**Comment by panva** [comment]
Hi @willmccullough 

> I’m not quite sure if this is a bug or a misunderstanding on my part, but I think this is worth mentioning. I noticed that in lib/passport_strategy.js, line 67, the params.redirect_uri defaults to the client object’s ‘redirect_uris[0]’ property. However, this property is found nowhere else in the documentation or source code...

Misunderstanding, not a bug.

I'd say `redirect_uris` is a [well documented](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata) property. That being said, you don't have to have it set on a client so long as your strategies' params has a valid `redirect_uri`.

> This caught me off guard for a while, and my only solution was to create with client object with both a redirect_uri and redirect_uris parameter, it still somehow defaults to {} no matter what I do.

What's `it`? [Params](https://github.com/panva/node-openid-client/blob/v2.3.1/lib/passport_strategy.js#L31)?

Client and the params are two entirely different arguments, you've read the doc, and read the source code as far as i can tell.

**Comment by willmccullough** [comment]
@panva I apologize for the ambiguity. I came to find out that I was creating a client object with a `redirect_uri` parameter instead of `redirect_uris`. For some reason I thought I was supposed to do this because the `authorizationUrl` function takes an object with a `redirect_uri` property as an argument. I'll try to get more familiar with the spec before asking questions like this.
