### ISSUE TITLE
I am getting "id_token issued in the future" on a server

### ISSUE THREAD

**Issue by JuneQuev** [panva/node-openid-client#126]
My authorization server (AS) and server using openid-client are on different cloud hosted instances, but they are both in the UTC time zone.  I am in the CST time zone.  I have 2 servers configured using the same exact code and one of them works great.  The other fails with the error in the subject line.  Is there a skew time for the issued at time (iat) that can be configured to allow for the AS to be ahead in time by a few seconds?

**Comment by panva** [comment]
Yeah. Readme. CLOCK_TOLERANCE
