### ISSUE TITLE
Problem dealing with URLs that have a trailing slash

### ISSUE THREAD

**Issue by atimmer** [panva/node-openid-client#13]
I am trying to connect with oauth openID connect to a WordPress installation. WordPress is very strict about ensuring every page has exactly one URL. Because of this, it redirects a URL without a trailing slash to one with a trailing slash. (Or vice versa, but that depends on the settings)

So when trying to connect I get the error: "expected 200 OK with body, got 301 Moved Permanently without one". This is because the library does a request to `.well-known/openid-configuration` without a trailing slash by default.

I think there are two solution for this: 
1. Following 301 redirects
2. Allowing the user of the library to set whether to include a trailing slash when requesting endpoints.

**Comment by panva** [comment]
Hey @atimmer 

ad 1) Following Redirects can be enabled, you can learn about this from the [README](https://github.com/panva/node-openid-client#changing-http-request-defaults)
```js
Issuer.defaultHttpOptions = { followRedirect: true };
```

ad 2) .well-known urls are well known for a reason, they are static and don't change, appending a trailing slash makes it a different request, doesn it? For all other requests the library just requests to a url that is either configured or discovered.

**Comment by atimmer** [comment]
Thank you for the quick response. I discovered `followRedirect` after making this issue. This solved the problem. On the second point, you are correct. It is indeed static: http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig. Thanks again for helping and for this library 😀
