### ISSUE TITLE
The code_verifier parameter is too short

### ISSUE THREAD

**Issue by cheesemacfly** [panva/node-openid-client#131]
[In the passport strategy](https://github.com/panva/node-openid-client/blob/master/lib/passport_strategy.js#L94) `uuid()` is being used to generate the `code_verifier` but `uuid()` is too short and limits the characters that can be used for the `code_verifier`. `uuid()` always generates [36 characters](https://tools.ietf.org/html/rfc4122#section-3) but the [RFC 7636 requires a `code_verifier` of at least 43 characters](https://tools.ietf.org/html/rfc7636#section-4.1).

I'd suggest generating the `code_verifier` using something similar to this:

```
const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~';
const length = 43;

const randomBytes = crypto.randomBytes(length);
const result = new Array(length);

let cursor = 0;
for (let i = 0; i < length; i++) {
  cursor += randomBytes[i];
  result[i] = chars[cursor % chars.length];
}

const verifier = result.join('');
```

I can create a PR if needed.

**Comment by panva** [comment]
@cheesemacfly great find, thank you! I'll update the client with nanoid instead of uuid and adjust the length appropriately.

**Comment by panva** [comment]
b1d3e7e wdyt?

**Comment by cheesemacfly** [comment]
Woa, that was super fast! 

LGTM, just as a side note nanoid doesn't use as many characters as allowed for the code_verifier but I don't think that's an issue. Also 43 characters is the minimum length, maybe we could allow for more (up to 128) as an option? Either way, thanks for the quick fix and the work you've done with this library!

**Comment by cheesemacfly** [comment]
I was actually looking at the first commit not the last one for some reason. Great fix, thanks!
