### ISSUE TITLE
Passport strategy and redirect_uri

### ISSUE THREAD

**Issue by Themandunord** [panva/node-openid-client#133]
Hi guys 😀 

I use the Passport strategy to use my openid connection.

I would like to know if I can have a  dynamic `redirect_uri` to have a different behavior between two conditions.

During the creation of the Passport Strategy, we set the params field with the `redirect_uri` in it. It is possible to change this value? 

Thanks

**Comment by panva** [comment]
https://github.com/panva/node-openid-client/pull/132#issuecomment-432924093

Not sure if this answers your question.

**Comment by Themandunord** [comment]
Oh like that! Easy!

Thank you very much @panva 👍

**Comment by panva** [comment]
You’re very welcome!
