### ISSUE TITLE
Exposing error class

### ISSUE THREAD

**Issue by badeball** [panva/node-openid-client#137]
Hi,

Awesome job on the lib, @panva. I've really appriciated looking through the code and especially the tests, to learn what openid is.

I'm currently trying to test error paths in my application and want to assert that an error is in fact the expected openid error, preferably without checking the message text.

Would it be possibly for you to expose the error class, like you've done in the [provider library](https://github.com/panva/node-oidc-provider/blob/v5.3.0/lib/index.js#L12)?

Regards

Jonas

**Comment by panva** [comment]
Hi Jonas,

definitely, it's already part of 3.x

**Comment by panva** [comment]
If you open a PR with that exact change i'll be happy to merge.
