### ISSUE TITLE
client_id missing on token endpoint

### ISSUE THREAD

**Issue by Garogat** [panva/node-openid-client#142]
**Describe the bug**
The openid server (fusionauth) I am running needs to get the client_id on the "token_endpoint" endpoint. Can I extend my discovery metadata somehow to match this requirements?

**To Reproduce**
```js
// Issuer configuration (issuer.metadata) and how it's constructed (discovery or manual?)
{
  "authorization_endpoint" : "https://auth.xxx.tdl/oauth2/authorize",
  "claims_supported" : [ "applicationId", "aud", "authenticationType", "email", "email_verified", "exp", "iat", "iss", "nbf", "roles", "sub" ],
  "grant_types_supported" : [ "authorization_code", "password", "refresh_token" ],
  "id_token_signing_alg_values_supported" : [ "RS256", "RS384", "RS512", "HS256", "HS384", "HS512" ],
  "issuer" : "acme.com",
  "response_types_supported" : [ "code" ],
  "scopes_supported" : [ "openid", "offline_access" ],
  "subject_types_supported" : [ "public" ],
  "token_endpoint" : "https://auth.xxx.tdl/oauth2/token",
  "userinfo_endpoint" : "https://auth.xxx.tdl/oauth2/userinfo",
  "userinfo_signing_alg_values_supported" : [ "RS256", "RS384", "RS512", "HS256", "HS384", "HS512" ]
}
// Client configuration (client.metadata) and how it's constructed (fromUri or manual?)
Issuer.discover(Config.get('auth.issuer'))
    .then((oicIssuer) => {
      client = new oicIssuer.Client({
        client_id: Config.get('auth.client.id'),
        client_secret: Config.get('auth.client.secret'),
      });
    });
```

Steps to reproduce the behaviour:

1.  open authorize url
2.  redirected to my node server
3.  crash when trying to exchange code with access_token, because client_id is missing

**Environment:**
 - openid-client version: [e.g. ^2.4.5]
 - node version: [e.g. v8.11.3]

**Comment by panva** [comment]
> client_id missing on token endpoint

It's not missing, it's being sent in an `Authorize` header which is the spec described and recommended default. If your IDP doesn't default to or recognized `client_secret_basic` client authentication you may configure you client to use a different auth scheme they support (probably `client_secret_post`). Honestly tho, using post in favor of basic is not good practice.

See <https://github.com/panva/node-openid-client#client-authentication-explained>
