### ISSUE TITLE
Issuer.issuer can be normal string and parsing it like a url is generates null.

### ISSUE THREAD

**Issue by ysaakpr** [panva/node-openid-client#15]
In passport strategy file creating session key can be updated to this with a null check..

const hostname = url.parse(issuer.issuer).hostname || issuer.issuer;
const sessionKey = `oidc:${hostname}`;

**Comment by panva** [comment]
Hello and thank you for the report. 

Did you discover or manually set up your Issuer instance? Either way, its issuer identifier value is likely invalid if the code for getting hostname returns null.

https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata
> Issuer
> URL using the https scheme with no query or fragment component that the OP asserts as its Issuer Identifier.

I'll rather introduce assertions that the values are in conform format than handling of invalid properties that don't follow the specification.

**Comment by panva** [comment]
Since the issue comes from invalid issuer identifier either configured or discovered, I am going to go ahead and close the issue. Feel free to open a backwards compatible PR with an option you can pass to the constructor to specify the session key to be used.
