### ISSUE TITLE
Issues with selfsigned https servers

### ISSUE THREAD

**Issue by vit100** [panva/node-openid-client#157]
**Is your feature request related to a problem? Please describe.**
If oauth issuer is working on self signed https then Issuer.discover('<https:.//urlOfissuerHost>') throws exception.

**Describe the solution you'd like**
I am developing solution and in dev I use Keycloak with self signed certificate. Unfortunately auto discovery fails with error:

> UnhandledPromiseRejectionWarning: AggregateError:
    RequestError: self signed certificate
        at ClientRequest.req.once.err (C:/Dev/TL-CQ/node_modules/openid-client/node_modules/got/index.js:182:22)    RequestError: self signed certificate

**Describe alternatives you've considered**
manually configure issuer via new Issuer({<CONFIGURATION_HERE>})

**Comment by panva** [comment]
Hi @vit100,

This is 100% expected. Not sure what solution you’d be expecting but a quick search for ignoring self-signed certificates will give you the answer

**Comment by vit100** [comment]
Yeh, you are right, search for ignoring of self-signed certificates yields
`process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;` 

What I expect is that only invocation of issuer.discover() will ignore self-signed.
If use trick with process.env, it is global setting. Maybe will be more flexible if it is applicable to issuer.discover function.
But again, it is not critical.
Thanks
