### ISSUE TITLE
Provider session logout with Passport Strategy

### ISSUE THREAD

**Issue by mshwery** [panva/node-openid-client#16]
Hello again!

Thanks for these two great (certified) libraries. They are super helpful.

I see how (in the example) you could handle a `/logout` scenario, where you revoke any potentially active `access_token` and use the `issuer.end_session_endpoint` to perform a browser redirect to the Provider's session management logout endpoint, but I have a general question about implementing this while using the Passport Strategy:

With Passport, you would normally use something like this:

```js
app.get('/logout', (req, res) => {
  req.logout() // end passport session
  res.redirect('/')
})
```

So I want to do something like this:
```js
app.get('/logout', (req, res) => {
  req.logout() // end passport session
  
  const url = `${req.protocol}://${req.get('host')}${req.baseUrl}`
  res.redirect(`${exampleIssuer.end_session_endpoint}?post_logout_redirect_uri=${encodeURIComponent(url)}`)
})
```

How can I retrieve the `id_token_hint` or revoke any remaining `access_token` – are they accessible somewhere or would it be helpful to extend the Passport Strategy itself to encapsulate these things in some form of `passport.logout()`?

**Comment by panva** [comment]
> How can I retrieve the id_token_hint or revoke any remaining access_token – are they accessible somewhere or would it be helpful to extend the Passport Strategy itself to encapsulate these things in some form of passport.logout()?

The strategy does not and will not take care of storing tokens for you, it's too specific to each and every environment. You must store them using your own mechanism and retrieve and revoke them in your logout route handler. Use your latest received id_token as your id_token_hint value.

**Comment by mshwery** [comment]
@panva thanks for the follow up – I took your advice and ended up using a store (soon to be redis) to keep track of `sub`s and their `id_token` and `access_token`. I revoke if possible, and otherwise send on the `id_token` as the `id_token_hint` for the logout flow.
