### ISSUE TITLE
Allow for additional properties to be passed to code exchange

### ISSUE THREAD

**Issue by alexashley** [panva/node-openid-client#160]
**Is your feature request related to a problem? Please describe.**

I'm using Keycloak as the OpenId provider for a number of applications. Keycloak doesn't support the [OpenId backchannel logout draft](https://openid.net/specs/openid-connect-backchannel-1_0.html), but it does have a way through its client [adapters](https://github.com/keycloak/keycloak-nodejs-connect) to notify when a logout happens. This feature works by passing an additional, non-standard parameter when doing the code exchange (`client_session_state`). Later, when a user is logged out through one app, Keycloak will include this value when hitting an admin endpoint inside of other apps with a session.

This library correctly [removes any non-standard parameters](https://github.com/panva/node-openid-client/blob/83d3d3cb7b3243e0e8711ae8535e58bf0397fe56/lib/client.js#L441) before doing the code exchange call, but this prevents passing this custom parameter.

**Describe the solution you'd like**
Allow for users to supply a list of additional allowed properties that could be merged with [callback properties](https://github.com/panva/node-openid-client/blob/83d3d3cb7b3243e0e8711ae8535e58bf0397fe56/lib/helpers/consts.js#L29) and included in the code exchange request. 

I made this change locally and would be happy to make a PR after I add tests. 

**Describe alternatives you've considered**
I imagine it would be possible to swap the HTTP client and mutate the request, but that's a large overhaul for one additional parameter. It also makes the code much harder to follow for future maintainers.

Alternatively, it would be possible to make Keycloak changes to allow for adding this additional session note another way.

**Additional context**
The Node.js application server I use isn't supported by Keycloak's official Node.js adapter.

 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
Additional request body properties and callback properties the client needs are two different things. I'm gonna need you to elaborate.

I'm not going to consider a "passthrough" of sorts that would automatically get applied to code exchange.

I am going to overhaul the way request options are applied at each request's time for 3.x so that you get a chance to change the http request options (including body) on each request.

I'd be happy to see a doc entry for using it with this particular KeyCloak feature then.

**Comment by alexashley** [comment]
It would be another form-encoded parameter to the token endpoint, like `grant_type` or `code`. But rather than coming from the query parameters of the callback redirect, it's an option supplied by the client. 

In the patch I have locally, I changed the signature of `authorizationCallback` to add a list of properties that should be included in the request.

```js
queryParams['client_session_state'] = clientSessionState;

client.authorizationCallback(oidcConfig.callbackUri, queryParams, {state}, ['client_session_state']);
```

It's definitely a hack, and I would rather alter the request in another way. Is there any way I can help with that work for 3.x branch? Or a release candidate I could try out?

**Comment by panva** [comment]
> It's definitely a hack, and I would rather alter the request in another way. Is there any way I can help with that work for 3.x branch? Or a release candidate I could try out?

Not atm.

**Comment by alexashley** [comment]
Ah, I didn't see that issue. Sounds like you're already on it. I'll wait for the 3.x release then and continue on a fork until it's out. Thanks for the help!
