### ISSUE TITLE
Encoding of Credentials in Basic-Authentication Header

### ISSUE THREAD

**Issue by GrannyOlli** [panva/node-openid-client#161]
Steps to reproduce the behaviour:
Authentication with an openidconnect-idp to receive access-token with code fails because of invalid credentials.
Cause: in client.js, client_id and client_secret are formUrlEncoded before base64-encoding.
According to RFC2617, client_id and client_secret must not be formUrlEncoded (https://tools.ietf.org/html/rfc2617#section-2)

Code from client.js, starting from line 968
       
const encoded = `${formUrlEncode(this.client_id)}:${formUrlEncode(this.client_secret)}`;
const value = Buffer.from(encoded).toString('base64');
return { headers: { Authorization: `Basic ${value}` } };

**Expected behaviour**
client_id and client_secret are not formUrlEncoded before base64 encoding

**Environment:**
 - openid-client version: 2.4.5
 - node version: v10.15.3

**Comment by panva** [comment]
This is correct behaviour, see https://tools.ietf.org/html/rfc6749#section-2.3.1 and the related appendix, this was fixed (introduced) in https://github.com/panva/node-openid-client/releases/tag/v2.0.1 and will stay as such.

If the AS you're using openid-client with does not process your client_secret correctly then you should request them to fix it. If you can't get them to fix client_secret_basic see if you can use client_secret_post instead.

Note this behaviour is certified with OIDC Certification Suite where this behaviour was also missing until [recently](https://github.com/openid-certification/oidctest/issues/88)
