### ISSUE TITLE
Allow to customize HTTP request timeouts

### ISSUE THREAD

**Issue by ulrichb** [panva/node-openid-client#172]
**Is your feature request related to a problem? Please describe.**

I'm getting HTTP timeouts after 2500 ms (the [hard-coded default in `request.js`](https://github.com/panva/node-openid-client/blob/f9cda63a91b98a43167b76d2afbafe79c370e1ae/lib/helpers/request.js#L15)) and have no option to customize the timeout value.

**Describe the solution you'd like**

For example in `Issuer.discover(url)` a new options parameter allowing to optionally specify a HTTP timeout value.

**Describe alternatives you've considered**
-

**Additional context**
-

 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
https://github.com/panva/node-openid-client/tree/master/docs#customizing-http-requests

**Comment by panva** [comment]
you can assign this symbol to Issuer constructor, issuer instance, Client constructor, client instances.

It is like so because in v2.x was global and didn't serve the more complex use cases.

**Comment by ulrichb** [comment]
Okay. Many thanks for info. Works!
