### ISSUE TITLE
Error: ERR_OSSL_BN_NEGATIVE_NUMBER in Auth Code callback

### ISSUE THREAD

**Issue by bcallaghan-fri** [panva/node-openid-client#176]
**Describe the bug**

When working through the Authentication Code flow, the following error occurs during the callback step. I'm attempting to get a token from Azure Active Directory v2.0. This result occurs with both the `common` and `organizations` tenants. The error appears to occur while getting the signing key for the returned ID Token.

```
Error: error:0300006d:bignum routines:OPENSSL_internal:NEGATIVE_NUMBER
    at createPublicKey (internal/crypto/keys.js:315:10)
    at asKey (C:\Users\...\node_modules\@panva\jose\lib\jwk\import.js:73:19)
    at C:\Users\...\@panva\jose\lib\jwks\keystore.js:162:39
    at Array.map (<anonymous>)
    at Object.asKeyStore (C:\Users\...\node_modules\@panva\jose\lib\jwks\keystore.js:162:26)
    at Issuer.keystore (C:\Users\...\node_modules\openid-client\lib\issuer.js:87:38)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
    at async Issuer.key (C:\Users\...\node_modules\openid-client\lib\issuer.js:119:22)
    at async Client.validateIdToken (C:\Users\...\node_modules\openid-client\lib\client.js:831:13)
    at async Client.callback (C:\Users\...\node_modules\openid-client\lib\client.js:472:7)
```

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
const issuer = await Issuer.discover('https://login.microsoftonline.com/organizations/v2.0');
this.client = new issuer.Client({
	client_id: '<my-client-id>',
	redirect_uris: ['https://login.microsoftonline.com/common/oauth2/nativeclient']
	token_endpoint_auth_method: 'none'
});
```

**Expected behaviour**
The ID Token and Access Token are returned, or a validation error is thrown.

**Environment:**
 - openid-client version: 3.2.1
 - node version: 12.0.0 (Electron 6.0.0-beta.13)

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
@bcallaghan-fri This is strange, i thought windows might be an issue (since it works locally for me) so I've triggered a CI build including a windows one doing the same code path that doesn't work for you - resolving the add issuer and then fetching the keystore.

- [code](https://github.com/panva/node-openid-client/commit/723906ad30cfda64bda45f7f1fdb3160ca4350ee)
- [ci build](https://travis-ci.com/panva/node-openid-client/builds/119020828)

As you can see the regular windows build [passed](https://travis-ci.com/panva/node-openid-client/jobs/215708063) so the only thing left to check is electron's bundled node version - I suggest you open the issue over at https://github.com/electron/node

I can only guarantee node runtime compatibility, electron bundles BoringSSL instead of OpenSSL which is what node's crypto is working on. If BoringSSL is not API compatible with OpenSSL then there are operations bound to fail.

**Comment by bcallaghan-fri** [comment]
Thank you for your fast response. I was able to replicate the issue in a minimal project based on the test case you linked. The following code works with Node 12.0.0, but does not work with Electron 6.0.0-beta.13.

```
const { Issuer } = require('openid-client');

async function run() {
	const aad = await Issuer.discover('https://login.microsoftonline.com/organizations/v2.0');
	const keystore = await aad.keystore();
	console.log(keystore);
}

run()
.catch(console.error)
.then(() => process.exit());
```

I'll file a new bug report with Electron.

**Comment by bcallaghan-fri** [comment]
A [new bug report](https://github.com/electron/node/issues/111) has been filed with Electron Node.

**Comment by panva** [comment]
@bcallaghan-fri i'll be releasing @panva/jose 1.5.1 shortly with a fix to the JWK import, but please note that electron still fails to import the last jwks_uri x5c as a certificate. Even if that got fixed, i just ran the jose test suite under electron and there are plenty of failures. Mostly probably coming from missing cipher support in boringssl compared to openssl.

So bottom line, while the lingering bug in the jose library is going to be fixed, no good news for you as electron still doesn't behave as node when it comes to importing keys.

**Comment by panva** [comment]
I've pinned https://github.com/panva/jose/issues/34 in @panva/jose summarizing what doesn't work due to BoringSSL use.

**Comment by panva** [comment]
@bcallaghan-fri you should be unblocked now with @panva/jose 1.5.2 (do `npm upgrade --depth 99999`), i've just tried to split the cert by 64 and join with new lines and it worked.

**Comment by bcallaghan-fri** [comment]
@panva Those two patches worked for me. I can now do the full Auth Code flow when running in Electron 6. Thanks for your help!
