### ISSUE TITLE
Receiving checks.state argument is missing Error

### ISSUE THREAD

**Issue by chveragad** [panva/node-openid-client#178]
I am quite new to IDP integration and currently encountering an issue.  Our application utilizes an SDK which consumes openid-client 2.4.0 and when using the direct IP works perfectly fine.  But when there is a layer of either NGINX or CLOUDFLARE-APPLICATION GATEWAY, the **error checks.state argument is missing** is encountered.

This is most likely setup issue but would like to know if anyone encountered such and if there are settings for those layers need to be added/removed to maintain the state. One thing I notice is that the identity in the request header when there is a web server layer is quite short compared to a request without that layer.

Hope someone could help me with this issue. 

Steps to reproduce the behaviour:

1.  Deploy the node application where it is only accessible through web server like NGINX or goes through cloudflare-application gateway layer.
2.  Access the application -> which in turn will redirect to IDP then redirect back to openid-client to redirect back to node application with authenticated user.
3.  Redirect to application contains error message checks. state argument is missing 

**Expected behaviour**
Expected behavior is that the authentication will proceed.

**Environment:**
 - openid-client version: v2.4.0
 - node version: v8.4.0

**Additional context**
I have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by chveragad** [comment]
This is the line throwing the error:
    ```
if (params.state && !checks.state) {
      return Promise.reject(new Error('checks.state argument is missing'));
    }
```

From my understanding, the param.state comes from the query parameters from redirect and the checks.state will come from identity attribute in the request object.  When I debugged, I see that the identity is present but somehow state might not be in that encoded information.

Here are the requests:
![nginx-app-request](https://user-images.githubusercontent.com/11677578/62510117-6c8b5880-b840-11e9-934e-a5d31e803a9b.png)
![nginx-cidp-request](https://user-images.githubusercontent.com/11677578/62510118-6c8b5880-b840-11e9-961e-bb3025254adc.png)
![nginx-error-request](https://user-images.githubusercontent.com/11677578/62510119-6c8b5880-b840-11e9-8755-260bc14e501e.png)
![nginx-oidc-request](https://user-images.githubusercontent.com/11677578/62510120-6d23ef00-b840-11e9-8e4f-98bb005dd65d.png)

**Comment by panva** [comment]
This is 100% a problem with either your nginx/cloudflare integration or your code (e.g. cookie option settings on your app).

Make sure the cookies your app sets in the response in which it redirects to the IdP are available and forwarded to your app when the user-agent gets redirected back to your redirect_uri.

**Comment by chveragad** [comment]
Thanks for your reply.  I see that the necessary cookie information gets passed on the redirects up to our redirect_uri.  This I verified using the browser network logs.  However it seems that even if the cookies might not be containing the complete information hence the issue.

Yes, I do acknowledge that it is most likely the environment setup or application specific config.  But then, this will be a good reference point to developers integrating this in their application along with nginx/cloudflare.

I have set these configurations.  There might be something amiss causing the issue.  Hope someone can share their inputs.

_NGINX_

           ```
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection 'upgrade';
           proxy_set_header Host $host;
           proxy_cache_bypass $http_upgrade;
           proxy_http_version 1.1;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Proto $scheme; 
```

For cookies in my app, we are utilizing the connect-redis node module and these have been tweaked:
_SESSION IN CONFIG.json_
```
"session": {
              "module": {
                  "name": "path:./lib/redis-session",
                  "arguments": [
                      {
                          "secret": "+++++++++++++++++",
                          "cookie": {
                              "path": "/",
                              "maxAge": null
                          },
                          "resave": false,
                          "saveUninitialized": true,
                          "store": null,
                          "proxy": true
                      },
                      {
                          "host": "+++.+++.+++.++",
                          "port": 6379,
                          "prefix": "session:",
   		          "pass": "passwordHere"
                      }
                  ]
              }
          },
```

_Added this line in index.js_
app.set('trust proxy', true);

**Comment by panva** [comment]
> This I verified using the browser network logs.

That’s not enough for verification, you only know it reaches your webserver and tls terminating proxy, not the app itself. Put a middleware in and confirm the header gets to your app and session gets loaded.

**Comment by chveragad** [comment]
Thanks for your suggestion.  I have logged the request object that the application received from nginx and can see that the request headers has the cookie information.  However, I notice that the sid is actually not being persisted in redis and that the cookie necessary for authentication is quite short (compared to the successful one - without nginx).

I cannot exactly pinpoint if it is an issue on nginx only, our app only or a combination of both.  :(

This is the configuration I have set for our application session:

```
"session": {
              "module": {
                  "name": "path:./lib/redis-session",
                  "arguments": [
                      {
                          "secret": "04bXXXXXXXXXXXXXXXXXcd26",
                          "cookie": {
                              "path": "/",
                              "maxAge": null,
                              "httpOnly": false,
                              "secure": true,
                              "sameSite": true
                          },
                          "resave": false,
                          "saveUninitialized": true,
                          "proxy": true
                      },
                      {
                          "host": "xxx.xxx.xx.xx",
                          "port": 6379,
                          "prefix": "session:",
			     "pass": "XXXXXXXXXX"
                      }
                  ]
              }
          },
```

_redis-session_
```
'use strict';

var session = require('express-session'),
    RedisStore = require('connect-redis')(session);

/** Creates a REDIS-backed session store.
 *
 * @param {Object} [sessionConfig] Configuration options for express-session
 * @param {Object} [redisConfig] Configuration options for connect-redis
 * @returns {Object} Returns a session middleware which is backed by REDIS
 */
module.exports = function (sessionConfig, redisConfig) {

    // add the 'store' property to our session configuration
    sessionConfig.store = new RedisStore(redisConfig);

    // create the actual middleware
    return session(sessionConfig);
};
```

Also, I noticed that httpOptions can be customized in openid-client.  Currently, there is nothing set from our application.  Is there something needed to be configured on this? 

[https://github.com/panva/node-openid-client/tree/master/docs#customizing-http-requests]

Thanks a lot! Appreciate any responses as I have been stucked to it for quite a while now.

**Comment by panva** [comment]
> Also, I noticed that httpOptions can be customized in openid-client. Currently, there is nothing set from our application. Is there something needed to be configured on this?

Those are http **request** options made by the client to the IdP, unrelated to your issue.

**Comment by panva** [comment]
The sameSite:true option i think may be problematic. If true maps to “strict” then your callback from the idp will not get the cookies. Try setting it to “lax” / “none” or false.

**Comment by chveragad** [comment]
> The sameSite:true option i think may be problematic. If true maps to “strict” then your callback from the idp will not get the cookies. Try setting it to “lax” / “none” or false.

Initially, this was not set and takes the default which is false.  It is actually still returning checks.state argument is missing .

**Comment by panva** [comment]
I have yet to see your code or details on what integration you actually use. It's unlikely anyone will be able to help with this little detail.

**Comment by chveragad** [comment]
There is a middleware being used by our app which is instantiated at the application level.  This middleware does redirect to identity provider then back to oidc.

Here is the code in our app:

app.use(idp.idpMiddleware(oidcConfig));

* oidc config consists of authority url, client id/secret, redirect uri, error uri, session cookie name, http options and clock tolerance

Middleware:
```
idpMiddleware: function idpMiddleware(settings) {
        var $this = this;
        settings.session_cookie_name = settings.session_cookie_name || 'identity';
        $this.oidcSettings = settings;
        _openidClient.Issuer.defaultHttpOptions = settings.httpOptions;
        return [(0, _clientSessions2.default)({
            cookieName: settings.session_cookie_name,
            secret: _crypto2.default.randomBytes(16).toString('hex')
        }), $this.connect(), $this.signInCallback(), $this.signOutCallback()];
    },
```
After which, our routes (for instance home page) can perform calls to this middleware to check is user is authenticated and allowed access to the application.  

The isAuthenticated method call is as follows:

```
isAuthenticated: function isAuthenticated(settings) {
        var $this = this;
        return function (req, res, next) {
            $this.updateOidcSettings(settings);
            var session = req[$this.oidcSettings.session_cookie_name];

            var user = $this.getUser(session);
            if (user.authenticated) {
                return next();
            }

            if (session.refresh_token) {
                var client = $this.getClient();
                return client.refresh(session.refresh_token).then(function (tokenSet) {
                    if (tokenSet.id_token) {
                        req[$this.oidcSettings.session_cookie_name] = tokenSet;
                        next();
                    }
                }).catch(function (err) {
                    return $this.authenticate(req, res);
                });
            }

            $this.authenticate(req, res);
        };
    },

WHERE CLIENT is the openid-client, SETTINGS are oidc config
```

The authenticate call then redirects to the identity provider to validate user access and redirects back to openid-client signin callback.  This callback is the one invoking the authorization callback and compares the states:

```
signInCallback: function signInCallback() {
        var $this = this;
        return function (req, res, next) {
            if (req.path !== _settings2.default.signInCallback) {
                next();
                return;
            }

            var clientHost = $this.getHostUrl(req);
            if (req.query.errMsg) {
                return res.redirect(clientHost + $this.oidcSettings.error_url + req.query.errMsg);
            }
            var session = req[$this.oidcSettings.session_cookie_name];
            var state = session.state;
            var nonce = session.nonce;

            var client = $this.getClient();

            var params = client.callbackParams(req);
            client.authorizationCallback(clientHost + _settings2.default.signInCallback, params, { nonce: nonce, state: state }).then(function (tokenSet) {
                req[$this.oidcSettings.session_cookie_name] = tokenSet;
                return res.redirect(clientHost + $this.oidcSettings.redirect_uri);
            }).catch(function (err) {
                return res.redirect($this.oidcSettings.error_url + err.message);
            });
        };
    },

WHERE CLIENT is the openid-client
```

**Comment by chveragad** [comment]
From what I understand, the signinCallback is invoked after the redirect call from the authenticate method.  Does that mean that it might not have received the cookie information from the request headers?

**Comment by panva** [comment]
You're not showing the part that actually matters, that stores the state and nonce in your session your `authenticate(req, res)`

**Comment by chveragad** [comment]
This is the authenticate method:

```
authenticate: function authenticate(req, res) {
        var session = req[this.oidcSettings.session_cookie_name];
        if (!session) {
            console.error('Error: ' + this.oidcSettings.session_cookie_name + ' session is not configured');
            return;
        }
        var clientHost = this.getHostUrl(req);
        var user = this.getUser(session);
        if (user.authenticated) {
            return res.redirect(clientHost + this.oidcSettings.redirect_uri);
        }

        if (req.baseUrl) {
            this.oidcSettings.redirect_uri = req.baseUrl;
        }

        session.state = _crypto2.default.randomBytes(16).toString('hex');
        session.nonce = _crypto2.default.randomBytes(16).toString('hex');
        var authorizationUrl = this.getAuthorizationUrl(req);
        return res.redirect(authorizationUrl);
    },
```

**Comment by panva** [comment]
I’m going to go ahead and close this in a few days. Your issue is not related to the library but rather, your environment and/or code using the library. 

There’s little I can do to help. You gotta debug and investigate your environment.

**Comment by chveragad** [comment]
I understand. Thanks.  I would just remove the codes that I pasted earlier.

**Comment by panva** [comment]
I can delete the whole issue if that's what you'd rather have.

**Comment by chveragad** [comment]
Okay please do. thanks
