### ISSUE TITLE
Verify callback never being called

### ISSUE THREAD

**Issue by mithun-daa** [panva/node-openid-client#18]
Hello there,
I am trying to use the passport strategy, I get redirected to my Auth server and redirect back to my `redirect_url` but the `verify` callback never gets called. What am I missing?

```
const Issuer = require('openid-client').Issuer;
const Strategy = require('openid-client').Strategy;

Issuer.discover('http://localhost:5000')
    .then(idSrvIssuer => {
        const client = new idSrvIssuer.Client({
            client_id: 'my_client',
            client_secret: ''
        });

        const params = {
            redirect_uri: 'http://localhost:5004/callback',
            response_type: 'id_token',
            response_mode: 'form_post',
            scope: 'openid profile',
            claims: {
                id_token: { email_verified: null },
                userinfo: { sub: null, email: null },
            },
        }
        passport.use('oidc', new Strategy({ client, params }, (tokenset, userinfo, done) => {
           // **NEVER GET HERE**
            console.log('tokenset', tokenset);
            console.log('access_token', tokenset.access_token);
            console.log('id_token', tokenset.id_token);
            console.log('claims', tokenset.claims);
            console.log('userinfo', userinfo);
        }));
        app.use(passport.initialize());
        app.use(passport.session()); // persistent login sessions
    })
    .catch(ex => {
        console.log(ex)
    })
app.get('/', passport.authenticate('oidc'), function (req, res) {
    res.send('hello!!');
});

app.post('/callback', function (req, res) {
    console.log('In callback', req.user)
    res.send(200);
})
```

I get to `/callback` but I do not have any of the claims or user info.

**Comment by panva** [comment]
Why are you not calling authenticate on the callback route?

```
app.post('/callback', passport.authenticate('oidc'));
```

**Comment by mithun-daa** [comment]
I get the following error when I do auth in the callback:
```
Error: access_token not present in TokenSet
   at Client.userinfo (D:\playground\IdSrvTest\src\node_client\node_modules\openid-client\lib\client.js:492:31)
   at callback.then (D:\playground\IdSrvTest\src\node_client\node_modules\openid-client\lib\passport_strategy.js:106:40)
   at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by mithun-daa** [comment]
FYI, I am using Identity Server 4 (another OP) and it posts back to my `callback` and it posts to my app with the following fields in the body:
```
  id_token: 'long string',
  scope: 'openid profile',
  state: '...',
  session_state: '...
```

**Comment by panva** [comment]
Well your callback includes `userinfo`, so what the function attempts to do is get userinfo with what it received, but your response_type is id_token only. Should be pretty clear you cannot get userinfo with this response_type. Change your verify signature to (tokenset, done) and you're good to go.

**Comment by mithun-daa** [comment]
Awesome! Thank you very much. That did it.

**Comment by m-ermolaev** [comment]
@panva 
Hi! I have almost identical situation. Have this too:

> FYI, I am using Identity Server 4 (another OP) and it posts back to my `callback` and it posts to my app with the following fields in the body:
> 
> ```
>   id_token: '....',
>   scope: 'openid profile',
>   state: '...',
>   session_state: '...'
> ```

But by adding `passport.authenticate` in my `post` I get cyclic redirect.

Could you give some tip what can be done ?

**Comment by panva** [comment]
do you have a body parser on that path?

**Comment by m-ermolaev** [comment]
@panva with body parser works fine, thanks
