### ISSUE TITLE
RP that have client_secret fail when sending authorization_code grant in passport strategy

### ISSUE THREAD

**Issue by dementeddevil** [panva/node-openid-client#180]
**Describe the bug**
I have an authentication server with a configured client that has a client secret defined and configured for hybrid-flow. When I use the passport strategy to handle authentication via this library, during the callback handling I have stepped through all the code and found that it never sets up the clientAssertionPayload when it attempts to get a refresh token using the authorization code.

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
// Issuer configuration (issuer.metadata) and how it is constructed (discovery or manual?)
{
  // Gained issuer configuration via metadata discovery method (authentication server is a .NET implementation based on IdentityServer v3)
}
// Client configuration (client.metadata) and how it is constructed (fromUri or manual?)
{
  // To gain the client I call the following method
  let client = new issuer.Client();
  client.client_id = 'some id';
  client.client_secret = 'some secret';
}
```

Express and passport have been configured as follows;
expressApp.use(cookieParser('cookie secret');
expressApp.use(bodyParser.json());
expressApp.use(bodyParser.urlencoded({extended: true}));
expressApp.use(cookieSession({
}));
passport.use(openid-client passport strategy);
expressApp.use(passport.initialize());
expressApp.use(passport.session());
expressApp.get('/auth/signin', passport.authenticate('oidc'));
expressApp.post('/auth/signin/callback', passport.authenticate('oidc'));

Steps to reproduce the behaviour:

1.  After navigating to my site https://somedomain/auth/signin the browser redirects to my auth server as expected and after filling in appropriate credentials I am redirected back to the callback URI: https://somedomain/auth/signin/callback
2.  I see an error 'invalid_client' caused by the fact that the token endpoint fails because the client info has not been filled in correctly.
3.  If I manually adjust the variables in the debugger then the token call results in a successful result (ie: an appropriate refresh_token, access_token etc)

**Expected behaviour**
The grant call inside the passport_strategy file is expected to work by providing clientAssertionPayload or specifying the basic auth credentials for servers that only support a token_endpoint_auth_method of client_secret_basic

**Environment:**
 - openid-client version: 3.4.0
 - node version: 12.6.0

**Additional context**

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Hi @dementeddevil 

Unrelated, but this is NOT how you should instantiate new clients.

```js
let client = new issuer.Client();
client.client_id = 'some id';
client.client_secret = 'some secret';
```

This is (as documented)
```js
let client = new issuer.Client({ client_id: 'foo', client_secret: 'bar' });
```

`clientAssertionPayload` has nothing to do with the request payload, the defaulted to `client_secret_basic` client authentication method does not set a body but an `Authorization` header.

If your IdP expects client authentication to use the request payload set your `token_endpoint_auth_method` to `client_secret_post`.

https://github.com/panva/node-openid-client/tree/v3.4.0/docs#client-authentication-methods
