### ISSUE TITLE
client 3.3.0 not working in Electron 5.0.0

### ISSUE THREAD

**Issue by Lakshman1996** [panva/node-openid-client#181]
Hey @panva 

I have an electron 5.0.0 app and there is a node_module which my electron app uses as dependency ( node server ) and i use openid-client inside this node_module. But when i launch my app i get this error.
![Screenshot from 2019-08-21 19-44-28](https://user-images.githubusercontent.com/29203844/63442330-8c319c00-c450-11e9-861d-8da3a6de4fde.png)

I know this error appears when the node version is not supported. But  according to  [Electron 5.0.0 blog ](https://github.com/electron/releases) it supports node  12.0.0 environment

**Environment:**
 - openid-client version: [3.3.0]
 - node version: [12.0.0]
 - Electron: [5.0.0]

 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.

Thanks in advance

**Comment by panva** [comment]
It may be node 12 but its not the right version of V8 underneath, that's why only v6.x electron runtime is [supported](https://github.com/panva/node-openid-client#electron-support).
