### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by hdt1234** [panva/node-openid-client#182]
#37 
Hello, I saw an issue about the examples. You've said that this library is not framework bound, thanks btw, but if anyone could provide an example of using this library with google or facebook, it would be perfect for beginners, like me.

Thanks!

**Comment by panva** [comment]
> if anyone could provide an example of using this library with google, it would be perfect for beginners, like me.

That’s exactly what the quick start readme section explains. 

https://github.com/panva/node-openid-client/blob/master/README.md#quick-start
