### ISSUE TITLE
Passport Strategy not return req.user

### ISSUE THREAD

**Issue by xperiafan13-rom** [panva/node-openid-client#183]
Hi, I use lasted version with nodeJS 12.0

Here is my code:

Endpoints:

```
this.get('/login/openid', passport.authenticate('openid'));

this.post('/login/openid/callback',
    passport.authenticate('openid', {
        successRedirect: '/',
        failureRedirect: '/signup'
    })
);
```

Strategy:
```
let remIssuer = await Issuer.discover('http://127.0.0.1:3020/.well-known/openid-configuration');
const options = {
    client: new remIssuer.Client({
        client_id: 'doex_on_rem',
        response_types: ['token id_token'],
    }),
    params: config.passport.openid
};
const verify = (tokenSet, profile, done) => {

};
passport.use('openid', new Strategy(options, verify));
```

Config:
```
openid: {
    scope: 'openid email profile wallet',
    response_mode: 'form_post',
    nonce: 'doex_rem',
    passReqToCallback: true
}
```

I need get req.user on verify function, how i can get this param?
```
const verify = (req, tokenSet, profile, done) => {
    if (req.user) <= === = How to get this value ?
};
```

**Comment by panva** [comment]
Please be so kind and edit your description to a readable state first.

**Comment by xperiafan13-rom** [comment]
> Please be so kind and edit your description to a readable state first.

Im sorry, I already up this

**Comment by big-kahuna-burger** [comment]
@xperiafan13-rom You don't **get** it there. You **set** it there for the next middlewares in the chain.
Take the subject and pass it to your db adapter to find matching user.

Like: 
```js
(req, userinfo, done) => {
  const user = await Users.findOne(userinfo.sub);
  if(!user) return done(new Error('user not found in db!'));
  req.user = user;
}
```

**Comment by xperiafan13-rom** [comment]
But i need to load req.user on every request, in other strategies like twitter or google (and local) I use this:
```
if (req.user) {
                let token = await Services.redis.setSocketToken(req.user);
                return done(null, getUser(req.user, token));
} esle .... other logic
```
I already add passReqToCallback option to true [(Association in Verify Callback)](http://www.passportjs.org/docs/authorize/)

**Comment by big-kahuna-burger** [comment]
That is not a issue of this library. 
Read passport js docs. Especially the part with `serialize` and `deserialize` user.

**Comment by xperiafan13-rom** [comment]
I already have this
assport.serializeUser(function (user, done) {
    done(null, user);
});
passport.deserializeUser(function (uid, done) {
    done(null, uid);
});

**Comment by big-kahuna-burger** [comment]
If you could set up repo with a reproducible example, I might help you.

**Comment by panva** [comment]
I'm reading http://www.passportjs.org/docs/authorize, i checked the underlying twitter strategy and there's nothing this library isn't doing that twitter would be.

You need to correctly handle building the profile from the tokenset or userinfo response as step one and then adding **`passport.authorize`** call the same way you have probably have it for twitter or google.

You currently apply `passport.authenticate`.
