### ISSUE TITLE
Device Flow: access denied issues

### ISSUE THREAD

**Issue by theogravity** [panva/node-openid-client#185]
**Describe the bug**

Trying out the device flow. Having access denied issues.

**Possibility #1**

The `handler.poll()` call sends an `Authorization` header that when decoded reads `<client_id>:undefined` (no secret key specified). 

I don't think `undefined` is supposed to be part of the value.

**Possibility #2**

If not that, I'm following this guide (were using `Auth0` and followed set-up instructions), and noticed that an `Authorization` header is not sent at all, and instead, the `client_id` is sent as a parameter in the `/token` request:

https://auth0.com/docs/flows/guides/device-auth/call-api-device-auth#example-request-token-post-to-token-url

```js
var request = require("request");

var options = {
  method: 'POST',
  url: 'https://YOUR_DOMAIN/oauth/token',
  headers: {'content-type': 'application/x-www-form-urlencoded'},
  form: {
    grant_type: 'urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code',
    device_code: 'YOUR_DEVICE_CODE',
    client_id: 'YOUR_CLIENT_ID'
  }
};

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
```

**To Reproduce**

```js
    const handler = await client.deviceAuthorization({
      client_id: 'xxxx',
      scope: ['offline_access', 'openid', 'email', 'profile'].join(' '),
      audience: 'xxxx'
    })

   // I'm able to get the user code / url to activate
   // display that to the user, then poll to wait for the activation completion
   const tokens = await handler.poll()
```

I put a breakpoint on `handler.poll()`, and dug down right to the `got(opts)` call in `request.js`. Inspected the `Authorization` header, took the encoded value, decoded it and saw it had `<client-id>:undefined` as the value.

**Expected behaviour**

Authorization header has correct value, and/or client_id is passed as part of the body (maybe allow specification of the header or part of body)?

**Environment:**
 - openid-client version: 3.6.2
 - node version: 12.3.1

**Additional context**

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by theogravity** [comment]
Update: 

Got it to work, but this issue is still valid:

Just realized I can pass in `exchangeBody`, for the client id, but feels redundant, as I'm doing this:

```js
    const handler = await client.deviceAuthorization({
      client_id: 'xxxx',
      scope: ['offline_access', 'openid', 'email', 'profile'].join(' '),
      audience: 'xxxx'
    }, {
      exchangeBody: {
         client_id: 'xxx'
      }
    })
```

**Comment by panva** [comment]
well you should set your client's [`token_endpoint_auth_method` to `none`](https://github.com/panva/node-openid-client/tree/master/docs#client-authentication-methods) for public clients without a secret

**Comment by theogravity** [comment]
Ah, thanks!
