### ISSUE TITLE
How to add state in auth url

### ISSUE THREAD

**Issue by zkhkoku** [panva/node-openid-client#188]
I find that the`authorizationUrl` method would take the following parameter 

```
export interface AuthorizationUrlParameters {
    readonly redirect_uri?: string;
    readonly response_type?: string;
    readonly scope?: string;

    readonly response_mode?: string;
    readonly nonce?: string;
    readonly resource?: string;
    readonly code_challenge?: string;
    readonly code_challenge_method?: string;
}
```

I cannot find a place to pass state to create the auth url, so now I just append state to the string

```
client.authorizationUrl({
            scope: 'openid',
            code_challenge: codeChallenge,
            code_challenge_method: 'S256',
          }) + '&state=testtestme'
```

Is there a right way to pass state?

**Comment by panva** [comment]
You should reference docs over incomplete unofficial typings 

https://github.com/panva/node-openid-client/blob/master/docs/README.md#clientauthorizationurlparameters

> any other authorization parameters may be provided

**Comment by zkhkoku** [comment]
Find the right way to pass in state: 

```
client.authorizationUrl({
            scope: 'openid',
            code_challenge: codeChallenge,
            code_challenge_method: 'S256',
            state: 'testtestme',
          } as any)
```

**Comment by panva** [comment]
That is not the right way with the upcoming official types being developed in #184, you don't need to pass `as any` in those since `AuthorizationParameters` not only enumerates all known to me today but also `[key: string]: unknown;` making you able to pass in any parameter the way you should according to the official documentation.

**Comment by zkhkoku** [comment]
The version I use is "@types/openid-client": "^3.1.6".
There is no `[key: string]: unknown` in `AuthorizationParameters` interface

**Comment by panva** [comment]
I reiterate, once more, **`@types/openid-client` is not official** and any issues you have with it should be directed at its [authors](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/openid-client/index.d.ts).

Once #184 openid-client will bundle its own types and I will ask the authors of the incomplete types to retire it.

**Comment by zkhkoku** [comment]
OK, I understand now, when the official type of openid-client releases, I will change the code. Thanks for reply!
