### ISSUE TITLE
Authorization scope parameter is not space delimited

### ISSUE THREAD

**Issue by danieljee** [panva/node-openid-client#191]
**Describe the bug**

The scope parameter is has to be space delimited but the url query generated by calling authorizationUrl is comma delimited.

The scope parameter of the authorization request looks like scope=openid%2Cuma_protection
but it should be scope=openid%20uma_protection.

[RFC 6749 3.3](https://tools.ietf.org/html/rfc6749#section-3.3)

**To Reproduce**
Steps to reproduce the behaviour:

1.  Call authorizationUrl method of the Client object:
`
app.get('/test', (req, res) => {
    let authUrl = client.authorizationUrl({
        state: "test",
        scope: ["openid", "uma_protection"]
    })
    res.redirect(authUrl)
})
`

**Expected behaviour**
The scope parameter of the authorization request should be space delimited like this scope=openid%20uma_protection

**Comment by panva** [comment]
This is not a bug, you should be passing scope as the space delimited value already, like so.


```js
app.get('/test', (req, res) => {
    let authUrl = client.authorizationUrl({
        state: "test",
        scope: ["openid", "uma_protection"].join(' '),
    })
    res.redirect(authUrl)
})
```
