### ISSUE TITLE
Bug TypeError: The "original" argument must be of type Function 

### ISSUE THREAD

**Issue by mediabuff** [panva/node-openid-client#193]
Get error on 

import {Issuer} from 'openid-client';

***********

TypeError: The "original" argument must be of type Function
promisify

GoogleApi.Tester/GoogleApi.Tester/ClientApp/node_modules/util/util.js:605
602 | var kCustomPromisifiedSymbol = typeof Symbol !== 'undefined' ? Symbol('util.promisify.custom') : undefined;
603 |
604 | exports.promisify = function promisify(original) {

605 | if (typeof original !== 'function') throw new TypeError('The "original" argument must be of type Function');
606 |
607 | if (kCustomPromisifiedSymbol && original[kCustomPromisifiedSymbol]) {
608 | var fn = original[kCustomPromisifiedSymbol];
View compiled
(anonymous function)

GoogleApi.Tester/GoogleApi.Tester/ClientApp/node_modules/jose/lib/jwk/key/rsa.js:44
41 |
42 | var Key = require('./base');
43 |

44 | var generateKeyPair = promisify(async);
45 | var SIG_ALGS = ['PS256', 'RS256', 'PS384', 'RS384', 'PS512', 'RS512'];
46 | var WRAP_ALGS = ['RSA-OAEP', 'RSA1_5'];
47 |
View compiled

**Comment by panva** [comment]
not related to openid-client. Closing.
