### ISSUE TITLE
RFC7592 - OAuth 2.0 Dynamic Client Registration Management Protocol

### ISSUE THREAD

**Issue by nickevansuk** [panva/node-openid-client#196]
Are there any plans to implement support for [RFC7592 - OAuth 2.0 Dynamic Client Registration Management Protocol](https://tools.ietf.org/html/rfc7592)?

This protocol is currently supported by the complimentary project over at https://github.com/panva/node-oidc-provider/

Can we implement this alongside `Client.register(metadata[, other])` ([RFC7591 - OAuth 2.0 Dynamic Client Registration Protocol](https://tools.ietf.org/html/rfc7591))?

**Comment by panva** [comment]
Hi @nickevansuk,

I don't have any plans to support this exotic specification in the client library. I did write a [CLI](https://github.com/panva/openid-client-cli) interface for this a while back tho.

**Comment by nickevansuk** [comment]
Hi @panva, understood. Would accept a PR for it?

Many thanks

**Comment by panva** [comment]
I don't have plans to support it, at all. A PR would still mean i need to continue maintaining the feature. The protocol is not tied to any OIDC functionality. Its a simple HTTP based protocol that, as seen by the linked CLI interface does not need the rest of the library and you can wrap around it.

**Comment by nickevansuk** [comment]
That's great, thanks for letting me know. Will see what we can do with the CLI :)
