### ISSUE TITLE
README Minor Issue

### ISSUE THREAD

**Issue by douglasrlee** [panva/node-openid-client#20]
The README part about using this with passport has a section about params and describes the default value of redirect_uri but it doesn't show it being a part of the client.

Another words
`// redirect_uri defaults to redirect_uris[0]`
should be
`// redirect_uri defaults to client.redirect_uris[0]`

**Comment by panva** [comment]
Could you open a PR with the change? it's super simple with the github UI

**Comment by panva** [comment]
thank you
