### ISSUE TITLE
Seek for suggestion on how to handle client secret that will expire

### ISSUE THREAD

**Issue by alexyeunghk01** [panva/node-openid-client#205]
**Is your feature request related to a problem? Please describe.**
Apple signin is using openid standard, but their client secret has maximum 6 months TTL (not sure if follow the standard). So the passport Strategy will fail to work after 6 months.

**Describe the solution you'd like**
Would like to ask if there is any suggestion to handle this issue?

**Additional context**
- https://developer.apple.com/documentation/signinwithapplerestapi/generate_and_validate_tokens#3262048
- https://bitbucket.org/openid/connect/src/default/How-Sign-in-with-Apple-differs-from-OpenID-Connect.md#markdown-header-peculiarities

 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
Hi @alexyeunghk01,

what apple uses to **derive the client_secret value from a private key that's generated for you** is NOT standard.

What I'd suggest is to have the secret [derivation code](https://gist.github.com/panva/f02ebf9e4c98014836db6efea5919b80) of your process in which you instantiate the client and make sure to reload your processes at least once every 6 months? (shouldn't be a problem for a maintained system to get updates and be restarted once in a while).
