### ISSUE TITLE
Not universal/isomorphic compatible

### ISSUE THREAD

**Issue by Rogger794** [panva/node-openid-client#212]
**Describe the bug**
It is not universal/isomorphic compatible, that means they can't use the fs module and other non-universal modules (net, http, etc.).

**To Reproduce**
Import generators in page inside nextjs pages
```js
Import {generators} from "openid-client"
```

**Additional context**
Error
./node_modules/got/source/utils/get-body-size.js
Module not found: Can't resolve 'fs' in '/home/rogger/Documentos/oidc-server/node_modules/got/source/utils'

**Comment by panva** [comment]
It’s not intended to be. Please read the docs, the intended runtime is Node.js and Electron
