### ISSUE TITLE
TypeScript: Extending the Client class throws runtime exception

### ISSUE THREAD

**Issue by yohanb** [panva/node-openid-client#213]
**Describe the bug**

When using TypeScript, extending the class `Client` throws on runtime the error:
> TypeError: Class extends value undefined is not a constructor or null

Seems to be related to a circular dependency issue when searching for similar issues.

**To Reproduce**
Create `extendedClient.ts` with the following content:
```typescript
import { Client, ClientMetadata } from "openid-client";

class ExtendedClient extends Client {

    constructor(metadata: ClientMetadata) {
        super(metadata);
    }
}

export default ExtendedClient;
```

Steps to reproduce the behaviour:

1.  `tsc extendedClient.ts`
2.  `node extendedClient.js`

**Expected behaviour**
Being able to extend the client to provide custom functionality. For example, setting default metadata for a specific kind of flow:
```typescript
class MsoDeviceCodeClient extends Client {

    constructor(metadata: ClientMetadata) {

        Object.assign(metadata, {
            response_types: ["code"],
            token_endpoint_auth_method: "none"
        });
        
        super(metadata);
    }
}
```

**Environment:**
 - openid-client version: 3.9.1
 - node version: v13.2.0
- tsc version: 3.7.3

**Additional context**
N/A

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
This is not how you get to the Client constructor, the types are wrong it’s not exported. It’s present on an Issuer instance as a property. Please check the docs.
