### ISSUE TITLE
Will this work In Ionic 4 Project ?

### ISSUE THREAD

**Issue by FolabiAhn** [panva/node-openid-client#224]
I'm trying to integrate this into Ionic 4 project with no success. 
After npm install openid-client and using require with 

`const { Issuer } = require("openid-client");`

 I'm getting those errors : 

`[ng] ERROR in ./node_modules/got/source/utils/get-body-size.js`
`[ng] Module not found: Error: Can't resolve 'fs' in 'C:\Users\...\node_modules\got\source\utils'`
`[ng] ERROR in ./node_modules/got/source/utils/timed-out.js`
`[ng] Module not found: Error: Can't resolve 'net' in 'C:\Users\...\node_modules\got\source\utils'`
`[ng] ERROR in ./node_modules/defer-to-connect/dist/index.js`
`[ng] Module not found: Error: Can't resolve 'tls' in 'C:\Users\...\node_modules\defer-to-connect\dist'`

**Comment by panva** [comment]
I believe you’ve answered yourself but incase it isn’t clear from the readme, package json engine or description, the intended runtime is Node.js. 

https://github.com/panva/node-openid-client/blob/master/README.md#how-do-i-use-it-outside-of-nodejs

**Comment by panva** [comment]
https://github.com/panva/openid-client/releases/tag/v6.0.0
