### ISSUE TITLE
Back-Channel Logout Token Validation

### ISSUE THREAD

**Issue by mikejpeters** [panva/node-openid-client#225]
**Is your feature request related to a problem? Please describe.**
I want my RP to use Back-Channel Logout to end the related user session when the user logs out of the OP or another RP, but no methods are available/documented to validate or parse the logout token.

**Describe the solution you'd like**
A method (e.g. `client.validateLogoutToken(req)`) that can be used to validate a back-channel logout request as described in the [specs](https://openid.net/specs/openid-connect-backchannel-1_0.html#Validation). It should also return the payload so that the `sub` and/or `sid` can be used to identify the session.

**Describe alternatives you've considered**
I'm currently using the private methods `client.decryptIdToken()` and `client.validateJWT()` along with some additional validation:

```typescript
const logoutEvent = 'http://schemas.openid.net/event/backchannel-logout';
const idToken = request.payload.logout_token;

// See https://openid.net/specs/openid-connect-backchannel-1_0.html#rfc.section.2.6

await (client as any).decryptIdToken(idToken);

const { payload } = await (client as any).validateJWT(
  idToken,
  client.id_token_signed_response_alg,
  ['iss', 'aud', 'iat', 'events'],
);

if (!(logoutEvent in payload.events)) {
  throw Boom.badRequest(`logout token should contain event: ${logoutEvent}`);
}

if ('nonce' in payload) {
  throw Boom.badRequest('logout token should not contain a nonce claim');
}

// do something with `payload.sid`
```

 - [x] I have searched the issues tracker on github for similar requests and couldn't find anything related.

I can create a pull request if it would be helpful.

Or if this is outside the scope you want for this library, maybe you could make the `decryptIdToken()` and `validateJWT()` methods on the client public?

Thanks for the great project

**Comment by panva** [comment]
Hi @mikejpeters,

I'm not convinced it is time to be adding this validation just yet... aside from generating the logout uris this library does not yet support logout specs.

You may use my `jose` library to do the generic Logout Token validation with the inputs right out of the client and issuer instances.

```js
const jose = require('jose') // ^1.18.0

const keyInput = client.id_token_signed_response_alg.startsWith('HS') ? client.client_secret : await issuer.keystore()

jose.JWT.LogoutToken.verify(token, keyInput, {
  issuer: issuer.issuer,
  audience: client.client_id,
  algorithms: [client.id_token_signed_response_alg]
})
```

**Comment by mikejpeters** [comment]
Thanks @panva, that works :)
