### ISSUE TITLE
Export jose instance

### ISSUE THREAD

**Issue by foray1010** [panva/node-openid-client#226]
**Is your feature request related to a problem? Please describe.**
I am using following version
```json
{
    "jose": "1.22.1",
    "openid-client": "3.12.2"
}
```

As openid-client doesn't support logout token validation by default, I will have to install jose and call `jose.JWT.LogoutToken.verify` manually. This function requires a `key` that I would like to get by `issuer.keystore()`, but the problem is as my jose version is not sync with openid-client one because the openid-client is installed a few days ago and still using jose `v1.22.0`, `jose.JWT.LogoutToken.verify` will throw `key must be an instance of a key instantiated by JWK.asKey, a valid JWK.asKey input, or a JWKS.KeyStore instance`

**Describe the solution you'd like**
`exports.jose = require('jose')` so that I can reuse the same jose instance

**Describe alternatives you've considered**
maybe peer dependency? or do not use `instanceof` but use like class name for checking?

**Additional context**

 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
I intentionally don't expose the dependency, i had that before and it was still messy.

If you want to work with the keys returned by keystore in your own code, i suggest you `key.toJWK()` and then `jose.JWK.asKey(jwk)`.

**Comment by foray1010** [comment]
I was able to reuse the keystore by `jose.JWKS.asKeyStore(key.toJWKS())`, thank you!

**Comment by panva** [comment]
That works too.
