### ISSUE TITLE
Restore the state of your application from before authentication

### ISSUE THREAD

**Issue by awegrzyn** [panva/node-openid-client#230]
Hi,
Thanks for a great library.
Could you help me to understand how can I restore the state of the application from before authentication? In OAuth 2.0 flow I was using `state` to save query parameters that user passed initially.
This will not work with your OpenID implementation as I need to provide state checker.

**Comment by panva** [comment]
Hi @awegrzyn 

I don't understand why something "won't work". `state` is a parameter like any other that you can pass in. Your issue lacks details as to HOW you use this library so I cannot help.
