### ISSUE TITLE
Missing `register` function signature in `Issuer`

### ISSUE THREAD

**Issue by alvis** [panva/node-openid-client#232]
It only affects typescript users.

Currently, if you create an issuer, typescript would complain if you use the client register function. e.g.
```ts
const issuer = new Issuer();

issuer.Client.register();
```

It's due to the type definition on Issuer that the type definition of Client is not typeof Client. Therefore, all the static methods are missing. See below:

https://github.com/panva/node-openid-client/blob/dd2194e8680af9a9b996a1973618999e1d821f01/types/index.d.ts#L517-L523

https://github.com/panva/node-openid-client/blob/dd2194e8680af9a9b996a1973618999e1d821f01/types/index.d.ts#L507-L511

**Comment by panva** [comment]
@alvis can you propose a fix to the types? In addition i noticed the types actually suggest that the Client class is exported when it isnt.

**Comment by panva** [comment]
ping @theogravity who contributed the types in the first place.

**Comment by theogravity** [comment]
Register is defined here:

https://github.com/panva/node-openid-client/blob/dd2194e8680af9a9b996a1973618999e1d821f01/types/index.d.ts#L456

Did you try specifying the Client as the generic impl?

`const issuer = new Issuer<Client>();`

**Comment by panva** [comment]
Okay, couple of issues i'd like to see a PR for

1) DeviceFlowHandle is not exported by the library but is in the types
2) Client is not exported by the library but is in the types
3) make sure the Client methods mentioned here are available by default

**Comment by theogravity** [comment]
1. We actually use the type info from `DeviceFlowHandle` even if it's not exported
2. You still need the typing info for it; we also use it in our project
3. it should already be in there

**Comment by panva** [comment]
> it is already in there as noted in my response above

until the following code passes type checks i wouldn't call it "there"

```
const issuer = new Issuer();

issuer.Client.register({});
```

> You still need the typing info for it

```
type Client = InstanceType<Issuer['Client']>;
```

I'd expect the following to work to get your typing info. And `DeviceFlowHandle` can easily be an exported interface that `DeviceFlowHandle` implements.

**Comment by theogravity** [comment]
Right, which is why I said this prob fixes it:

`export class Issuer<TClient extends Client = Client>`

**Comment by panva** [comment]
It doesn't from what i was able to test.

**Comment by theogravity** [comment]
I'll take a look

**Comment by panva** [comment]
Thank you Theo

**Comment by panva** [comment]
Closing this as `stale`, feel free to come up with a PR to unblock this.

**Comment by panva** [comment]
@theogravity poke
