### ISSUE TITLE
Wrong registration on http://www.passportjs.org/packages/

### ISSUE THREAD

**Issue by freegroup** [panva/node-openid-client#235]
Your registration on passportjs.org has a wrong manifest.

The github on http://www.passportjs.org/packages/openid-client/ contains wrong url.

git+https://github.com/panva/node-openid-client.git  instead of
git://github.com/panva/node-openid-client.git

This ends with missing README and broken github reference on the web site.

**Comment by panva** [comment]
The project pulls the repo link from npm based on the package name. It's not doing the transformation correctly.

Other than [this](https://github.com/passport/www.passportjs.org/pull/90) there's not much I can do.

Thanks for raising this.
