### ISSUE TITLE
idToken

### ISSUE THREAD

**Issue by adon-at-work** [panva/node-openid-client#239]
**Describe the bug**

The `callback` function always expect `id_token` to be present (for response_type=code), which is not true, when `openid` was not requested as part of the `scope` in the authorization call.
```
TypeError: id_token not present in TokenSet
    at Client.validateIdToken (/project/node_modules/openid-client/lib/client.js:697:15)
    at Client.callback (/project/node_modules/openid-client/lib/client.js:471:18)
```

**To Reproduce**
```js
I used Auth0. But this is not specific to auth0.
// authorizationParams
{
  ...
  scope: 'offline_access' // deliberately dropped "openid", as only refresh and access_token are needed
}
```

**Expected behaviour**
 inside `async validateIdToken(tokenSet, ...)`,
```
      if (!idToken.id_token) {
        throw new TypeError('id_token not present in TokenSet');
      }
```
be changed to
```
      if (!idToken.id_token) {
        return tokenSet 
      }
```
I'm proposing a one-liner change as follows. It should NOT throw. This one-liner will work in other cases too, as `validateIdToken()` is always wrapped with conditionals to check if an id_token is present, except in the `callback` function that gave me the error

**Environment:**
 - openid-client version: 3.14.0
 - node version: *

**Additional context**

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Read the callback’s method docs until the very end ;)

**Comment by adon-at-work** [comment]
thanks for the quick reply

**Comment by adon-at-work** [comment]
hi @panva,

I'm getting to the bottom of the issue. It turns out that we do actually need the `openid` scope. The access_token exchanged that we later turn into our API servers do need that scope to operate normally.  

However, at non-confidential clients, we do not want the the `id_token` to be validated, or it will fail because auth0 does not allow us to control `azp` or multiple `aud`.

For the auth code grant flow, 
- using the `oauthCallback()` works for me, which effectively is skipping the idToken validation despite the `/token` endpoint actually returns `id_token`. I believe it's also fine not validating that as the idToken actually comes from the response from a direct call to the legitimate https `/token` endpoint.

However, for the device grant flow,
- we have no luck from there. inside `poll()`, we observed that there're no validations for other tokens such as `access_token`, which I believe it's also due to the fact that the tokens come from a direct call to the legitimate https `/token` endpoint.
```
    if ('id_token' in tokenset) {
      await instance(this).client.decryptIdToken(tokenset);
      await instance(this).client.validateIdToken(tokenset, undefined, 'token', instance(this).maxAge);
    }
```

So, I appreciate if you could kindly consider adding an oauthPoll() or a boolean parameter to `poll()` to bypass the branch above. Thanks

**Comment by panva** [comment]
> However, at non-confidential clients, we do not want the the id_token to be validated, or it will fail because auth0 does not allow us to control azp or multiple aud.

??? 🤷‍♂ 

@adon-at-work i try but I really do not get what you're after.

> I believe it's also fine not validating that as the idToken actually comes from the response from a direct call to the legitimate https /token endpoint.

PSA: Please validate your ID Tokens.

**Comment by adon-at-work** [comment]
Let's not focus on the "PSA" in general. We do not use the id token at the clients, whether it's validated doesn't really matter. We're okay to have id_token dropped if a special boolean parameter is passed in. But if the check is always there, and always throws, that gives us a headache.

To help understand why we're asking to skip id token validation or have it dropped, here's our unique use case:

We're attempting something "crazy" by proxying a couple of endpoints to auth0. So, non-confidential clients connect to our proxy instead of auth0. To simplify deployments, we want to have clients specify `client_id` that is agnostic to the underlying tenants. At the proxy, we have a chance to turn them back. For instance, a client always turns in `happy-client` as `client_id`,
- with `prod.auth0-proxy.company.com`, `happy-client` was internally mapped back to the long random `client_id` assigned for the auth0 prod tenant. 
- similarly, with `stg.auth0-proxy.company.com`, `happy-client` was mapped to another `client_id` that is specific to a different auth0 tenant meant for stage.

No errors thrown for access tokens and refresh tokens. There're no JWT verification for access token in `callback()`, `oauthCallback()` and `poll()`, while refresh tokens are JWT. The validation does NOT have to happen at client side, but it's needed only when it's turned to our API resource servers. 

Everything works fine, until we hit the bumper at id token validation at the clients. Since the JWT validation expects `aud` in id_token to match with the `client_id`, but at the client, it thought `client_id` is `happy-client`, and thus `'happy-client' !== 'long-random-client-id'`.

If auth0 let us configure multiple `aud` for the id token, we could have added `happy-client` (besides the long random real client_id) in all tenants that we use. So, the JWT check won't fail.

**Comment by adon-at-work** [comment]
We thought of falling back to a scope without `openid`, and that turned us to use `oauthCallback()` for the auth code grant flow. But we later figure that dropping `openid` scope is a no-go. Because when the access_token is passed to our resource servers (using the authorization bearer), our resource servers cannot fetch `/userinfo` from auth0 without the `openid` scope.

Okay, so we have no choice but keep `openid` as part of the scope. Then the `openid-client` always wants to validate the `id_token` from the auth0's `token_endpoint` and throw, even though the clients might not even use the `id_token`.

**Comment by panva** [comment]
> We're attempting something "crazy"

Excuse my bluntness, but why are you attempting to use a spec conform piece of software for something, in your own words "crazy". It is not my intention to support every non standard flow that developers come up with and bloat the library surface to maintain on the account of allowing to bend the rules.

As a matter of fact, not throwing when `oauthCallback` encounters an ID Token is something i consider a bug which i'll deal with by either throwing or filtering out the id_token from the response.

> Then the openid-client always wants to validate the id_token from the auth0's token_endpoint and throw, even though the clients might not even use the id_token.

Validating the ID Token claims received is required by the specification, validating its signature is optional when received via a backchannel TLS-covered connection to the AS.

**Comment by adon-at-work** [comment]
If I were you, it makes a lot of sense to not "support every non standard flow that developers come up with and bloat the library surface to maintain on the account of allowing to bend the rules." 

Specifically, I do support `oauthCallback()` to filter `id_token` out, in case someone mistakenly use that instead of the `callback()`, and actually consume the idToken without validating it. More generally, I propose to support an option to drop `id_token` for all circumstances. 

It's my bad for not making it clearer in the first place. Forget about "not validating". Think about just dropping it. Let's also not over-interpret the specs. No specs would mandate clients to ALWAYS use everything, or mandate validating the `id_token` even if it is NOT used. An option to drop it introduces **no** security implications. Even with changing anything, one could still try/catch and swallow the error. I tend to believe that the discussion so far is only about optimization / engineering.

Anyway, we internally have developed a workaround. So the above is just my humble suggestion. Thanks for your time. :)

**Comment by panva** [comment]
> No specs would mandate clients to ALWAYS use everything, or mandate validating the id_token even if it is NOT used.

That is just not the case. If you don't want to validate the ID Token then the only option you have is not requesting one, ergo not having the identity layer (OIDC) from a delegation protocol (OAuth 2.0). That much is 100% clear.

You usecase sounds like just being a proxy for a bunch of providers, in which case i'd expect you to write proprietary software that you'll submit to internal security scrutiny and policies.

**Comment by adon-at-work** [comment]
@panva Thanks for your time
