### ISSUE TITLE
 Can't I specify more than one response_type or scope with Passport Strategy?

### ISSUE THREAD

**Issue by aacn14521** [panva/node-openid-client#24]
I'd like to specify more than one in response_types and scope in Passport Strategy, but I do not seem to be able to do it.
For example, when I make new client with   response_types: ['id_token', 'token'], scope: ['openid', 'email', 'proflie'], 
It seems that response_types = 'id_token', scope = 'openid'.

**Comment by panva** [comment]
These defaults are all documented. You may provide non-default or additional authentication request parameters through various means.

```js
app.get('/auth', passport.authenticate('oidc', {
  response_type: 'the type you want',
  scope: 'openid profile email',
}));
```
