### ISSUE TITLE
 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by AbdulHannan96** [panva/node-openid-client#242]
**Describe the bug**
Getting this warning when I run "npm run build"
./node_modules/got/source/request-as-event-emitter.js 72:18-25
  Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
   @ ./node_modules/got/source/as-promise.js
   @ ./node_modules/got/source/create.js
   @ ./node_modules/got/source/index.js
   @ ./node_modules/openid-client/lib/helpers/request.js
   @ ./node_modules/openid-client/lib/index.js
   @ ./lib/*******.js
   @ ./lib/main.js
   @ multi ./lib/main.js

Steps to reproduce the behaviour:

1.  Install Package
2.  Run npm run build
3.  

**Expected behaviour**
No warnings

**Environment:**
 - openid-client version: 3.14.0
 - node version: 10.16.0

**Comment by panva** [comment]
@AbdulHannan96 I have absolutely zero clue what your `npm run build` script does.

**Comment by panva** [comment]
If i'm to guess, you're running webpack, in which case - don't apply webpack on dependencies. It's mostly not supported and in the case of the only supported js runtime of this library being Node.js, not necessary.

If you're hoping to transpile this and use it in a browser based app, bad luck, this ain't a package that supports that.
