### ISSUE TITLE
Sending specific state while calling passport.authenticate

### ISSUE THREAD

**Issue by kinjalkparmar** [panva/node-openid-client#245]
Hi All,

I am sending a particular state parameter with the authenticate call as below. But that state is changed to a random string. How do I send a specific state and retrieve it after the callback url is called. Basically what I want is, I have couple of parameters based on which I will redirect to different routes. those i am trying to pass as state parameters, but they are changed to some random string  and they are lost. How do I retrieve them. Thanks.

passport.authenticate('oidc', { state: JSON.stringify({ tab: 'placement' }) })

I also tried to change it to base64 and send it but it is always overrided by a random string. I think the state generator is the culprit. how do I disable it.

**Comment by panva** [comment]
@kinjalkparmar 

first of all, you're trying to use `state` completely wrong, given the one line of code you provided, you're completely removing its main purpose - CSRF protection.

You can continue doing that IF you also add a random `nonce` parameter to the request (unless your response_type includes `id_token` in which case its done automatically).

Nevertheless, seeing the [latest strategy code](https://github.com/panva/node-openid-client/blob/v3.14.1/lib/passport_strategy.js#L90-L94), the parameters sent in the authenticate call take precedence over ones defined in the constructor option's `params` object. If `state` is present in either of those the random value will not be used.

I'd also urge you to follow the issue templates, you're not providing the details required for me to help you, such as library version, a code snippet i can reproduce the problem with.

Therefore, either upgrade your dependency version or it's just that your code is not doing what you think it's doing. And definitely provide a working sample of your problem.

**Comment by kinjalkparmar** [comment]
Thanks for the quick reply.

I am using "passport-openidconnect": "0.0.2" and "passport": "^0.4.1". Below is my code. If not the state parameter how does one retrieve the state the user was before the authentication happened.
FYI- I am using okta as AS.
`
const passport = require('passport');
const OidcStrategy = require('passport-openidconnect').Strategy;

app.use(
      session({
        secret: crypto.randomBytes(64).toString('hex').substring(0, 20),
        resave: true,
        saveUninitialized: true,
      })
    );
    app.use(passport.initialize());
    app.use(passport.session());
    passport.use(
      'oidc',
      new OidcStrategy(
        {
          issuer: 'xxxx',
          authorizationURL: 'xxxx',
          tokenURL: 'xxxx',
          userInfoURL: 'xxxx',
          clientID: 'xxxx',
          clientSecret: 'xxxxx',
          callbackURL: 'xxxxx',
          scope: 'profile groups',
          nonce: crypto
            .randomBytes(64)
            .toString('hex')
            .substring(0, 20),
        },
        (issuer, sub, profile, accessToken, refreshToken, params, done) => {
            
          return done(null, profile);
        }
      )
    );

app.use('/login',passport.authenticate('oidc', { state: JSON.stringify({ tab: 'placement' }) }) )`

The call back url has query parameters as ?code="Some random string"& state="the random string that we send".

Thanks for the help again.

**Comment by panva** [comment]
Then you’re in a completely wrong issue tracker.

**Comment by kinjalkparmar** [comment]
I used a different way of calling  passport.authenticate(as shown below) so I can see the authenticate function.
`const authenticator = passport.authenticate('oidc', { state: JSON.stringify({ tab: 'placement' }) })
    authenticator(req, res, next)`
I have put in a debugger and I can see in my object options-->state = "whatever I put in"(example attached
![img1](https://user-images.githubusercontent.com/23006226/78067707-2a7dcc80-7365-11ea-9ce3-87ec383f4bfa.png)
). but in my browsers network tab when it is calling the okta service that is changed to a random string and that same string I am getting back from okta. I don't know where this change to random string is happening.

**Comment by panva** [comment]
You’re opening an issue in a module you’re not actually using. Please take up your issue with your package’s maitainer.
