### ISSUE TITLE
Message-Level Encryption support

### ISSUE THREAD

**Issue by tpimh** [panva/node-openid-client#246]
Message-Level Encryption is required by some OpenID providers. Here is a brief description of [MLE](https://developer.signicat.com/documentation/finnish-trust-network/full-message-level-encryption-for-ftn/). It doesn't seem to be supported by node-openid-client.

If I'm wrong and it really can support it, a simple example would be very appreciated!

**Comment by panva** [comment]
Signed and/or encrypted ID Tokens and JWT Userinfo responses are fully supported - all algs and encs JOSE has registered. You just have to set the according client metadata and provide jwks the provider will encrypt to.

https://github.com/panva/node-openid-client/blob/master/docs/README.md#new-clientmetadata-jwks-options
