### ISSUE TITLE
PKCE Support

### ISSUE THREAD

**Issue by davidgtonge** [panva/node-openid-client#25]
Hi,

Thanks for both this and the node-oidc-provider project!

I'd like to add in support for PKCE.
While this is mainly for public clients, there are use-cases to support it for confidential clients.
I'm thinking of adding a 4th optional argument to this method: 

```javascript
authorizationCallback(redirectUri, parameters, checks) { ... }
// to:
authorizationCallback(redirectUri, parameters, checks, codeVerifier) { ... }
```

No change is needed for the `client.authorizationUrl` method.

What do you think?

**Comment by panva** [comment]
Hi @davidgtonge,

I am much interested in the use-case where this applies to a confidential client that has a kept-secret. I can't think of a situation where PKCE would add any real value to such a client.

What about passing code_verifier as a property of `checks` and if it's present it would be added to the body that goes to the `grant(...)` call.

**Comment by davidgtonge** [comment]
Hi @panva apologies for the delay.
So in an earlier draft of the [FAPI spec](https://bitbucket.org/openid/fapi/commits/8d420fd67b79a1b72c29fac4ea38e6db2b0ff61d?at=master) we had PKCE as required for confidential and public clients. We've now made it only required for public clients, however there is still a "defence in depth" argument for using it for confidential clients. Essentially it provides "Holder of Key" protection for the auth code. So the client is not just proving its identity with its client creds, but also proving that it was the client who started that particular authorization flow.

I also think it's nice to help people understand the specs :-)

I'll do a pull request to add it as an optional property of `checks`.

Thanks

**Comment by ingoncalves** [comment]
The Passport Strategy doesn't take the `code_verifier` param. I'll send a PR with this fix.
