### ISSUE TITLE
Typescript compile error when parent project using got >= 10

### ISSUE THREAD

**Issue by jwheeler-gs** [panva/node-openid-client#253]
Typescript projects which have a dependency on the "got" library at major version 10 or newer and also a dependency on "openid-client"@3.15.0 fail to compile.

Openid-client depends on Got version 9. Everything compiles successfully if the parent project is also on Got version 9, but fails on version 10 or newer with the following error:

```
node_modules/openid-client/types/index.d.ts:12:10 - error TS2614: Module '"../../../../../../../my-project/node_modules/got/dist/source"' has no exported member 'GotOptions'. Did you mean to use 'import GotOptions from "../../../../../../../my-project/node_modules/got/dist/source"' instead?

12 import { GotOptions, GotPromise } from 'got';

node_modules/openid-client/types/index.d.ts:12:22 - error TS2614: Module '"../../../../../../../my-project/node_modules/got/dist/source"' has no exported member 'GotPromise'. Did you mean to use 'import GotPromise from "../../../../../../../my-project/node_modules/got/dist/source"' instead?

12 import { GotOptions, GotPromise } from 'got';
```

I did try adding `@types/got@9` to my project's dev dependencies, but unfortunately this did not help.

Any idea how to fix or work around this problem?

**Comment by panva** [comment]
> Any idea how to fix or work around this problem?

AFAIK openid-client does everything correctly, it requires types from a version it depends on using `@types/got`. If you install a different version on a top level it's typescript's job to recognize the different modules that provide types.

Take it up with `got` or `typescript` directly please.

**Comment by jwheeler-gs** [comment]
Any chance this project could be upgraded to got version 10 or 11 in the near future? Starting with 10, got is now typescript and no longer needs a `@types/got` dependency.

**Comment by panva** [comment]
Not without requiring a new major release, which i don't have a good reason for. Yet. And FWIW, the name of the game for next major will be to remove got as a dependency altogether and just rely on Node's `http/https`

**Comment by jwheeler-gs** [comment]
In case anyone else runs into this same issue, I've created a related issue in the Typescript project:
https://github.com/microsoft/TypeScript/issues/38233
