### ISSUE TITLE
Custom Profile Claims for Auth0

### ISSUE THREAD

**Issue by livelo-app** [panva/node-openid-client#254]
I am currently using Auth0 for user authentication on my NextJS Application. An issue that I am currently dealing with is attempting to get **user_metadata** and **app_metadata** in my user profile. My understanding is that this is a custom claim since it is not a standard OIDC Claim. 

I have looked through the docs for openid-client and haven't found any information regarding custom claims and was hoping someone had an idea on how to go about this. 

Auth0 has provides this useful guide in regards to User Profiles and Custom Claims:
[https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims
](https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims)

**Comment by panva** [comment]
This client does not filter claims in any way, what your idp returns is what you’ll get.
