### ISSUE TITLE
Cannot customizing individual HTTP requests

### ISSUE THREAD

**Issue by buithienquyet** [panva/node-openid-client#257]
Hello!
I tried using  custom HTTP request, but not working.
I assigned a funtion:
![ảnh](https://user-images.githubusercontent.com/26385748/80907782-dc812d80-8d43-11ea-9a9a-213e7f78f68d.png)
and console logged new options:
![ảnh](https://user-images.githubusercontent.com/26385748/80907726-8f04c080-8d43-11ea-81fa-9449b3ceeb28.png)
 but it still throws error with default options timeout 2500ms when calling client.callback() after that
![ảnh](https://user-images.githubusercontent.com/26385748/80907700-4220ea00-8d43-11ea-9889-64e95b719c9a.png)
I don't know what wrong? 
Thank you very much!

**Comment by panva** [comment]
It’s probably not a client instance timeout, an Issuer instance timeout can happen too when fetching its jwks_uri for the first time.

**Comment by buithienquyet** [comment]
> 
> 
> It’s probably not a client instance timeout, an Issuer instance timeout can happen too when fetching its jwks_uri for the first time.

Thanks for your response, but I initialize Issuer by passing metadata, I tried setting global options and it worked but i want to set options locally for each client.
Thanks!

**Comment by panva** [comment]
client !== issuer

Read the text before the code snippet 

https://github.com/panva/node-openid-client/blob/master/docs/README.md#customizing-individual-http-requests

**Comment by buithienquyet** [comment]
> 
> 
> client !== issuer
> 
> Read the text before the code snippet
> 
> https://github.com/panva/node-openid-client/blob/master/docs/README.md#customizing-individual-http-requests

I have fixed this, I must set options for both client and issuer.
Thank you very much!
