### ISSUE TITLE
Non-conforming http basic authentication

### ISSUE THREAD

**Issue by gordonmleigh** [panva/node-openid-client#258]
I realise that your (excellent) library is standards compliant, but given that the existence of non-compliant IdPs is sufficient to warrant a several line "not my fault" comment in the code, would you accept a PR to special-case support for non-conforming servers in some way? E.g. by a using a `client_secret_basic_not_encoded` scheme or something like that.

In an ideal world we'd ask the third parties to fix their implementation and they would appreciate being guided in the path to standards compliance, but I don't think that is hugely likely in reality.

**Comment by panva** [comment]
> would you accept a PR to special-case support for non-conforming servers in some way?

I would not.

There are plenty of non-conformities that can occur and I will not have one flag for each.

To work around specific IdP-quirks when it comes to http auth see [customizing http requests](https://github.com/panva/node-openid-client/blob/v3.15.0/docs/README.md#customizing-individual-http-requests) and replace the authorization header with one that fits your bill.
