### ISSUE TITLE
support OAuth 2.0 Pushed Authorization Requests

### ISSUE THREAD

**Issue by foray1010** [panva/node-openid-client#259]
**Is your feature request related to a problem? Please describe.**
Since oidc-provider already support OAuth 2.0 Pushed Authorization Requests - draft 01, I would like openid-client to support it too so that my project could use it, I am willing to open PR for it.

**Describe the solution you'd like**
not sure what is the best interface design, maybe we create another function called `pushedAuthorizationUrl`?

**Describe alternatives you've considered**
N/A

**Additional context**

 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
Hi @foray1010,

thank you for offering to work on this interface. Given that PAR is still an early draft i am hesitant to adding it to the client library. Rest assured that once stable, as one of the draft's authors i will be adding first party support.

It shouldn't be an issue for you to make those requests using `got` or similar request library.

You may even use the existing API and construct a [dirty client instance method](https://gist.github.com/panva/6adab7b3a4ba2fde9c361e4a9dc665e2) to re-use some of the client internals.

**Comment by panva** [comment]
[v4.6.0](https://github.com/panva/node-openid-client/releases/tag/v4.6.0) now supports [draft-ietf-oauth-par-06](https://tools.ietf.org/html/draft-ietf-oauth-par-06).
