### ISSUE TITLE
v1.7.0 fails in npm install

### ISSUE THREAD

**Issue by mattwoolnough** [panva/node-openid-client#26]
Install of latest client fails with following error.

```
> npm i openid-client
npm ERR! cb() never called!
```

Previous version is fine.

**Comment by panva** [comment]
yarn publish is clearly not ready ;) 
re-published as 1.7.1 using npm, thanks for taking the time to report this, can you please confirm its fine now? It works on my station now but one can never be sure.

**Comment by mattwoolnough** [comment]
Works 100%. Keep up the good work! 🥇
