### ISSUE TITLE
Random error: jwks_uri must be configured on the issuer on '/callback' route

### ISSUE THREAD

**Issue by nathanprabhu** [panva/node-openid-client#260]
**Actual Behavior**
- On client.callback, randomly I get the error '**jwks_uri must be configured on the issuer**' even though the Authorization server has a jwks_uri configured. This behavior is not consistent. On restarting node server, it goes away. 

**Steps to Reproduce the Problem**
- Create a oidc client
- client.callback()

**Version:**
"openid-client version": "3.15.0"

**Platform:**
MacOSX Catalina 10.15.2 (19C57)
node v10.15.3

---

**Client creation:**
```
const { Issuer, generators } = require('openid-client');
            await Issuer.discover(issuer)
              .then(function (oidcIssuer) {
                  oktaClient = new oidcIssuer.Client({
                      client_id: clientId,
                      client_secret: clientSecret,
                      redirect_uris: [ callbackUrl ],
                      response_types: [ 'code' ]
                  });
                  oktaClient.state = generators.state();
              });

```
**Callback**
```
const params = oktaClient.callbackParams(req);
oktaClient.callback(callbackUrl, params, { state: State })
        .then(function (tokenSet) {
          ...
        });
```

**Error**
TypeError: jwks_uri must be configured on the issuer\n    at assertIssuerConfiguration (..../node_modules/openid-client/lib/helpers/assert.js:15:11)\n    at Issuer.keystore (..../node_modules/openid-client/lib/issuer.js:79:5)\n    at Issuer.queryKeyStore (..../node_modules/openid-client/lib/issuer.js:125:33)\n    at Client.validateJWT (..../node_modules/openid-client/lib/client.js:963:31)\n    at Client.validateIdToken (..../node_modules/openid-client/lib/client.js:705:60)\n    at Client.callback (..../node_modules/openid-client/lib/client.js:471:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7) ....

**Issuer metadata **
GET {{url}}/.well-known/openid-configuration?client_id={{clientId}}
```
{
    "issuer": "https://{{url}}",
    "authorization_endpoint": "https://{{url}}/oauth2/v1/authorize",
    "token_endpoint": "https://{{url}}/oauth2/v1/token",
    "userinfo_endpoint": "https://{{url}}/oauth2/v1/userinfo",
    "registration_endpoint": "https://{{url}}/oauth2/v1/clients/{{clientId}}",
    **"jwks_uri": "https://{{url}}/oauth2/v1/keys?client_id={{clientId}}",**
    "response_types_supported": [
        "code"
    ],
....
....
}
```

**Comment by panva** [comment]
Use the discovery document url instead of issuer identifier for the Issuer.discover call. 

For some reason Okta’s RFC8414 doesn’t list jwks.

**Comment by panva** [comment]
Expanding on my answer, check the difference between your server's

/.well-known/oauth-authorization-server
/.well-known/openid-configuration

They should be aliases for one another and they're likely not.

If you discover issuer with the string `{{url}}/.well-known/openid-configuration` you'll be fine as it won't attempt a general discovery using both mechanisms
