### ISSUE TITLE
Authorization Example Sample Code

### ISSUE THREAD

**Issue by a3986** [panva/node-openid-client#265]
Hi,

I am using keycloak for my authentication and authorization purposes and using Angular as frontend and NodeJS as backend.

I am able to do the authentication using this library in node js but I am not able to figure out, how to do the authorization using the same.

I have created different resources, scopes in keycloak and also attached different permissions but could not make it work using this library. 

It would be great, if someone could point me to a complete example on how scope or resource based authorization could be done using the library.

Last but not least, thank you for the library :)

**Comment by panva** [comment]
This is not a Resource Server library. You can merely request resources according to your IdP’s scheme by adding authorization request parameters.

**Comment by a3986** [comment]
> This is not a Resource Server library. You can merely request resources according to your IdP’s scheme by adding authorization request parameters.

Thanks for your response. Is there an example on how this is done? I was expecting a 403 error on requesting a resource if user does not have access to it.

**Comment by panva** [comment]
Once again, that is not the responsibility of this library, its an openid connect client, not a resource server. It’s job is to give you means to establish an end-user session and accomodate requesting claims/tokens from the authorization server.

**Comment by roggervalf** [comment]
I could suggest using https://www.npmjs.com/package/iam-policies in a middleware. Also in backend you should check if token is valid from your provider, get the userId and so on.
