### ISSUE TITLE
Separate redirect URL from discovery URL

### ISSUE THREAD

**Issue by cnoelle** [panva/node-openid-client#266]
Trying to use the library for authentication (Auth flow with PKCE) with passport in a docker-compose setup. The identity provider in this case is reachable from the NodeJS server via a docker-internal host name, such as http://keycloak:8080, whereas the browser reaches the identity provider via http://localhost:8080. The issuer discovery is successful at http://keycloak:8080, but when a user tries to login in the browser he is redirected to the same URL, which cannot be resolved by the browser. It would hence be necessary to use a different redirect URL for the user. I could not find a way to do this in the documentation, is it possible?

**Comment by panva** [comment]
I won’t be working on something nonstandard like this as an “improvement”, if you want to change some of the responses to show a different url or redirect elsewhere, use a post middleware to do so.

**Comment by panva** [comment]
Or better yet, invest time in a proper deployment setup that works externally but internally resolves to your internal hosts.

**Comment by panva** [comment]
I thought this was open under a different repo so i've deleted my previous answers based on that wrong assumption.

**Comment by panva** [comment]
No, such thing isn't possible with discovery.
