### ISSUE TITLE
Modify the issuer URL after discover

### ISSUE THREAD

**Issue by Lakshman1996** [panva/node-openid-client#269]
Hi

I am discovering the issuer using Microsoft common URL to perform multi tenant auth.
i tried modifying the issuer URL in metadata as mentioned in this [issue](https://github.com/panva/node-openid-client/issues/58)
The value in the metadata object remains same even after assigning a new value. 
Is there anything that i am missing?

Thanks

**Comment by panva** [comment]
Why are you trying to do that? Ever since 2.5.0 that shouldn't be needed anymore.

**Comment by Lakshman1996** [comment]
I get this error `unexpected iss value, expected https://sts.windows.net/{tenantid}/, got: https://sts.windows.net/8d88c9c2-2058-486d-9cd4-2fc9010326bc/` when is use `https://login.microsoftonline.com/common` for discover.

I have to use common endpoint for Multi tenant auth to work in [AAD](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant)

**Comment by panva** [comment]
Can't you use `https://login.microsoftonline.com/common/v2.0` instead?

**Comment by panva** [comment]
`v3.15.3` released that handles v1 common the same as v2 common.

Please consider [supporting](https://github.com/panva/node-openid-client?sponsor=1) the library if it provides value to you or your company and this and the previous support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.

**Comment by Lakshman1996** [comment]
Thanks for the quick reply.
Using v2.0 worked.
