### ISSUE TITLE
Unable to get Authorization_Code flow working

### ISSUE THREAD

**Issue by frikkievb** [panva/node-openid-client#27]
Hi,

Hope all is well.  I've been struggling for almost a whole day to get the authorization code flow implemented.  

 I am also using the oidc-provider as a backend. What I have that is custom is a custom adapter (that implements sequelize) and a custom account. (Not sure if this is where the problem is)

The only error I get is: POST /idp/token 500 41.618 ms - 72

Please help!  :(

**Comment by panva** [comment]
1) wrong library. 
2) your adapter is likely wrong, run your provider with DEBUG=oidc-provider:* to get some details.
