### ISSUE TITLE
Device flow auth nonce check

### ISSUE THREAD

**Issue by katsanva** [panva/node-openid-client#271]
Hello. 

I've encountered a weird behavior with polling the TokenSet for device auth:
Mu OpenId server gives the id token that has nonce in JWT payload, but unfortunately the `handle.poll()` rejects with 

```sh
RPError: nonce mismatch, expected undefined, got: 4ab20ceb73b2624074f30aa7e9284173
    at Client.validateIdToken
```

This happens because of [id token check in device handle](https://github.com/panva/node-openid-client/blob/master/lib/device_flow_handle.js#L74) fails due to the [actual check](https://github.com/panva/node-openid-client/blob/master/lib/client.js#L732) returns true.

So I'm just curious - is this behavior intended and there should be no nonce is the JWT (is there any RFC on that) or it's an issue in openid-client?

Just tested that manually:

```js
> const payload = {nonce: 'fff'}
undefined
> nonce = undefined
undefined
> nonce !== null && (payload.nonce || nonce !== undefined) && payload.nonce !== nonce
true
```

**Comment by panva** [comment]
There should be no server generated nonce in the id token unless you’re sending one in. Using nonce for decice flow makes no sense anyway.

**Comment by katsanva** [comment]
Thank! Isn't that better to ignore nonce in the JWT for this case instead of throwing an error?

**Comment by panva** [comment]
Nop, it’s better if the server doesn’t fill the id token with random values the client should be generating.

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-openid-client?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.

**Comment by panva** [comment]
Think about it this way - if this was about code flow, for which you're not required to send in a `nonce` as a client but you got one back anyway (generated by the server) - the client would throw because it's possible a mixup attack happened.

**Comment by katsanva** [comment]
Thank you for such a detailed response!
