### ISSUE TITLE
Consider stopping using `lodash`?

### ISSUE THREAD

**Issue by s100** [panva/node-openid-client#272]
There is a [prototype pollution vulnerability in `lodash`](https://github.com/lodash/lodash/issues/4738), which `lodash`'s maintainers [seem not to be acting on](https://github.com/lodash/lodash/pull/4759). My suggestion is that moving away from `lodash` entirely might be an expedient way to resolve this.

Related, previously: #5, #171

**Comment by panva** [comment]
openid-client does not utilize the method in question and is therefore not affected. Nevertheless, removing lodash is something I’d support driving a PR forward for if you’re offering putting the time into it.
