### ISSUE TITLE
Regression in patch release 3.15.4

### ISSUE THREAD

**Issue by ddolcimascolo** [panva/node-openid-client#273]
Hi,

This ticket is a reminder, I'll provide all the details on Monday morning max, maybe during the weekend. 

We've started to see build failures with an automated upgrade of openid-client from v3.15.3 to v3.15.4. I don't have access to full build logs currently, but what I can tell is that an HTTP request performed by the client when refreshing an access token is now different. Again, I'll provide all the details soon.

Thanks,
David

**Comment by panva** [comment]
@ddolcimascolo thank you, i'll investigate as much as i can but any details would be helpful.

**Comment by panva** [comment]
@ddolcimascolo hopefully 3.15.5 addresses the regression. 🤦 , `merge` !== reversed `defaultsDeep`, apologies. If it's not resolved, please provide more details in a bug report.

**Comment by ddolcimascolo** [comment]
Hey @panva I can confirm 3.15.5 fixes it. Thanks

**Comment by panva** [comment]
Much appreciated 🌟
