### ISSUE TITLE
Passport strategy callback doesn't handle 403 errors properly

### ISSUE THREAD

**Issue by keatsk** [panva/node-openid-client#275]
**Describe the bug**
When my OP sends an "Access Denied" error to the callback URL, client.js throws an RPError, 'state missing from the response'.  (line 402).

In passport_strategy.js line 83, the reqParms gets set to { error: "access_denied", error_description: "Unauthorized").  I think at that point you should just throw an Access Denied error, no?

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
// Issuer configuration (issuer.metadata) and how it is constructed (discovery or manual?)
{
  // Discovery.  URL: https://a-ci.labshare.org/_api/auth/ls/.well-known/openid-configuration
}
// Client configuration (client.metadata) and how it is constructed (fromUri or manual?)
{
  // ...
}
```

Steps to reproduce the behaviour:

1.  Use the passport strategy to request a resource that is forbidden by the OP, generating an access-denied error.

**Expected behaviour**
I think the passport-strategy should throw an Access Denied error when the OP sends the error=access-denied query parameter in the callback request.

**Environment:**
 - openid-client version: 3.15.5
 - node version: v13.14.0

**Additional context**

 - [X] the bug is happening on latest openid-client too.
 - [X] i have searched the issues tracker on github for similar issues and couldn't find anything related.
<img width="1216" alt="passport_strategy js2020-07-07 18-09-22-Access_Denied-1" src="https://user-images.githubusercontent.com/17165689/86851551-2c9ca900-c081-11ea-9341-28204cd8949f.png">
<img width="1188" alt="passport_strategy js2020-07-07 18-09-22-Access_Denied-2" src="https://user-images.githubusercontent.com/17165689/86851558-30c8c680-c081-11ea-869a-4ca839a0070f.png">
<img width="1342" alt="client js-2020-07-07 18-14-40-Access_Denied" src="https://user-images.githubusercontent.com/17165689/86851564-345c4d80-c081-11ea-9805-efee7aed7acd.png">

**Comment by keatsk** [comment]
FYI, I was able to make a workaround by adding a check in the express route handler.  See below:

```js  
app.get('/oauth/callback', (req, res, next) => {
    var reqParams = req.query;
    if (reqParams.error) {
      var err = new Error(reqParams.error);
      err.status = (reqParams.error === "access_denied") ? 403 : 400;
      err.message = reqParams.error_description;
      next(err);
    } else {
      passport.authenticate('oidc', {
        callback: true,
        successReturnToOrRedirect: '/users',
        failureRedirect: '/',
        failureFlash: true
      })
    }
  }
  );`

**Comment by panva** [comment]
Your OP is not including the state callback parameter as it should, hence the state check error. Check with your OP to fix this issue.

**Comment by keatsk** [comment]
Thanks for the quick response. You're right, it appears that the state parameter is required in the error response if supplied in the request per https://openid.net/specs/openid-connect-core-1_0.html#AuthError.  I suspect many OPs don't honor that, but I'll try to get a fix for mine.

**Comment by panva** [comment]
> I suspect many OPs don't honor that

All proper ones do. It’s part of the spec, it’s mandatory to implement. Amongst my circle, all do.
