### ISSUE TITLE
How is it possible to skip the "consent screen"?

### ISSUE THREAD

**Issue by gigo1980** [panva/node-openid-client#276]
We have the following scenario.
After the user has logged in you are seeing the consent screen where you have to approve the scopes that are requested.

We would skip this step, is this still possible? And if, how can we can hook into that process/workflow?

**Comment by big-kahuna-burger** [comment]
It is not recommended but in any case, here it goes:

```js
const {
  interactionPolicy: { Prompt, base: policy }
} = require('oidc-provider')

interactions.remove('consent')
```

But then if your user is requesting scopes, you need to grant them all when calling `interactionFinished` or you will get error.
Something like this:
```js
       await provider.interactionFinished(req, res, {
          select_account: {},
          login: {
            account: account.accountId
          },
          consent: { accepted: [params.scope.split(' ')] } // this line matters, note that the params come from interaction details
        }, {
          mergeWithLastSubmission: false
        })
```

**Comment by panva** [comment]
How is this an openid-client question?

**Comment by panva** [comment]
@gigo1980 your IdP controls when a consent screen is shown. The client software does not control that.
