### ISSUE TITLE
Why is validateIdToken() private?

### ISSUE THREAD

**Issue by smithamax** [panva/node-openid-client#28]
You've got validateIdToken() documented in the code as private.

It would seem to me that an advantage of using JWTs is that you can then pass them to your other services to authenticate the user.

In those secondary services I would think you would want to validate the JWT by doing something similar to...
```
const token = req.header.authorization.slice('Bearer '.length);
client.validateIdToken(token)
.then(result => {
  // assert some other things about the user
});
```

Is it just an oversight that this is documented as private, or is there some reasoning behind this?

Any insight would be appreciated.

**Comment by panva** [comment]
It is not an oversight, i intentionally kept the method undocumented and unmentioned in the readme for now as i am not happy with it's signature and the fact that you need to chain decrypt and validate. There's also alot of ID Token related validations that simply does not happen in the exact same snippet you posted.
