### ISSUE TITLE
Token: RPError: failed to decode JWT

### ISSUE THREAD

**Issue by uramen** [panva/node-openid-client#283]
Hello,
I have some trouble with: 
```
.callback(redirectUrl, params, {
          code_verifier: codeVerifier,
          state: params.state,
  })
```

an error that I've received:
![Screenshot from 2020-08-12 15-43-30](https://user-images.githubusercontent.com/12251236/90016465-b22ffc00-dcb2-11ea-9389-1f537dc8e28c.png)

discovery URL:
https://preprod.signicat.com/oidc/.well-known/openid-configuration

config:
```
Issuer.discover(discoveryUrl).then((googleIssuer: any) => {
  client = new googleIssuer.Client({
    client_id: clientId,
    client_secret: clientSecret,
    redirect_uris: [redirectUrl],
    response_types: ['code'],
  });

  console.log('Signicat created');
});
```
Seems that I need something to encrypt.
It will be great If somebody has some thoughts.

**Comment by panva** [comment]
https://github.com/panva/node-openid-client/blob/master/docs/README.md#new-clientmetadata-jwks-options

```
id_token_encrypted_response_alg: <string>
id_token_encrypted_response_enc: <string>
```

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-openid-client?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that the library and such support will be available to you in the future.

**Comment by uramen** [comment]
Sorry for bothering you @panva but I stuck a little. I put JWK from the SIGNICAT platform as you said and got this:

![Screenshot from 2020-08-18 14-32-46](https://user-images.githubusercontent.com/12251236/90508091-b69b5f80-e15f-11ea-997d-69adb779557e.png)

my config now:

```
 client = new googleIssuer.Client(
    {
      client_id: clientId,
      client_secret: clientSecret,
      redirect_uris: [redirectUrl],
      response_types: ['code'],
      id_token_encrypted_response_alg: 'RSA-OAEP',
      id_token_encrypted_response_enc: 'A128CBC-HS256',
    },
    {
      keys: [
        {
          kty: 'oct',
          use: 'sig',
          kid: 'any.oidc client secret.test.jwk.v.1',
          k: <my secret key>,
          alg: 'HS256',
        },
      ],
    }
  );
```
It seems that format is different, should I ask them for something like this:
```
{
   "kty":"EC",
   "crv":"P-256",
   "x":"MKBCTNIcKUSDii11ySs3526iDZ8AiTo7Tu6KPAqv7D4",
   "y":"4Etl6SRW2YiLUrN5vfvVHuhp7x8PxltmWWlbbM4IFyM",
   "d":"870MB6gfuTJ4HtUnUvYMyJpr5eUZNP4Bk43bVdj3eAE",
   "use":"enc",
   "kid":"1"
   // https://tools.ietf.org/html/rfc7517
},
```
Or I can change it by myself. I'm not good in such encrypting stuff sorry :(
Thanks!

**Comment by panva** [comment]
`RSA-OAEP` means they're encrypting using your RSA public key. Ergo, you should have a private key that corresponds with that already.
