### ISSUE TITLE
Allow custom discovery props

### ISSUE THREAD

**Issue by kevinhos** [panva/node-openid-client#29]
It looks like one can't access custom discovery props because they are filtered: https://github.com/panva/node-openid-client/blob/master/lib/issuer.js#L47.

It seems like custom discovery props should be accessible in some way. Perhaps the raw discovery response can be exposed by a getter on the `Issuer`.

**Comment by panva** [comment]
Good idea.

**Comment by panva** [comment]
See https://github.com/panva/node-openid-client/blob/master/CHANGELOG.md#version-180
