### ISSUE TITLE
Module '"crypto"' has no default export

### ISSUE THREAD

**Issue by brianpooe** [panva/node-openid-client#291]
[
![Screenshot 2020-09-14 at 18 27 04](https://user-images.githubusercontent.com/13939613/93112633-87253780-f6b8-11ea-9d4e-ab6f558401c5.png)
](url)

**Expected behaviour**
Not throw an error when program starts.

**Environment:**
Nestjs 7
 "openid-client": "^4.1.0",
 node v12.18.3

**Additional context**

 - [x ] the bug is happening on latest openid-client too.

**Comment by panva** [comment]
Might be a tooling issue. Based on what's in the issue i can't help, nor can i reproduce.

**Comment by brianpooe** [comment]
Thanks for the swift response but not sure what you mean by tooling, this is a nodejs environment and dependencies are built the same throughout its framework counterparts. If it helps this is typescript.

But i noticed your library does support types so not sure what is the issue.

**Comment by panva** [comment]
I’m no ts expert but both jose (in its types) and crypto (through @types/node) do have default exports. 

Hence me saying this is likely a tooling issue on your end, a tsconfig one maybe?

**Comment by panva** [comment]
I've pushed a small change, see if it helps.

**Comment by brianpooe** [comment]
I was about to do a pull request for this. Thanks.
