### ISSUE TITLE
acr_values not passed to auth request

### ISSUE THREAD

**Issue by taxcycle** [panva/node-openid-client#296]
I understood from this post:

"The authenticate call on your init route accepts additional parameters to pass to the auth. request.

_Originally posted by @panva in https://github.com/panva/node-openid-client/issues/81#issuecomment-371926921_"

That the following code should work to add acr_values to the auth call:
app.get('/auth', (req, res, next) => {
      passport.authenticate('oidc', { acr_values: 'thevalue' })(req, res, next);
    });

but it doesn't.

Should this work? If not, is this something node-openid-client should do?

**Comment by panva** [comment]
> but it doesn't.

Hi @taxcycle, I have tests in the project's test suite telling me it does. If you want either provide a failing test case or a sample code I can effortlessly run.
