### ISSUE TITLE
I like to fetch multiple access tokens for multiple resources provided by my Identity Provider

### ISSUE THREAD

**Issue by ktikku** [panva/node-openid-client#297]
I'm using **openid-client** package to perform **OIDC authentication with Azure AD**.
Azure AD provides multiple access tokens for multiple resources (like Microsoft Graph: https://graph.microsoft.com
Microsoft 365 Mail API: https://outlook.office.com)
How can I **fetch and maintain multiple access tokens** via openid-client package?

**Comment by panva** [comment]
@ktikku that's a question of when and what parameters to include to the basic protocol requests. I am unable to tell you the specifics for AAD.
