### ISSUE TITLE
openId-client Strategy

### ISSUE THREAD

**Issue by Cyben** [panva/node-openid-client#298]
The use of Strategy is not so clear, I tried to use the Strategy of this lib with no real success.
I there a way for giving a code example for using it (Couldn't find anywhere something about it).
It will really help.

**Comment by panva** [comment]
The use of this strategy is the same as any other strategy, with the exception of its constructor. I do not mean to supplement Passport documentation here in this repo.

If you're not sure how to use passport strategies, maybe consider not using passport at all, maybe something [like so](https://github.com/auth0/express-openid-connect) will be more fitting for your use.
