### ISSUE TITLE
Initiating Login from a Third Party

### ISSUE THREAD

**Issue by RALGIE** [panva/node-openid-client#299]
Hello,

Great work on this module :) I have the following question. Does this module support Initiating Login from a Third Party (https://openid.net/specs/openid-connect-core-1_0.html#ThirdPartyInitiatedLogin). 

I want to use this to authenticate an Public Mobile App. I have multiple dynamic OpenId Providers to authenticate the User.

**Comment by panva** [comment]
Third Party Initiated Login is something you build into a specific route that initiates functionality of an openid client. I don't see what this client could be bringing there.
