### ISSUE TITLE
Generate the script for fragment processing

### ISSUE THREAD

**Issue by aacn14521** [panva/node-openid-client#30]
I think it would be nice to have a function to return the script for processing fragments to User Agent, as shown in OpenID Connect Core 1.0 15.5.3.
What do you think?

**Comment by panva** [comment]
Hi @aacn14521,

i don't think this is something that has just "one" solution, or one way of doing it. The example in the spec does an ajax request, i myself would always do a urlencoded form post instead. But this depends on the type of application you are running and what behavior you need.

**Comment by aacn14521** [comment]
Thank you for your response.
I agree that using scripts is one of the solutions and depends on the application.
However, I think that there are not many types of methods, and I feel that there are not a few people who can help by providing scripts. It may be better to also provide a urlencoded form.
I also expect that it will be better for users to improve shared code than to create ad hoc scripts or forms.

**Comment by panva** [comment]
Hi @aacn14521, I am afraid I do not fully understand your request. How would the library providing a fixed snippet help anyone if it needs to be tailored anyway. So not part of the library's API for sure. A guidance / example? Sure, that's doable. Can you create a wiki page with what you think is needed?

And as a general rule of thumb, if your Issuer supports form_post response_mode, use it ;)
