### ISSUE TITLE
login.gov, private_key_jwt, and client_assertion iat

### ISSUE THREAD

**Issue by delfuego** [panva/node-openid-client#302]
I'm testing using this library in order to build an OIDC login workflow with login.gov (largely following [this example](https://github.com/18F/identity-oidc-nodejs-express)), and could get all the way through the login process but was never ending with a successful login. After debugging, I was seeing that the login.gov token endpoint was returning an error saying that the `iat` property of the `client_assertion` was invalid, which was curious to me; I'm wondering if the problem is at their end or in the library.

I was able to get logins to succeed by first commenting out the `iat` property (in `helpers\client.js#authFor`), and then by just subtracting one from it (`iat: timestamp - 1`). That's... weird to me, that the server is fine with an `iat` that's one second previous.

Thoughts? Do you think this is something worth reporting to the login.gov folks (somehow)? On the flip side, is there a downside to generally setting the `iat` property back one (or a few) seconds? I don't want to maintain a fork of this code just to be able to interoperate with login.gov... so I'd love to make sure this gets addressed/looked into on one end or the other!

**Comment by panva** [comment]
Seems like clock tolerance is what login.giv needs.

**Comment by panva** [comment]
And you don't need to fork, you can use the clientAssertionPayload option of whatever method you're using to set your iat.

**Comment by panva** [comment]
Furthermore while iat in the past makes sense logically, it isn't a normative requirement anywhere. And its redundant when exp is also part of the jwt.

**Comment by delfuego** [comment]
Hmmm -- I'll look into that, @panva. I'm currently just using your Passport strategy directly; tracking back where I have the opportunity to set the clientAssertionPayload, it looks like it's at the time I construct the Strategy. Which means I can't dynamically set an iat in the clientAssertionPayload, unless I'm missing something.

**Comment by panva** [comment]
Try without passport. It'll be worth it ;)

**Comment by delfuego** [comment]
Is there an example anywhere of how to use it in an Express app without using Passport?

**Comment by panva** [comment]
No copy paste development in this repo. Sorry.

**Comment by panva** [comment]
https://github.com/panva/node-openid-client#authorization-code-flow

This should be enough for anyone to apply to <insert framework>
