### ISSUE TITLE
How do I sent a state parameter in the authorization request?

### ISSUE THREAD

**Issue by blake-mealey** [panva/node-openid-client#304]
I'm struggling to find a built-in way to send a `state` parameter in the authorization request. My provider (Okta) requires it for the implicit flow. 

I am able to workaround this by manually adding the query parameter to the URL:

```ts
...

const nonce = generators.nonce()
const state = generators.state()

const loginUrl =
  client.authorizationUrl({
    scope: 'openid email profile',
    response_mode: 'form_post',
    nonce
  }) + `&state=${state}`

...

const params = client.callbackParams(ctx.req)
const tokenSet = await client.callback(ctx.url, params, {
  nonce,
  state
})
```

This feels pretty hacky and I know I must be missing something but I haven't found any related properties in the docs.

**Comment by panva** [comment]
<img width="1058" alt="Screenshot 2020-10-26 at 17 27 07" src="https://user-images.githubusercontent.com/241506/97199687-91a31880-17b0-11eb-91d4-b6d300b89a3e.png">

**Comment by blake-mealey** [comment]
🤦‍♂️ Thank you.

Would you consider adding `state` as an optional parameter in the options object for TS users? I can open a PR if you'd like

**Comment by panva** [comment]
sure, seems like it was omitted by mistake.
