### ISSUE TITLE
OpenApi / swagger codegen and open id client

### ISSUE THREAD

**Issue by FaizRasool** [panva/node-openid-client#306]
Hi i have a bit of challenge:

I need to use the open id client somehow in conjunction with openapi or swagger base generated client.

Any suggestions for best approach?

I am playing with this libraries:

"https://github.com/ferdikoomen/openapi-typescript-codegen"

It gives me a model and service to make a resource request but ideally i want somehow it helps me rather construct the object and give me back header and body that i can inject into open id client

```client.requestResource(URL, tokenSet, {body, headers} )```

**Comment by panva** [comment]
> Any suggestions for best approach?

Apologies, none
