### ISSUE TITLE
Proxy setup and Meteor support

### ISSUE THREAD

**Issue by p3pp8** [panva/node-openid-client#307]
Hello, finally i've managed to upgrade my Meteor project to version 1.11 that supports Node v12 and upgraded to OpenId Client 4.2.1, but, after upgraded and run my app i've faced 2 main issues, **the first** is that i can't use **request** client anymore, and that was necessary as my app is behind a proxy, **the second**  is on discovery function that ignores my remote config and try to connect to 127.0.0.1:443 and that, of course, ends to a socket error.  Any suggestion really appreciated!

**Comment by panva** [comment]
https://github.com/panva/node-openid-client/blob/master/docs/README.md#customizing
https://github.com/sindresorhus/got#agent
https://github.com/sindresorhus/got#proxies

Request is gone, no way around that, you should set up your proxy agent with got using the http customization option.

**Comment by p3pp8** [comment]
Thank you!

**Comment by p3pp8** [comment]
Can't test whether the proxy override code works or not as the discovery using .well-known config fails for the "well-known" GOT bug:

```
W20201102-10:01:04.950(1)? (STDERR) RequestError: connect ECONNREFUSED 127.0.0.1:443
W20201102-10:01:04.953(1)? (STDERR)     at ClientRequest.<anonymous> node_modules\got\dist\source\core\index.js:953:111)
W20201102-10:01:04.955(1)? (STDERR)     at Object.onceWrapper (events.js:422:26)
W20201102-10:01:04.957(1)? (STDERR)     at ClientRequest.emit (events.js:327:22)
W20201102-10:01:04.959(1)? (STDERR)     at ClientRequest.EventEmitter.emit (domain.js:483:12)
W20201102-10:01:04.961(1)? (STDERR)     at ClientRequest.origin.emit (\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
W20201102-10:01:04.963(1)? (STDERR)     at TLSSocket.socketErrorListener (_http_client.js:426:9)
W20201102-10:01:04.965(1)? (STDERR)     at TLSSocket.emit (events.js:315:20)
W20201102-10:01:04.967(1)? (STDERR)     at TLSSocket.EventEmitter.emit (domain.js:483:12)
W20201102-10:01:04.999(1)? (STDERR)     at emitErrorNT (internal/streams/destroy.js:92:8)
W20201102-10:01:04.999(1)? (STDERR)     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
W20201102-10:01:05.015(1)? (STDERR)     at processTicksAndRejections (internal/process/task_queues.js:84:21)
W20201102-10:01:05.016(1)? (STDERR)     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
```

Any other suggestion?

Thanx in advance!

**Comment by panva** [comment]
I am tracking no bugs around discovery. [This](https://github.com/panva/node-openid-client/issues/301#issuecomment-708027004) could be related but is more likely your proxy is in the way.

**Comment by p3pp8** [comment]
That happens **before** creating the client, so the proxy server can't be the problem, it's raised on: 

```
Issuer.discover( https://my.server.com/.well-known/openid-configuration')
```

I think proxy setup is done after a client instance is created, but probably i'm missing something... Can it be configured directly on Issuer before calling the discovery function? 

Thank indeed for your help!

**Comment by panva** [comment]
Yes it can, and its in the docs i've shared.

**Comment by p3pp8** [comment]
Sorry, got it! thanx!
