### ISSUE TITLE
customize http status code when redirect by passport authentication

### ISSUE THREAD

**Issue by read-only-man** [panva/node-openid-client#308]
When callback
using passport strategy in xhr
`if (Object.keys(req Params).length === 0)`
it send auth request again
but redirect didn't work.
Because it is xhr

Passport redirect function syntax allows status parameter.

`strategy.redirect = function(url, status) `

So I want to pass redirect status at OpenIDConnectStrategy.prototype.authenticate.

(e.g )
```Javascript
OpenIDConnectStrategy.prototype.authenticate = function authenticate(req, options, redirect_status)
```

that way I can manage redirect pattern.
Is such a feature possible?

**Comment by panva** [comment]
> but redirect didn't work.

Isn't that just because your XHR client "follows" redirects? fetch does this by default, set it to manual and you'll be able to get the 302 response and its location header. Then you can handle redirection on your end.

**Comment by read-only-man** [comment]
thank you
