### ISSUE TITLE
more logging / debug options

### ISSUE THREAD

**Issue by JoshBarr** [panva/node-openid-client#31]
Hey @panva, 

Thanks for making a great library. This makes doing OIDC in Node really easy. 

I was wondering, would you consider accepting a PR to add some logging? The API I was considering was this:

```js
/*
interface ILogger {
  log(message: string)
  warn(message: string)
  info(message: string)
  error(message: string)
}
*/

const issuer = new Issuer({
   logger: console,  /* implements ILogger */
});

// Would inherit logger from issuer, but could also pass logger into the client
const client = new issuer.Client({ 
   logger:  console,  /* implements ILogger */
});
```

My use case is a container cluster which I monitor via CloudWatch. It's not easy to tell what errors we're getting from `got`, particularly when proxies or redirects are involved. If you're happy with the API, I can write the code/tests.

**Comment by panva** [comment]
Hello @JoshBarr, i think this would be a great addition, even better if you could contribute it.

my $.02 towards the API solution direction,
- do we need issuer / client instance specific loggers?
- do we need Issuer / Client specific loggers? > can't we do with one logger setting (similar to defaultHttpOptions set on Issuer) This would greatly reduce the efforts and keep the API simple and understandable.
- can the default logger state be disabled / not provided?
- is your problem error specific? Would you consider Issuer/Client being an EventEmitter?

**Comment by JoshBarr** [comment]
You're right, we probably don't need client-specific loggers. Something like this?

```js
const Issuer = require('openid-client').Issuer;
Issuer.logger = console;
```

Making the Iss/Client into EventEmitters would actually be really neat – certainly would make logging easier, as we can just attach the logger to the events.

**Comment by panva** [comment]
This already looks the right amount of "simple" I shoot for ;) Let me get back to you tomorrow, I will give it some thought whether to do emits or a logger.

**Comment by panva** [comment]
@JoshBarr what do you think of a simple inclusion of [debug](https://github.com/visionmedia/debug) instead?

**Comment by JoshBarr** [comment]
Debug would be fine for our use case - we only need to log some internals for troubleshooting purposes.

**Comment by panva** [comment]
Sounds good!

**Comment by panva** [comment]
Feel free to open PR, 'till then i will be closing non-Issues.

**Comment by vancouverwill** [comment]
hi @panva I needed to add in some logs into a fork of this repo so we could see why it was failing for us, i.e. which stage and for what reason and thought it could be useful for others.

It looks like this issue is closed for a while but I still think it useful. 

There are a couple of other things I need to do such as update docs and add logging to other functions but wanted to see your initial thoughts before I invest too much 👍
