### ISSUE TITLE
dynamic userAgent in all requests

### ISSUE THREAD

**Issue by slavab89** [panva/node-openid-client#32]
I've noticed that in all requests that the client makes, the useragent is always static. Should it better be dynamic based on the user-agent of the request? The real users user-agent?

It is possible to change it using `Issuer.defaultHttpOptions` and maybe change that setting every time before a request is made using the client but its not that elegant in my opinion because its should be a default that is set 1 time.
I didnt see that the code allows you to pass a dynamic header / user-agent through the flow.

**Comment by panva** [comment]
Hey @slavab89,

> I've noticed that in all requests that the client makes, the useragent is always static. Should it better be dynamic based on the user-agent of the request? The real users user-agent?

It should not, a backend process making a request is not the same as the user-agent the end-user is using to hit that backend.

> It is possible to change it using Issuer.defaultHttpOptions and maybe change that setting every time before a request is made using the client but its not that elegant in my opinion because its should be a default that is set 1 time.

I would not recommend to rely on setting this option before every request, the function call may end up making multiple requests and by then the setting may be changed.

> I didnt see that the code allows you to pass a dynamic header / user-agent through the flow.

That's because it does not. I don't see the need to allow for per function call headers. If you wish to have per-client (client.defaultHttpOptions) settings i would be ok with that and would be happy to see a PR with such a feature.

**Comment by slavab89** [comment]
Great. I'll definitely think about this.
You point about the request being processed by the backend seems valid, but usually it happens due to a redirect from the provider, no?

If i'm looking at [authorizationCallback](https://github.com/panva/node-openid-client/blob/master/lib/client.js#L262). We arrive here originally (with passport as an example) due to a redirect that the provider returned to the end-user, and then we makes an additional request to convert the `authorization_code` into a token. Is this request considered on behalf of the end-user or the backend?

**Comment by panva** [comment]
Let me ask you, is it the end-user's user-agent making the request or your backend?

**Comment by slavab89** [comment]
Well, basically its the backend. But the one that triggered that backend request is a redirect from the end-user.

authenticate --(`/auth` route in provider)--> provider 
-> [login happens] --(redirect back to openid-client)--> authenticate --(`/token` route in provider)--> openId-client --(`/certs` route in provider)--> success....

Hopefully you'll understand what i tried to "draw" here XD

So, in `/auth/` path, i get a end-user userAgent (clicks on login button)
during the login process in the provider, its the end-user userAgent (inputs data)
**on `/token` `/certs` path its a backend (static) userAgent**
The trigger to the last steps is the redirect from the provider. Because the process after the login happens pretty much automatically without the user making any action on its own, is it considered backend flow with backend userAgent?

I thought that maybe because of the redirect, it does involve the end-user - its not server-server interactions.

**Comment by panva** [comment]
Making a backend call with frontend user-agent... *shrugs*

It was more of a rhetorical question. Of course the communication from your client (nodejs process with openid-client) to an OP is a backend one, the end-user's user-agent is not involved.
