### ISSUE TITLE
code_challenge_method is not send with the authorize request

### ISSUE THREAD

**Issue by borleth** [panva/node-openid-client#322]
**Describe the bug**

In order to test PKCE on our IDP, we see the code_challenge_method is not send during the first authorize endpoint.
So in reference to the RFC, the IDP need understand it's "plain" challenge, the default value.

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
// Issuer configuration (issuer.metadata) and how it is constructed (discovery or manual?)
{
  // ...
}
// Client configuration (client.metadata) and how it is constructed (fromUri or manual?)
{
  // ...
}
```

Steps to reproduce the behaviour:

1.  
2.  
3.  

**Expected behaviour**

**Environment:**
 - openid-client version: [e.g. v3.14.0]
 - node version: [e.g. v8.9.0]

**Additional context**

 - [ ] the bug is happening on latest openid-client too.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Hi. I'm closing this issue because it does not follow the template and provides no details as to how you're using the module, not even a understandable description.
