### ISSUE TITLE
Doesn't work with Auth0

### ISSUE THREAD

**Issue by rochdev** [panva/node-openid-client#34]
When using this library with Auth0, either automatically with `Issuer.discover()` or manually with `new Issuer()`, the following error is thrown:

```
issuer must be configured with introspection endpoint
```

Since both this library and Auth0 are certified, I am not sure which one is at fault so I am opening an issue on both.

This library requires an `introspect_endpoint` which Auth0 doesn't provide. From my understanding, it seems that this is an OAuth2 specific concept that is not required by OpenID.

**Comment by rochdev** [comment]
I asked Auth0 about this as well and this was their reply:

*I'm curious however on why your library would try to use a token introspection. In OAuth, token introspection is meant to be used by the resource server to check if the access_token sent by a client is valid. So, a backend API that receives access tokens might require an introspection endpoint, but a client who uses OIDC does not need one.
OIDC builds on top of Auth0. When using OIDC (that is, scope=openid), the provided access_token is meant to be used against the identity provider's /userinfo endpoint, which returns information about the logged in user. So it's the identity provider the one who would need to check if the access_token is valid, not the client using it (the client should treat access tokens as opaque strings, no matter the format). Since in the case of Auth0 (as in most OIDC identity providers) the authorization server (who issues the access token) is the same as the identity provider (who provides information about the user), there's no need for token introspection because we "know" internally if the token is valid. 
The OIDC client application just receives the access_token and uses against the /userinfo endpoint to get information about the user. If the token is not valid, it's up to the identity provider to return 401, but the client shouldn't try to validate the access token.*

**Comment by panva** [comment]
I'm not sure why you would assume the example application which is designed to showcase all available functionality against fully featured OP would work against all other issuers. 

The only place in the code where `introspection_endpoint` is required is if you call the method. The assertion is there to simply let you know that your Issuer is not configured / misses support for this particular spec.

**Comment by rochdev** [comment]
Fair enough. Would it be useful however to provide some kind of offline validation for the token?

For example with these steps: https://auth0.com/docs/api-auth/tutorials/verify-access-token

**Comment by panva** [comment]
Access, Refresh and other Bearer tokens do not always come as JWTs, for the most part they come as opaque strings.

The steps described in Auth0 documentation do nothing more then validate the JWT signature and return it's payload - [auth0/node-jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) which they link out to is more then suitable for this task.
