### ISSUE TITLE
client_secret_jwt broken using Azure as Provider > 4.5.1

### ISSUE THREAD

**Issue by fraadsbrandth** [panva/node-openid-client#348]
**Describe the bug**
When upgrading to version > `4.5.1` we get an error from Azure when the token-request is done. `AADSTS50027: JWT token is invalid or malformed.` I have investigated and found out that the `JWT` here is the `client_assertion` sent in the token request since we use `client_secret_jwt`. 

Now that the `audience` is a list with both issuer & token_endpoint Azure rejects the request with the mentioned error.

It seems to have been introduced in this commit [da7d2f0090cd0323a14702bcca77536eb4e2b49d](https://github.com/panva/node-openid-client/commit/da7d2f0090cd0323a14702bcca77536eb4e2b49d)

It would have been nice to be able to explicitly set this `audience` to comply with how Azure validates this JWT.

Decoded `client_assertion` jwt body  > `4.5.1`
```json
{
  "iat": 1616744700,
  "exp": 1616744760,
  "jti": "7EpXOyzp6748W-yDzbucpH016_WRkuA_Oqtyi5ysHGM",
  "iss": "oidc-auth-proxy",
  "sub": "oidc-auth-proxy",
  "aud": [
    "http://azure-mock:8100/v2.0",
    "http://azure-mock:8100/v2.0/token"
  ]
}
```
Decoded `client_assertion` jwt body  <= `4.5.1`
```json
{
  "iat": 1616744827,
  "exp": 1616744887,
  "jti": "dLou0ji3IJTkMJTG-dQPJeRFZVV_rHwiQ1YQVx5-Tzo",
  "iss": "oidc-auth-proxy",
  "sub": "oidc-auth-proxy",
  "aud": "http://azure-mock:8100/v2.0/token"
}
```

**To Reproduce**
I have some integration tests running [here](https://github.com/navikt/oidc-auth-proxy/tree/master/integration-tests) with a `azure-mock`. This docker image might be private, but can fix that if needed.

**Environment:**
 - openid-client version:  `> 4.5.1`
 - node version: `v15.12.0`

**Additional context**
 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
> It would have been nice to be able to explicitly set this audience to comply with how Azure validates this JWT.

You can. see the `extras.clientAssertionPayload` option on all calls where client authentication takes place.

**Comment by fraadsbrandth** [comment]
Thanks @panva! I missed that option. I needed two tries, but now it works with latest version :)

**Comment by panva** [comment]
@fraadsbrandth happy to help. 
Please consider [supporting](https://github.com/panva/node-openid-client?sponsor=1) the library if it provides value to you or your company and this was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.
