### ISSUE TITLE
on app.js

### ISSUE THREAD

**Issue by jakavila** [panva/node-openid-client#36]
Hey ,

I´m getting an issue on running the client. What am i missing?

/node/node-openid-client/example/app.js:25
app.use(async (ctx, next) => {
^
SyntaxError: Unexpected token (
at createScript (vm.js:56:10)

Hoping to get some help.. tks

**Comment by panva** [comment]
The library works with node >= 4 no worries there, but the example app is using koa2, which requires node >= 7.6.0 for async/await support (you should really pay attention to the npm install warnings ;)).

The same example using old syntax is in an older tree (https://github.com/panva/node-openid-client/tree/64e1b5ebd63e5296448947d22bbde63490c41810)
