### ISSUE TITLE
Examples for Express JS.

### ISSUE THREAD

**Issue by gulatiy** [panva/node-openid-client#37]
Hi @panva ,

Can you please suggest some example for express using this library.

Thanks :)

**Comment by panva** [comment]
The functionality as documented is not web framework bound, what it provides are not middlewares, but simple Promise-based functions. If you have a specific question about usage ask that one. Thank you.

**Comment by sauravpandit** [comment]
I think as a beginner a small example will be really helpful with express and authorization flow.
