### ISSUE TITLE
Getting invalid token after grant

### ISSUE THREAD

**Issue by gwumkt** [panva/node-openid-client#372]
![image](https://user-images.githubusercontent.com/28900951/120705804-f1893c80-c4c0-11eb-8a42-c7faf3720ba7.png)

the log of userinfo is "invalid_token (invalid token provided)" although i just make the grant.

my actual goal is to save the access token in memory and to be able to know later what is his grantType

**Comment by panva** [comment]
You need to take this up with your idp.

**Comment by gwumkt** [comment]
What does it means?
