### ISSUE TITLE
Mandatory state check

### ISSUE THREAD

**Issue by PaulSzymanski** [panva/node-openid-client#377]
**Describe the bug**
If `state` is present in response, `Client.callback` and `Client.oauthCallback` require `checks.state`.

https://github.com/panva/node-openid-client/blob/v4.7.4/lib/client.js#L395-L397

**Expected behaviour**
At least with response type of `code` this check should be optional.
This is only mandatory for implicit flow responses: https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse
The check is not required for authorization code flow: https://openid.net/specs/openid-connect-core-1_0.html#AuthResponse

**Environment:**
 - openid-client version: v4.7.4

**Comment by panva** [comment]
This is intended behaviour. If you used state with the authorization request, you are expected to verify it on the callback.

**Comment by PaulSzymanski** [comment]
Can you please elaborate?
Verifying is not mandatory for all scenarios.

[The OAuth 2.0 Security Best Current Practice](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-13#section-3.1) states that this is not mandatory for redirect-based flows
> If PKCE [RFC7636] is used by the client
   and the authorization server supports PKCE, clients MAY opt to not
   use "state" for CSRF protection, as such protection is provided by
   PKCE.  In this case, "state" MAY be used again for its original
   purpose, namely transporting data about the application state of the
   client (see Section 4.7.1).

PKCE already protects against CSRF. With one caveat. Error responses can be spoofed. However, the value of this attack is limited. And this can be mitigated by returning the code_challenge in the error response.

I am using a redirect-based flow. I have to use state, to carry information the client requires when it receives the authorization response. My client knows, at best, a set of values that `state` might be set to.

Additionally, without PKCE state is often used to deliver the CSRF protection nonce plus to carry state information (e.g., `state = <nonce>+<correlationid>`.
This kind of scheme is not supported by the checks of the callbacks as well.

**Comment by panva** [comment]
@PaulSzymanski the BCP says that you may opt to not use "state" for CSRF protection, yes, but it does not alleviate the need to verify the "state" value you receive back is identical to the one sent in. That's how "state" is defined.

Verifying is mandatory for all cases when you sent a "state" in.

For schemes other than "what is sent in is what comes out" or cases where you use "state" to carry application state information (that should still be signed if containing things like target return URL), you can simply use the returned state value as your input to callback checks after you've validated it using any scheme you want.
