### ISSUE TITLE
Invalid token issuer

### ISSUE THREAD

**Issue by mrik974** [panva/node-openid-client#38]
Hi,

I have a tricky issue and I need your help to solve it.

I'm implementing OpenID Connect on my own infrastructure. I have set up an Openshift platform and installed my services on it.

I have a Keycloak (an OpenId Connect server) installation and my app that connects to it.

The keycloak is available externally at `identity.myapp.com`
My app is available externally at `app.myapp.com`

Openshift doesn't let my app talk to Keycloak using the external route, as they are in the same network and can't access the Openshift Integrated proxy from the inside.

Therefore my OpenId Issuer setup is :

```
const keycloak = new Issuer({
                    issuer: "https://identity.myapp.com/auth/realms/master",
                    authorization_endpoint: "https://identity.myapp.com/auth/realms/master/protocol/openid-connect/auth",
                    token_endpoint: http://keycloak-openshift:8080/auth/realms/master/protocol/openid-connect/token",
                    userinfo_endpoint: "http://keycloak-openshift:8080/auth/realms/master/protocol/openid-connect/userinfo",
                    jwks_uri: "http://keycloak-openshift:8080/auth/realms/master/protocol/openid-connect/certs"
                });
```

Note that the issuer and authorization endpoint point to the external route, and all the other endpoints used by the app point to the internal route.

When I try to retrieve the token I get this error : 

```
{ OpenIdConnectError: invalid_token
    at Client.gotErrorHandler (/opt/app-root/src/node_modules/openid-client/lib/error_handler.js:8:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  message: 'invalid_token',
  error: 'invalid_token',
  error_description: 'Token invalid: Invalid token issuer. Expected \'http://keycloak-openshift-3:8080/auth/realms/master\', but was \'https://identity.myapp.com/auth/realms/master\'',
  state: undefined,
  scope: undefined }
```

As you can see, the library expects the issuer value in the token to be set at the internal route, but Keycloak sets it to the external route (as it is called from outside).

Is there a way to tell the library to check the issuer with the value passed at the `Issuer` instantiation ? Or is there a way to disable the issuer validation (i'm in a private Docker network)

For sure I cannot use the external route from my app. My only other solution would be to take Keycloak out of my platform but I lose the easy scalability and reliability benefits.

**Comment by panva** [comment]
Hi @mrik974, what is the url for your discovery and it's returned content?

**Comment by mrik974** [comment]
Hi, the URL for discovery is `https://identity.myapp.com/auth/realms/master/.well-known/openid-configuration`
It's returned content is 
```
"issuer": "https://identity.myapp.com/auth/realms/master",
"authorization_endpoint": "https://identity.myapp.com/auth/realms/master/protocol/openid-connect/auth",
"token_endpoint": "https://identity.myapp.com/auth/realms/master/protocol/openid-connect/token",
"token_introspection_endpoint": "https://identity.myapp.com/auth/realms/master/protocol/openid-connect/token/introspect",
"userinfo_endpoint": "https://identity.myapp.com/auth/realms/master/protocol/openid-connect/userinfo",
"end_session_endpoint": "https://identity.myapp.com/auth/realms/master/protocol/openid-connect/logout",
"jwks_uri": "https://identity.myapp.com/auth/realms/master/protocol/openid-connect/certs",
"check_session_iframe": "https://identity.myapp.com/auth/realms/master/protocol/openid-connect/login-status-iframe.html",
```

But, as I said, my question is a tricky one.
The nodejs app I use is in the same internal Docker network, set up by Openshift. It can't access the keycloak server through the external URIs and must access it using an internal domain name. I can't override this setting. That's why I can't use auto discovery and set the URIs used by the app to `http://keycloak-openshift:8080` instead of `https://identity.myapp.com`

**Comment by panva** [comment]
hang on a minute - the config you have is right - but the error comes from the OP, not client. What i mean the RP just throws what the OP returned at you.

**Comment by mrik974** [comment]
Oh, I get it now. 
How does the OP know it's being called using it's internal domain name ?

**Comment by panva** [comment]
well the host http header ;) this seems to be an issue with keycloak or your setup, as you described it the configuration in the original post is the way i would do it.

**Comment by mrik974** [comment]
OK I really get it now, thank you for your time :)

**Comment by qinfanpeng** [comment]
> OK I really get it now, thank you for your time :)

Hi, how did you workround your problem?

**Comment by mrik974** [comment]
The workaround was to leave it as-is. I mean, if the URL used by the browser is not the same URL the client is calling to validate the token, the keycloak server will refuse the validation.
I had to create a dummy DNS entry for my specific setup that allowed the client to have access to keycloak from the inside, but with the same domain name as the browsers have access to it from the outside.
