### ISSUE TITLE
OPError: invalid_client (Unauthorized grant type: refresh_token)

### ISSUE THREAD

**Issue by matt-hahn** [panva/node-openid-client#380]
**Describe the bug**
We are using openid-client to deal with our auth provide. All the functions work great except `client.refresh`. When we call this, we get the following error:
```
OPError: invalid_client (Unauthorized grant type: refresh_token)
```
We tried explicitly setting the `grant_type` multiple ways:
1. Setup `grant_types: ['refresh_token']` when initializing the `client`
2. Use `client.grant` to set the `grant_type` and `refresh_token` values

All code examples are following

**To Reproduce**
We have a couple of function that deal with client creation. For the sake of simplicity, I will lay them out as they were in a single file.
```js
// This is how we initiate our client. We get all of the constants from .env but in this case I set them to an empty string.

// Oauth
import {Issuer} from 'openid-client';

const getClient = async ({
  callbackUrl = 'redirectUrl',
  clientId = 'clientId',
  clientSecret = 'clientSecret',
  authUrl = 'authorizationUrl',
} = {}) => {
  const issuer = await Issuer.discover(authUrl);
  return new issuer.Client({
    client_id: clientId,
    client_secret: clientSecret,
    redirect_uris: [callbackUrl],
    grant_types: ['authorization_code', 'refresh_token'],
  });
};

// This is our service to get a new token set with a `refresh_token`. Service gets the `refresh_token` from the controller, which gets it from the request (and it is alway set properly).
const refreshToken = async ({refresh_token}) => {
  const client = await getAuthClient();
  const tokens = await client.refresh(refresh_token); // <-- this is where the error happens
  return tokens;
};

// This is a helper function just for this example
const run = async () => {
  try {
   const tokens = await refreshToken({refresh_token: 'your_refresh_token'});
   console.log(tokens);
  } catch(error) {
    console.log(error);
  }
}
```

Steps to reproduce the behaviour:

1.  Copy code from the example into a file
2.  Setup openid variables in the `getClient` function
3.  Setup a `refresh_token` value in the `run` function
4. Run script

**Expected behaviour**
`const tokenSet = client.refresh(refresh_token);` should not throw `OPError: invalid_client (Unauthorized grant type: refresh_token)` but instead return a `tokenSet`

**Environment:**
 - openid-client version: v4.7.4
 - node version: v16.4.2

**Additional context**

 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
This is an error from your OP.
