### ISSUE TITLE
Nonce defaulted to undefined when using refresh

### ISSUE THREAD

**Issue by jotunskij** [panva/node-openid-client#4]
I might have misunderstood something, but why does the id token validation default to 'undefined' for nonce when validating the id token of a refresh token call?

I've looked through the open id specs and even though they don't explicitly talk about the nonce field in the section on refresh tokens, they do however state that "otherwise, the same rules apply as apply when issuing an ID Token at the time of the original authentication".

I'm using the Mitre Open ID connect server and if I try to refresh, the tokens I get back have the nonce field set to the same value as the original id token I used for my first authentication.

As I see it the nonce value for id token validation should be set to undefined only if the original token did not use nonce.

Thoughts on that?

**Comment by panva** [comment]
In my past experience the nonce is lost at the client side when doing a refresh. But i see the point and there are few solutions to consider

1. have the client#refresh method accept a second argument where { nonce } can be passed just like to client#authorizationCallback, regardless of the type being sent in (string or TokenSet). This would require manually deciding whether to pass in a nonce or not.
2. when refresh is called with a TokenSet the nonce to check is going to be read from the id_token member of this set. This would require the providers to preserve the original nonce with the refreshes.

Other options? As you can see different provider implementations interpret the spec differently, however i believe the nonce SHOULD be present, (i will adjust my server to do so).

Personally i like option 2 but am afraid of the failed validations when refresh is called just with the string value of the refresh_token and for servers that fail to interpret the spec this way.

**Comment by panva** [comment]
see 1d32edf

**Comment by jotunskij** [comment]
Thanks for the quick reply and commit! I agree that 2 seems that the most viable solution. Nonce should be present, but optional in the refresh process, I agree.

If you make a release containing the commit I'll make sure to try it out with our Mitre server asap.

**Comment by panva** [comment]
I've updated the provider used in the example to issue a nonce with refresh already, had the same issue as you then, the commit fixes that issue. Release later today.

**Comment by panva** [comment]
Fixed in v0.5.1
