### ISSUE TITLE
Incompatible assert OpenIDConnectStrategy when using koa-passport

### ISSUE THREAD

**Issue by ppvolto** [panva/node-openid-client#40]
I current Switch my App from Express and found a Problem with the OpenIDConnectStrategy when using koa-passport

I think the following message pops up since koa-passport mocks the RequestObject into a Object and so its can never be a IncomingMessage or a String
```AssertionError [ERR_ASSERTION]: #callbackParams only accepts string urls or http.IncomingMessage```

I hope That can be fixed or i need a alternative for koa-passport or passport in general.

**Comment by panva** [comment]
Please post a stripped down working example of an application that exhibits this behavior, i can help then.

**Comment by panva** [comment]
see if [v1.11.1](https://github.com/panva/node-openid-client/compare/v1.11.0...v1.11.1#diff-50cfa59973c04321b5da0c6da0fdf4feR217) solves your problem

**Comment by ppvolto** [comment]
Thanks Helps with this Problem... next is to work out how i can interconnect your provider model with koa-passport... but thats current my problem alone
