### ISSUE TITLE
Problem with esbuild 0.12.26

### ISSUE THREAD

**Issue by MonoAnji** [panva/node-openid-client#403]
**Describe the bug**
When updating to esbuild 0.12.26 running an application that uses the openid-client the application crahses with:
```
node_1      | file:///runtime/middlewares.js:26
node_1      |   throw new Error('Dynamic require of "' + x + '" is not supported');
node_1      |         ^
node_1      | 
node_1      | Error: Dynamic require of "util" is not supported
node_1      |     at __require (file:///runtime/middlewares.js:26:9)
node_1      |     at node_modules/openid-client/lib/issuer.js (file:///runtime/middlewares.js:17341:23)
node_1      |     at __require2 (file:///runtime/middlewares.js:44:45)
node_1      |     at node_modules/openid-client/lib/index.js (file:///runtime/middlewares.js:17724:19)
node_1      |     at __require2 (file:///runtime/middlewares.js:44:45)
node_1      |     at file:///runtime/middlewares.js:151846:31
node_1      |     at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
node_1      |     at async Loader.import (node:internal/modules/esm/loader:178:24)
node_1      |     at async Object.loadESM (node:internal/process/esm_loader:68:5)
node_1      |     at async handleMainPromise (node:internal/modules/run_main:63:12)
```

**To Reproduce**
Probably any project that  updates to the new esbuild version?

Steps to reproduce the behaviour:

1.  Build
2.  Run in node

**Expected behaviour**
I expect the application not to crash ;)

**Environment:**
 - openid-client version: 4.7.5
 - node version:  v16.9.0

**Additional context**
I mentioned that also on the merge request in esbuild that causes this behaviour, maybe the mistake is in there?
https://github.com/evanw/esbuild/pull/1580#issuecomment-916795733

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
There are no dynamic requires in this library's code. Apologies but this isn't something I can provide support on. This is a node-only package, why do you bundle it in the first place?

**Comment by MonoAnji** [comment]
It's running only in node (svelte-kit hook, thus server side only), i use it for some communication with keycloak. Maybe I mistook this issue for something it's not, just noticed that it's caused by requires in issuer.js, if that's a valid problem is something I don't know, could well be an issue in the new esbuild version.
Sorry that I bothered you with that. I shall not use the new esbuild for now.

**Comment by panva** [comment]
@MonoAnji you did not bother at all. I hope you can find the cause of your trouble eventually and come back with a hint for others towards what the problem was.

**Comment by MonoAnji** [comment]
The solution for using open-id-client with sveltekit seems to be to specify the module in the dependency section in package.json rather than in devDependencies. That might be obvious to other people, but I didn't know. I tried that but it caused other problems, which can be resolved by specifying jose (at this point in time 2.0.5) as a dependency too.

Cheers and thanks for the hind that it's a setup problem/ problem with bundling.
