### ISSUE TITLE
timeouts with 1.11.1

### ISSUE THREAD

**Issue by zackarychapple** [panva/node-openid-client#41]
When we moved to 1.11.1 we started experiencing timeouts with our openid client. 

We have two customizations.  One sets the clock tolerance, the other is setting the default timeout to 20 seconds. Is how we are setting the timeout incorrect with the new version? It worked with the old version. 

`Issuer.defaultHttpOptions = {timeout: 20000};`
`client.CLOCK_TOLERANCE = 5;`

**Comment by panva** [comment]
exactly what error `console.log(error)` are you getting?. I did update the major version of `got` but its timeout option remained unchanged, if anything it got fixed for more scenarios.

**Comment by ppvolto** [comment]
Tested aganst your node-oidc-provider-example with a local setup on a different mashine
when timeout less then 5100 then i get this:
```
RequestError: Request timed out
    at timeoutFn (<PROJECT>/server/node_modules/got/index.js:131:53)
    at asPromise (<PROJECT>/server/node_modules/got/index.js:134:9)
    at got (<PROJECT>/server/node_modules/got/index.js:386:10)
    at Function.got.(anonymous function) [as get] (<PROJECT>/server/node_modules/got/index.js:404:31)
    at Object.get (<PROJECT>/server/node_modules/openid-client/lib/http.js:14:14)
    at Function.discover (<PROJECT>/server/node_modules/openid-client/lib/issuer.js:191:28)
```
I hope it helps in a way...

**Comment by panva** [comment]
@ppvolto Getting a timeout error is intended if the request takes long. The timeout period is configurable (see docs), if this problem persists please post your `console.log('httpOptions %j', Issuer.defaultHttpOptions);` for me please.
@zackarychapple can you do the same?

**Comment by panva** [comment]
I just verified a timeout option works as intended. 

By introducing a delay in my OP responses i was able to get "RequestError: Request timed out" as intended and then, by setting `Issuer.defaultHttpOptions = { timeout }` to an appropriate value, i was getting to my OP responses again.

Closing for a) lack of feedback from the original poster, b) not able to reproduce.

**Comment by zackarychapple** [comment]
@panva apologies for taking so long to get back, was tied up with other issues.  I plan to try upgrading again next week.
