### ISSUE TITLE
Client is not a constructor. Erroneous typescript definition. Misleading docs.

### ISSUE THREAD

**Issue by PaulSzymanski** [panva/node-openid-client#416]
**Describe the bug**
The TS definition exposes the Client constructor. However, the Client constructor is only accessible on an Issuer instance.

Hence TS will not complain if you write `new Client(clientMetadata)`.

Also the [docs are misleading](https://github.com/panva/node-openid-client/tree/main/docs#new-clientmetadata-jwks-options).

**To Reproduce**
```ts
const client = new Client(recoveredClientMetadata)
```

**Expected behaviour**
Either TS complaining or the library directly exposing the constructor.

**Environment:**
 - openid-client version: v4.9.1
 - node version: v12

**Additional context**
This bug was probably causing confusion here as well: https://github.com/panva/node-openid-client/issues/213

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
I find nothing misleading about the docs, all examples show how to obtain the Client constructor. That the types are messed up is a pity, PR is welcome, they've been like this since their inclusion two years ago. Not a big deal IMHO since all the docs show the correct way of instantiating a Client.
