### ISSUE TITLE
Append client_id to session key in passport strategy

### ISSUE THREAD

**Issue by brianGammon** [panva/node-openid-client#42]
Hi, I'm hoping to use your library as-is without a fork, but I would like to append client_id to the session key in Passport Strategy. Something like this:
``const sessionKey = `oidc:${url.parse(issuer.issuer).hostname}:${client.client_id}`;``

Our node backend is shared by multiple apps at the moment. Even though they could all work with the same client_id, we want separate client_ids for each set up in the OP. I can create an instance of the strategy for each client, but presently they would all share the same session key since the issuer settings are the same. It's an edge case scenario, but adding client_id will ensure that it's picking up the right one if the user had 2 tabs going and somehow attempted to login at nearly the same time.

Would you consider a PR with this small change? If the whole thing is a bad idea, let me know that too :)

**Comment by panva** [comment]
a PR is welcome, it's pretty straight forward

constructor needs this to stay backwards compatible
```
this._key = options.sessionKey || `oidc:${url.parse(issuer.issuer).hostname}`;
```
and then authenticate just needs

```
const sessionKey = this._key;
```

**Comment by brianGammon** [comment]
Hi @panva, thanks for merging in my PR. It's working fine, but after using it, I wonder if the sessionKey belongs in the params sub-object on options. For example, this is how it is implemented after my change:
`new oidcStategy({ client: client, sessionKey: sessionKey, params: {scope: 'openid foo' }}`

But perhaps it should have been like this:
`new oidcStategy({ client: client, params: {sessionKey: sessionKey, scope: 'openid foo' }}`

I can resubmit if you prefer to keep options object the original 2 properties - client & params.

**Comment by panva** [comment]
`params` is intended for authorization parameters, sessionKey is right where it should be. Thanks for your contribution.
