### ISSUE TITLE
Typescript compilation fails: does not satisfy the constraint 

### ISSUE THREAD

**Issue by S0c5** [panva/node-openid-client#424]
**Describe the bug**
Wrong types for HttpOptions, in this case the `lookup` option should be removed to make it work, but the latest package doesnt compile

```
node_modules/openid-client/types/index.d.ts:15:5 - error TS2344: Type '"timeout" | "key" | "passphrase" | "lookup" | "headers" | "ca" | "cert" | "crl" | "pfx" | "agent"' does not satisfy the constraint '"rejectUnauthorized" | "servername" | keyof RequestOptions | keyof SecureContextOptions'.
  Type '"lookup"' is not assignable to type '"rejectUnauthorized" | "servername" | keyof RequestOptions | keyof SecureContextOptions'.
  ```

**To Reproduce**

Steps to reproduce the behaviour:

1.  try to compile the project with the latest typescript version 4.4.4

**Expected behaviour**

That the library compiles

**Environment:**
 - openid-client version: 5.0.2
 - node version: 13.14.0
 - typescript: 4.4.4

**Additional context**

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
The inclusion of lookup is very much intended. You just have to update your @types/node package.
