### ISSUE TITLE
Node 17.x support

### ISSUE THREAD

**Issue by r0und** [panva/node-openid-client#429]
**Describe the bug**
yarn install won't continue.

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
yarn install
...
error openid-client@5.0.2: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "17.0.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Steps to reproduce the behaviour:

1.  yarn install

**Expected behaviour**
No errors.

**Environment:**
 - openid-client version: [5.0.2]
 - node version: [17.0.1]

**Additional context**
No.

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
This is intended. Only LTS releases listed in engines are supported.

**Comment by r0und** [comment]
Understood, thank you!
