### ISSUE TITLE
Using within a create-react-app give a "classPrivateProperties isn't currently enabled" error

### ISSUE THREAD

**Issue by lecoqlibre** [panva/node-openid-client#431]
Hi, when I try to use this library within a new [Create React App](https://github.com/facebook/create-react-app) project I get the following error :

`/node_modules/openid-client/lib/client.js: Support for the experimental syntax 'classPrivateProperties' isn't currently enabled (163:3)`

It seems that you are publishing experimental features on npm.

Is that intentional? Please consider reading this issue: [Please don’t publish experimental syntax on npm](https://github.com/material-components/material-components-web-react/issues/107).

Thanks.

### How to reproduce this issue:
```
npx create-react-app my-app
cd my-app
yarn add openid-client
```

Add the following code into `src/App.js`:
```
import { Issuer } from 'openid-client';
const googleIssuer = Issuer.discover('https://accounts.google.com');
console.log('Discovered issuer %s %O', googleIssuer.issuer, googleIssuer.metadata);
```

Run `yarn start`

**Comment by panva** [comment]
There's nothing experimental and this is a Node.js only package.
