### ISSUE TITLE
NODE_EXTRA_CA_CERTS not honored

### ISSUE THREAD

**Issue by Morriz** [panva/node-openid-client#438]
**Describe the bug**

The `NODE_EXTRA_CA_CERTS` option seems not to be honored by openid-client. Other client libs (like `node-fetch`) work just fine with it but this one doesn't. Strangely, setting the agent's `ca:` with the same content also does nothing and still gives the `DEPTH_ZERO_SELF_SIGNED_CERT` error.

I hope this rings a bell and I don't have to present a repro setup, as that involves a running server. If needed I will go through those hoops but I am hoping to get a sane response first.

**Expected behaviour**
NODE_EXTRA_CA_CERTS to be used for requests

**Environment:**
 - openid-client version: 5.1.0
 - node version: 16.10

**Additional context**
 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
@Morriz there is nothing in the code that I am aware of that would prevent either `NODE_EXTRA_CA_CERTS` process.env or the `ca` option to work.

> I hope this rings a bell and I don't have to present a repro setup

It doesn't ring a bell and is very peculiar, please present a repro setup.

**Comment by Morriz** [comment]
It must be an upstream issue as I now see it in other libs as well. I am testing with `curl  --cacert` pointing to the extra CA file, which works fine, but pointing `NODE_EXTRA_CA_CERTS` to the same file does nothing.
