### ISSUE TITLE
Timeout 0 not accepted

### ISSUE THREAD

**Issue by soanaphikeste** [panva/node-openid-client#443]
**Describe the bug**
When setting the global timout to 0, it remains at the default value even though 0. This is normally an accepted value that would disable the timeout completely.

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
import { Issuer, custom } from 'openid-client';

custom.setHttpOptionsDefaults({
    timeout: 0
});

await Issuer.discover('https://some-url-to-extremely-slow-server.example.com')
```

Steps to reproduce the behaviour:
 
2. Set the global timeout option to 0
2.  Call an extremely slow server (e.g. using `Issuer.discover`)
3.  Observe that a timeout error is thrown with the message `RPError: outgoing request timed out after 3500ms`

**Expected behaviour**
There should not be a timout error or at least not one generated by openid-client. 3500ms is the default timeout imposed by this library, which leads me to believe that overriding the timeout did not have any effect

**Environment:**
 - openid-client version: 5.0.2
 - node version: 12.22.5

**Additional context**
The issue is most likely in the [`pick` function](https://github.com/panva/node-openid-client/blob/ff046ca2448d81e6b24a03f8e3bed967b7d632e3/lib/helpers/pick.js#L4), which checks for thruthy values whn selecting things.

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
If you change the pick function to `if (object[path] !== undefined) {`, do you observe the expected behaviour?

**Comment by soanaphikeste** [comment]
Yes, that produces the expected behavior
