### ISSUE TITLE
"The engine "node" is incompatible with this module"

### ISSUE THREAD

**Issue by lucasgonze** [panva/node-openid-client#452]
**Describe the bug**

`yarn run test` fails for Node 13, 15, 17

**To Reproduce**

Steps to reproduce the behaviour:

1.  git clone git@github.com:panva/node-openid-client.git && cd node-openid-client
2.  yarn run test
`*error openid-client@5.1.1: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "12.7.0"*`

**Expected behaviour**

node-openid-client should work in most production versions of Node.

**Environment:**

 - node version: the fail happens in any node version except "^12.19.0 || ^14.15.0 || ^16.13.0"

**Additional context**

openid-client uses node-jose which uses node-forge. node-forge has a deliberate policy of only supporting Node LTS releases; the inverse of this is throwing an error when invoked in non-LTS releases. Node [defines](https://nodejs.org/en/about/releases/) an LTS release  this way:

> After six months, odd-numbered releases (9, 11, etc.) become unsupported, and even-numbered releases (10, 12, etc.) move to Active LTS status and are ready for general use

**Comment by panva** [comment]
> openid-client uses node-jose which uses node-forge.

openid-client has not used node-jose for quite some time now. 

The engines entry is very much deliberate. 

> node-openid-client should work in most production versions of Node.

It works in all versions of node intended - active and maintenance lts releases, as made clear by the engines entry.
