### ISSUE TITLE
JWT not active yet, now 1642051718, nbf 1642051719: Id token Validation

### ISSUE THREAD

**Issue by sharmmoh1983** [panva/node-openid-client#454]
While trying to validate the id token in callback , we are getting following error
JWT not active yet, now 1642051718, nbf 1642051719

I think   In id_token IDP  round the nbf up, but  open id connect  round the time down
Can i add  add 1 sec to make it work consistantly...

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
// Issuer configuration (issuer.metadata) and how it is constructed (discovery or manual?)
import { Issuer } from 'openid-client';

const googleIssuer = await Issuer.discover('https://accounts.google.com');
console.log('Discovered issuer %s %O', googleIssuer.issuer, googleIssuer.metadata);
// Client configuration (client.metadata) and how it is constructed (fromUri or manual?)
const client = new googleIssuer.Client({
  client_id: '',
  redirect_uris: ['http://localhost:3000/cb'],
  response_types: ['id_token'],
  // id_token_signed_response_alg (default "RS256")
}); // => Client
```

Steps to reproduce the behaviour:

1. ```
 const client = new googleIssuer.Client({
  client_id: '',
  redirect_uris: ['http://localhost:3000/cb'],
  response_types: ['id_token'],
  // id_token_signed_response_alg (default "RS256")
}); // => Client
```
2.  ```
import { generators } from 'openid-client';
const nonce = generators.nonce();
// store the nonce in your framework's session mechanism, if it is a cookie based solution
// it should be httpOnly (not readable by javascript) and encrypted.
```

```
client.authorizationUrl({
  scope: 'openid email profile',
  response_mode: 'form_post',
  nonce,
});
```
3.  /```
/ assumes req.body is populated from your web framework's body parser
const params = client.callbackParams(req);
const tokenSet = await client.callback('https://client.example.com/callback', params, { nonce });
console.log('received and validated tokens %j', tokenSet);
console.log('validated ID Token claims %j', tokenSet.claims());
```

**Expected behaviour**
Id token getting validated successfully.

**Environment:**
 - openid-client version:^5.1.1
 - node version: v12

**Comment by panva** [comment]
https://github.com/panva/node-openid-client/blob/main/docs/README.md#customizing-clock-skew-tolerance

Please refer to documentation and existing issues/discussions before opening an issue.

**Comment by sharmmoh1983** [comment]
Thanks for the response .. Documentation was not clear enough to correlate the issue
