### ISSUE TITLE
Include node 17 as supported engine

### ISSUE THREAD

**Issue by Yasamato** [panva/node-openid-client#470]
Bump supported engine versions for [node 17](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V17.md).
https://github.com/panva/node-openid-client/blob/444e770563a36e6efc82cbee5889973f2db4f86e/package.json#L74

**Comment by panva** [comment]
#452 #447 #429

**Comment by Yasamato** [comment]
Oh haven't read that part:
> This is intended. Only LTS releases listed in engines are supported.

my bad :)
