### ISSUE TITLE
Module not found: Can't resolve 'v8'

### ISSUE THREAD

**Issue by developdeez** [panva/node-openid-client#475]
I keep getting an error (Module not found: Can't resolve 'v8') when I use the Issuer. Seems to happen even if I use the google issuer and I recently updated my node to see if its a version issue. Same error.

openid-client 5.1.3
in NextJS

`const { Issuer, Strategy } = require('openid-client');
class OidcConnector extends Connector {
  constructor(settings) {
    super('oidc', {
      issuer: settings.issuer,
      clientId: settings.clientId,
      clientSecret: settings.clientSecret,
      publicKey: settings.publicKey,
      redirectUri: settings.redirectUri,
      sessionSecret: settings.sessionSecret || 'Secret',
      selectProfileData: settings.selectProfileData,
      findOrCreateProfile: settings.findOrCreateProfile
    });
  }

  async initialize() {
    this.issuer = new Issuer({
      issuer: 'https://accounts.google.com',
    });

    const client = new this.issuer.Client({
      clientId: 'cid',
      clientSecret: 'csec',
      redirect_uri: 'localhost:3000'
    });

}

module.exports = OidcConnector;

`

**Comment by panva** [comment]
This is a Node.js runtime only library.

cc @balazsorban44 who can point you in the right direction.

**Comment by balazsorban44** [comment]
@developdeez as said above, you are likely using this library in a non-Node.js environment, something like Cloudflare Workers maybe?
