### ISSUE TITLE
Storage of discovered public keys etc. in a database

### ISSUE THREAD

**Issue by mansonitefirefox** [panva/node-openid-client#48]
I was wondering if it was possible to be able to perform the issuer discovery and then have the details that come back stored in a database. I cant see any kind of documentation or config that would allow this.

If possible it would allow a convenient means of using this package in an AWS Lambda without having to make an external call out to the secure token service for each new request. A timeout feature like forcing a new discovery every 5 minutes or so would be excellent.

Thanks a lot.

**Comment by mansonitefirefox** [comment]
If the package doesn't have this capability, would you consider a PR for it?

**Comment by panva** [comment]
What does the `etc.` in the title stand for, as far as i can see there's nothing else to cache, is there? As far as lambda goes you can just keep your discovered issuer in memory, lambda is not doing a cold start on every call, this is definitely better than going to a DB and instantiating an Issuer and a Client every single time. But I don't see the need for a DB connection from openid-client.

**Comment by mansonitefirefox** [comment]
> What does the etc. in the title stand for
Public keys

However, I wasn't aware that the lambda wasn't doing a cold start on every call. I guess I will investigate further.

Thanks.
