### ISSUE TITLE
Node 17 support

### ISSUE THREAD

**Issue by JalilArfaoui** [panva/node-openid-client#484]
Is it possible to support Node 17 ?

Currently, it refuses to install (package.json specifies `"node": "^12.19.0 || ^14.15.0 || ^16.13.0"`)

**Comment by panva** [comment]
As per https://github.com/panva/node-openid-client#install

> Node.js LTS releases Codename Erbium (starting with ^12.19.0) and newer LTS releases are supported. This means ^12.19.0 (Erbium), ^14.15.0 (Fermium), and ^16.13.0 (Gallium). Future LTS releases will be added to this list as they're released.

The next to be added will be LTS 18 (Codename Hydrogen) in October 2022 as per the [release schedule](https://github.com/nodejs/release).

**Comment by JalilArfaoui** [comment]
Sorry, I did not see this mention …
