### ISSUE TITLE
requestResource return type

### ISSUE THREAD

**Issue by coffe0wl** [panva/node-openid-client#488]
The documentation(Image1) states that the **requestResource** method returns the promise but in reality it doesn't(Image2)

### Image1
![image](https://user-images.githubusercontent.com/52937225/163621656-d931bce2-f7ab-42fa-90bc-97a47f2c7b27.png)

### Image2
![image](https://user-images.githubusercontent.com/52937225/163621749-361ac180-617a-45f1-a22e-53be607589c2.png)

**Comment by panva** [comment]
It sure [does](https://github.com/panva/node-openid-client/blob/v5.1.5/lib/client.js#L1119) return a Promise, it's an async function.

**Comment by coffe0wl** [comment]
> 

Yes, but not in the [index.d.ts](https://github.com/panva/node-openid-client/blob/e25eb16b37028be4517d0b14e0b6a38582770f39/types/index.d.ts#L352) file
![image](https://user-images.githubusercontent.com/52937225/163678522-b8fa0790-dc06-468b-bbbe-0f8b6bf51e70.png)

**Comment by panva** [comment]
> The documentation states that the requestResource method returns the promise but in reality it doesn't. 

That is what I checked.

Would you like to submit a PR to fix the types?
