### ISSUE TITLE
Node.js 18 support?

### ISSUE THREAD

**Issue by Apollon77** [panva/node-openid-client#494]
With Node.js 18 spreading and becoming LTS in some months, is there any timeframe to support it?

**Comment by panva** [comment]
In some months when it enters LTS. As per the readme and countless similar questions/discussions.

**Comment by loopingz** [comment]
@Apollon77 someone did create this in the mean time: https://www.npmjs.com/package/openid-client-any-engine
@panva Node18 is current, why do you wait for it to be in LTS mode to add it? I understand the reasons for the odd versions as they won't ever be LTS but on even ones I think it is better to prepare in advance for anyone depending on your package

**Comment by panva** [comment]
> to prepare in advance for anyone depending on your package

I've seen time and time again that new majors take a while to stabilize, this has been the case with 15, 16, 17 and now also 18. I believe it is up to me to choose which engines I wish to support and using an advisory field for sending that message across is okay.

npm's handling of `engines` is advisory and will only produce warnings when this package is installed as a dependency on an unsupported engine (unless the engine-strict config flag is set). `yarn` has an `--ignore-engines` flag for having it follow the same behaviour.

So I'd say you want to be on the edge, you can. It's only a matter of tooling.

**Comment by Apollon77** [comment]
@panva For the project I woórk on we use the strict mode in npm to prevent issues for the users .. that means that the engines property is used 100% and so I can not offer my software to users that are already on Node.js 18 because it would fail to install for them.

As said above I completely agree fr it with odd numbers because these are dev versions and yes alsothe even numbers could slightly change before the become LTS, but normally not in a breaking mannor.

But also ... Sure we respect your opinion ...

**Comment by panva** [comment]
> For the project I woórk on we use the strict mode in npm to prevent issues for the users

But that's exactly the point of my use of the engines and LTS-only policy. Even "even" numbered releases tend to be buggy and take a while to stabilize. For instance v18 shipped with a breaking change that caused ripples in the ecosystem's http server handling and took a few minors to resolve and roll back.

And it's not like this policy should come as a surprise, it is right there in the readme for both direct dependents to acknowledge and accept or for library developers to accept and propagate to their own libraries.

**Comment by lchrennew** [comment]
> > For the project I woórk on we use the strict mode in npm to prevent issues for the users
> 
> But that's exactly the point of my use of the engines and LTS-only policy. Even "even" numbered releases tend to be buggy and take a while to stabilize. For instance v18 shipped with a breaking change that caused ripples in the ecosystem's http server handling and took a few minors to resolve and roll back. It doesn't matter if the major is odd or even in this regard, they're equally as affected by breaking changes and instability in their first months.
> 
> And it's not like this policy should come as a surprise, it is right there in the readme for both direct dependents to acknowledge and accept or for library developers to accept and propagate to their own libraries.

So supply-side point...Seems everyone cannot run `"@kubernetes/client-node": "^0.17.1"` under node v18.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/1522365/190866644-59d0616e-9374-4060-924c-2480a08e4eb6.png">

https://github.com/kubernetes-client/javascript/issues/832
https://github.com/kubernetes-client/javascript/issues/878

**Comment by loopingz** [comment]
I think the author made his point. We just need the kubernetes team to release the fix they made
