### ISSUE TITLE
 client must be an instance of openid-client Client

### ISSUE THREAD

**Issue by corinz** [panva/node-openid-client#515]
**Describe the bug**
Error says wrong type is passed, but type is confirmed.

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
 createClient(obj){
    const { Issuer, Strategy } = require('openid-client');
    Issuer.discover(this.OIDC_PROVIDER_URL).then(
        function(oidcIssuer) {
        const oidcClient = new oidcIssuer.Client({
          client_id: obj.clientId,
          client_secret: 'NONE',
          redirect_uris: [obj.REDIRECT_URI],
          response_types: ['code'],
        });

        obj.passport.use('openid-client',
          new Strategy({ oidcClient, passReqToCallback: true }, (req, tokenSet, userinfo, done) => {
            if (this.DEBUG) console.log("tokenSet", tokenSet);
            if (this.DEBUG) console.log("userinfo", userinfo);
            req.session.tokenSet = tokenSet;  
            req.session.userinfo = userinfo;
            return done(null, tokenSet.claims());
          }));
        })
    }
```

Steps to reproduce the behaviour:

1.  Create an class with a constructor that calls the method above
2.  Execute
3.  

**Expected behaviour**
Strategy created without issues/errors

**Environment:**
 - openid-client version: 5.18
 - node version: v16.13

**Additional context**

 - [ ] the bug is happening on latest openid-client too.
 - [X] i have searched the issues tracker on github for similar issues and they didnt help.

Thank you!

**Comment by panva** [comment]
Please see the docs. https://github.com/panva/node-openid-client/blob/v5.x/docs/README.md#strategy
