### ISSUE TITLE
Can we expect an upgrade to 18.7 in the near future?

### ISSUE THREAD

**Issue by saschati** [panva/node-openid-client#517]
**Describe the bug**
At the moment, I'm getting blocked when installing the package because I'm using the 18.7 version of node:
```
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error openid-client@5.1.8: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "18.7.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
Is there a package update planned for node 18.7?

**Environment:**
 - openid-client@5.1.8
 - node 18.7.0

**Comment by panva** [comment]
Yes, when 18 enters active LTS as per the policy in the readme section.

**Comment by crudo** [comment]
@panva v18 is LTS already. Any news about adding support?

**Comment by panva** [comment]
I've removed the engines restriction what feels like ages ago.
