### ISSUE TITLE
Include client_id and client_secret in token request body

### ISSUE THREAD

**Issue by andystevensname** [panva/node-openid-client#52]
Is there a way to setup the token request to include the client_id and client_secret? I'm looking to use this with Twitch, which requires these items in the body for both authorization and the token request.

**Comment by panva** [comment]
set your client's `token_endpoint_auth_method` to `"client_secret_post"` - as per spec... http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication

**Comment by andystevensname** [comment]
Thank you
