### ISSUE TITLE
upgrading package openid-client from 4.7.4 to 5.1.8 getting ‘unable to get local issuer certificate’ 

### ISSUE THREAD

**Issue by piyushSinghalDemo** [panva/node-openid-client#527]
**Describe the bug**

 I am trying upgrade  openid-client from 4.7.4 to 5.1.8 and oidc-provider from 6.31.0 to 7.11.5 . In initial call when i do issuer configuration call it throows error  ‘**unable to get local issuer certificate**’. In our nestjs application we were doing below cerficate configuration 

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
const { Issuer, generators, custom } = require('openid-client');
async onModuleInit() {
	let options: any = {
            rejectUnauthorized: false,
        }
        options.ca = fs.readFileSync(CA_PATH);
      custom.setHttpOptionsDefaults(options);
}
```js
// Issuer configuration (issuer.metadata) and how it is constructed (discovery or manual?)
{
  // ...
}
// Client configuration (client.metadata) and how it is constructed (fromUri or manual?)
{
  // ...
}
```

Steps to reproduce the behaviour:

1.  
2.  
3.  

**Expected behaviour**
Previous certification configuration may be working in new version also 

**Environment:**
 - openid-client version: 5.1.8 
 - node version: :16-alpine3.16

**Additional context**

 - [ ] the bug is happening on latest openid-client too.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Please open a more complete, comprehensive report. 

It's unlikely this is a bug so a Q&A discussion is more appropriate. 

For you to get help you must provide easy and clear steps to reproduce your issue.
