### ISSUE TITLE
urn:ietf:params:oauth:grant-type:jwt-bearer support?

### ISSUE THREAD

**Issue by jmendiara** [panva/node-openid-client#54]
Nice work!

I'm wondering if you are planning to add support for `grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer` and/or if you will accept some contributions

Tnx

**Comment by panva** [comment]
Hi @jmendiara 

I do not plan to add support for this myself, that being said i will support/accept contributions so long as it 
follows the styleguide, includes test coverage for added code and functions on `node >= 4`.

**Comment by jmendiara** [comment]
Nice, thanks! I'll try on my spare time ;)

**Comment by brownbl1** [comment]
@jmendiara Did you try the following?
```js
client.grant({
  grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',
  ...
})
```

This worked for my use case (uses basic auth and sends the passed object as the body to your token endpoint.
