### ISSUE TITLE
bug(ts): statics missing on TypeOfGenericClient

### ISSUE THREAD

**Issue by flashtheman** [panva/node-openid-client#540]
I'm following an example I found and where it should be possible to call Client.register. See below.

```
const issuer = await Issuer.discover(baseURL);

const issuer = await issuer.Client.register({
     redirect_uris,
 });
```

However, the register method seems not to be implemented, and therefore typescript shows the following error:

> Property 'register' does not exist on type 'TypeOfGenericClient<BaseClient>'.ts(2339)

I would expect the register method to exist and not throw an error.

**Environment:**
 - openid-client version: v5.2.1
 - node version:  v19.0.1
 - typescript: v4.8.4

**Comment by panva** [comment]
I see no runtime issue, the method is there, it's type definition issue. Feel free to submit a PR fixing this. I suspect all static getters/setters and methods will be missing on `TypeOfGenericClient`.

**Comment by panva** [comment]
Completely unrelated. Maybe your IdP does not support dynamic client registration and you ought to just be instantiating a client like so, `new issuer.Client(metadata)` using metadata given to you.
