### ISSUE TITLE
`isPlainObject` returning `false` when running inside Jest

### ISSUE THREAD

**Issue by maxdeviant** [panva/node-openid-client#545]
**Describe the bug**

`isPlainObject` returns `false` for JWKs when running inside Jest:

```
/Users/maxdeviant/projects/node-openid-client-is-plain-object-repro/node_modules/openid-client/lib/client.js:99
    throw new TypeError('jwks must be a JSON Web Key Set formatted object');
          ^

TypeError: jwks must be a JSON Web Key Set formatted object
    at Client.getKeystore (/Users/maxdeviant/projects/node-openid-client-is-plain-object-repro/node_modules/openid-client/lib/client.js:99:11)
    at new BaseClient (/Users/maxdeviant/projects/node-openid-client-is-plain-object-repro/node_modules/openid-client/lib/client.js:233:36)
    at new Client (/Users/maxdeviant/projects/node-openid-client-is-plain-object-repro/node_modules/openid-client/lib/client.js:1742:7)
    at buildClient (/Users/maxdeviant/projects/node-openid-client-is-plain-object-repro/src/index.ts:38:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

The failure happens here when checking whether the entries of `jwks` is a plain object:

https://github.com/panva/node-openid-client/blob/a571a7200b139281ea411a31c7b08faa907cf34f/lib/client.js#L97

Specifically, the issue seems to be with the `a.constructor === Object` check in `isPlainObject`:

https://github.com/panva/node-openid-client/blob/a571a7200b139281ea411a31c7b08faa907cf34f/lib/helpers/is_plain_object.js#L1

**To Reproduce**

I put together a repo with a reproduction case: https://github.com/maxdeviant/node-openid-client-is-plain-object-repro

Steps to reproduce the behaviour:

1. Pull down the reproduction repo linked above
2. Run `yarn test:jest` to see the failing test case

If you run `yarn test:mocha` in the same repo you can see that the same test case does not fail when not running under Jest.

**Expected behaviour**

I would expect the behavior to be the same under Jest as it is for other testing frameworks.

**Environment:**
 - openid-client version: v5.0.2
 - node version: v16.18.1

**Additional context**

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Hi @maxdeviant 

> I would expect the behavior to be the same under Jest as it is for other testing frameworks.

I would too, but that is Jest's issue. One of many. https://backend.cafe/should-you-use-jest-as-a-testing-library

Setting up Jest properly definitely helps.

```
diff --git a/jest.config.js b/jest.config.js
index 40040d7..9f56d3f 100644
--- a/jest.config.js
+++ b/jest.config.js
@@ -4,7 +4,7 @@ module.exports = {
   resetMocks: true,
   restoreMocks: true,
   roots: ['<rootDir>/src'],
-  testEnvironment: 'node',
+  testEnvironment: 'jest-environment-node-single-context',
   testRegex: '.jest.test.ts$',
   transform: { '^.+\\.ts$': ['ts-jest', { isolatedModules: true }] },
 };
diff --git a/package.json b/package.json
index 09150aa..13614fd 100644
--- a/package.json
+++ b/package.json
@@ -21,6 +21,7 @@
     "@types/node-forge": "0.10.10",
     "chai": "4.3.7",
     "jest": "29.3.1",
+    "jest-environment-node-single-context": "^29.0.0",
     "mocha": "10.1.0",
     "nock": "13.2.9",
     "ts-jest": "29.0.3",
```

<img width="621" alt="image" src="https://user-images.githubusercontent.com/241506/203644563-4e5f1889-4d89-4ecf-a1c9-8ea031d3afd7.png">
