### ISSUE TITLE
Discovered token_endpoint_auth_methods_supported not used by client

### ISSUE THREAD

**Issue by helleroy** [panva/node-openid-client#57]
It seems the `Client` never uses the discovered `token_endpoint_auth_methods_supported` from the `Issuer` but instead always defaults to using `client_secret_basic`.

I know that this can be overwritten by setting `token_endpoint_auth_method` on the `Client` but it's confusing that it's unable to select a supported method by itself, considering that the `Issuer` has the information. It also appears to break with the intended behaviour described in the spec:

> token_endpoint_auth_methods_supported
OPTIONAL. JSON array containing a list of Client Authentication methods supported by this Token Endpoint. The options are client_secret_post, client_secret_basic, client_secret_jwt, and private_key_jwt, as described in Section 9 of OpenID Connect Core 1.0 [OpenID.Core]. Other authentication methods MAY be defined by extensions. If omitted, the default is client_secret_basic -- the HTTP Basic Authentication Scheme specified in Section 2.3.1 of OAuth 2.0 [RFC6749].

http://openid.net/specs/openid-connect-discovery-1_0.html

Here's the discovered metadata for my `Issuer` and `Client`

Issuer metadata
```javascript 
{
  claims_parameter_supported: false,
  grant_types_supported: ['authorization_code', 'implicit'],
  request_parameter_supported: false,
  request_uri_parameter_supported: true,
  require_request_uri_registration: false,
  response_modes_supported: ['query', 'fragment'],

  token_endpoint_auth_methods_supported: ['client_secret_post'],

  issuer: 'https://api.some-host.com',
  authorization_endpoint: 'https://api.some-host.com/oauth/authorize',
  token_endpoint: 'https://api.some-host.com/oauth/token',
  token_endpoint_auth_signing_alg_values_supported: ['RS256'],
  userinfo_endpoint: 'https://api.some-host.com/oauth/userinfo',
  jwks_uri: 'https://api.some-host.com/oauth/jwks.json',
  response_types_supported: ['code'],
  introspection_endpoint: undefined,
  introspection_endpoint_auth_methods_supported: ['client_secret_post'],
  introspection_endpoint_auth_signing_alg_values_supported: ['RS256'],
  revocation_endpoint: undefined,
  revocation_endpoint_auth_methods_supported: ['client_secret_post'],
  revocation_endpoint_auth_signing_alg_values_supported: ['RS256'],
}
```
Client metadata
```javascript
{
  application_type: 'web',
  grant_types: ['authorization_code'],
  id_token_signed_response_alg: 'RS256',
  response_types: ['code'],

  token_endpoint_auth_method: 'client_secret_basic',

  client_id: '6462923d-8061-46ab-8136-103a1a2a36e8',
  client_secret: 'f624a3fd-d5aa-4300-bc60-6f2a3eced8e1',
  introspection_endpoint_auth_method: 'client_secret_basic',
  introspection_endpoint_auth_signing_alg: undefined,
  revocation_endpoint_auth_method: 'client_secret_basic',
  revocation_endpoint_auth_signing_alg: undefined,
}
```

**Comment by helleroy** [comment]
Having it default to `client_secret_basic` is fine, my issue is that it never uses anything else unless specified when instantiating a `Client`. If the `.well-known/openid-configuration`-endpoint responds with another auth method, I propose that it should be used instead of the default (which in my case is not supported).

In the case where `.well-known/openid-configuration` responds with more than one supported auth method it could either default to the first method in the list, or prompt the user to specify a method - e.g. through an error message or similar.

In my specific case: just having it automatically use `client_secret_post` when that's specifically the only supported auth method would work.

**Comment by panva** [comment]
> In the case where .well-known/openid-configuration responds with more than one supported auth method it could either default to the first method in the list, or prompt the user to specify a method - e.g. through an error message or similar.

I have an issue with both of these proposals, throwing an error is a breaking change, one that i'm not going to introduce. Using the first one from the list also doesn't sound right as the first one might as well be `private_key_jwt` or `none`.

I can see prioritizing `client_secret_post` over `client_secret_basic` if the latter is not indicated as supported, but that's where i draw the line. A developer connecting to an OP only supporting `none` or `*_jwt` will likely know to set the properties of its client instances.
