### ISSUE TITLE
Device flow with GitHub does not continue to poll

### ISSUE THREAD

**Issue by jasonjoh** [panva/node-openid-client#575]
**Describe the bug**
The `poll` method returns after 5 seconds with an error object when it receives `authorization_pending`. The documentation states that `poll` will not resolve until a token is recevied.

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.

```typescript
const issuer = new Issuer({
  issuer: 'github.com',
  device_authorization_endpoint: 'https://github.com/login/device/code',
  token_endpoint: 'https://github.com/login/oauth/access_token',
});

const client = new issuer.Client({
  client_id: 'CLIENT_ID',
  token_endpoint_auth_method: 'none',
});

const handle = await client.deviceAuthorization({
  scope: 'user repo',
});
console.log('User Code: ', handle.user_code);
console.log('Verification URI: ', handle.verification_uri);

const tokenSet = await handle.poll();
console.log(typeof tokenSet);
console.log('received tokens %j', tokenSet);
```

Steps to reproduce the behaviour:

1. Register an OAuth app with GitHub, enable device flow. ([Docs](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app))
2. Replace `CLIENT_ID` with your app's client ID.
3. Run the above code.

**OUTPUT**

```bash
User Code:  BCE3-88D0
Verification URI:  https://github.com/login/device
object
received tokens {"error":"authorization_pending","error_description":"The authorization request is still pending.","error_uri":"https://docs.github.com/developers/apps/authorizing-oauth-apps#error-codes-for-the-device-flow"}'
```

**Expected behaviour**
`handle.poll()` should wait for user to go to the verification URL and enter the code.

**Environment:**
 - openid-client version: 5.4.0
 - node version: 18.14.0

**Additional context**

 - [x] the bug is happening on latest openid-client too.
 - [x] I have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Hi @jasonjoh,

The client imo behaves as expected. GitHub is returning a 200 OK instead of a 4xx status code. A 200 OK from the token endpoint means success.

**Comment by jasonjoh** [comment]
Ah, I didn't notice that! I guess they're not fully compliant with the RFC. However, I would respectfully disagree that this is expected behavior. A success status code that has none of the expected parameters in the body should at least result in an error. Wrapping the `poll` call in `try/catch` doesn't help since no error is thrown. Instead, a `TokenSet` is returned with properties that aren't present on its type definition.

I'm working around it by doing this:

```typescript
let waitingForAuth = true;
do {
  const tokenSet = await handle.poll();
  if ('error' in tokenSet) {
    if (tokenSet['error'] !== 'authorization_pending') {
      console.log(`Error: ${tokenSet['error']}`);
      waitingForAuth = false;
    }
  } else {
    console.log('received tokens %j', tokenSet);
    waitingForAuth = false;
  }
} while (waitingForAuth);
```

**Comment by panva** [comment]
That's a good workaround. I would suggest to reach out to GitHub for them to fix their issue though.
