### ISSUE TITLE
Editing Issuer iss values

### ISSUE THREAD

**Issue by jorgenkg** [panva/node-openid-client#58]
I'm using this excellent library to connect to `https://login.microsoftonline.com/common/oauth2/authorize`

Unfortunately, Microsoft uses a somewhat proprietary take on their `.well-known/openid-configuration` template.

```
{
  "issuer": "https://sts.windows.net/{tenantid}/" // the issue
  ...
}
```

They are specifying a template where they expect the client to replace the tag `{tenantId}` with an arbitrary value. I am *not* looking for template support in node-openid-client.

I'm trying to find a way to hack / set the `iss` value of an `Issuer()` instance. However, it seems that the value cannot be changed without refactoring the code. Is this correct, or have I overlooked a possibility?

**Comment by panva** [comment]
I think the following should work

1) discover an instance
2) use the `instance.metadata` getter to get the current discovery values as an object
3) modify the values
4) use `new Issuer(metadata);`

Not sure how ID Token validation will go since iirc the ID Tokens also have some surprises in them.

**Comment by panva** [comment]
And, not being able to confirm myself, i got this off a discussion somewhere, you should also be able to discover using your `{tenantid}` directly like so `https://login.microsoftonline.com/{tenantid}/.well-known/openid-configuration`

**Comment by jorgenkg** [comment]
Thanks for the quick response. I tried the first suggestion, which worked like a charm:

```
Issuer
    .discover( microsoftWellKnownUrl )
    .then((issuer) => {
      issuer.metadata.issuer = `https://sts.windows.net/#my-tenant-id/`; // this worked

      const scope             = "openid profile";
      const client            = new issuer.Client({
        client_id     : config.clientId,
        client_secret : config.clientSecret,
        token_endpoint_auth_method: "client_secret_post"
      }); 
```

Regarding your second suggestion I'm logging into the *common endpoint* of microsoftonline, thus I cannot use that specific endpoint.

**Comment by panva** [comment]
I thought it returns a copy of the object, oh well. I guess this works too :)
