### ISSUE TITLE
RequestError: Request timed out in authorizationCallback

### ISSUE THREAD

**Issue by sepehr1313** [panva/node-openid-client#61]
Hello Panava,
I'm trying to use openid-client in es5.
after I create my url I want to use authorizationCallback promise but it goes in catch and I get timed out error.
```
var clientQuery = client.callbackParams(query);
client.authorizationCallback('http://example.com/cb', clientQuery, {state: state})
        .then(function (tokenSet) {
            console.log('received and validated tokens %j', tokenSet);
            console.log('validated id_token claims %j', tokenSet.claims);
        })
        .catch(function (e) {
            logger.writeLog(e);
        });
```

**Comment by panva** [comment]
Try increasing the [default http client](https://github.com/panva/node-openid-client#changing-http-request-defaults) values such as request timeout. If the problem persists i suggest to check the request is actually getting through your network.
