### ISSUE TITLE
URL is not a constructor at Issuer.request

### ISSUE THREAD

**Issue by techyvenki** [panva/node-openid-client#659]
**Describe the bug**

Try to integrate azure pkce app into react application.

when trying to create issuer

const Issuer = await Issuer.discover(‘https://url’)

 it is giving error:

URL is not a constructor at Issuer.request

In request.js in your plugin I see

const {URL} = require(‘url’)

I see this is causing the issue when I make the above line changed to

const {Url} = required(‘url’) 

I see it is not complying in a different page of my code
 

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```js
// Issuer configuration (issuer.metadata) and how it is constructed (discovery or manual?)
{
  // ...
}
// Client configuration (client.metadata) and how it is constructed (fromUri or manual?)
{
  // ...
}
```

Steps to reproduce the behaviour:

1.  
2.  
3.  

**Expected behaviour**

**Environment:**
 - openid-client version: [e.g. v3.14.0] - 5.6.4
 - node version: [e.g. v8.9.0] - 8.19.2

**Additional context**

 - [ ] the bug is happening on latest openid-client too.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
> react application

This is a Node.js only module.
