### ISSUE TITLE
Support other status code than 200

### ISSUE THREAD

**Issue by DESOOMERPierre** [panva/node-openid-client#666]
**Describe the bug**
Hey there,

I am facing an issue where the provider ( CrowdStrike ) I am trying to connect to returns a status code 201 when requesting the authorization token. The problem is that `processResponse` always expects a status code 200 and therefore, throws an error. Is there a workaround already implemented?

**To Reproduce**
Issuer and Client configuration: (inline or gist) - Don't forget to redact your secrets.
```ts
public constructor({ tokenEndpoint, clientId, clientSecret, clientAuthentication }: Args) {
    const issuer = new Issuer({
      issuer: "generic_issuer",
      token_endpoint: tokenEndpoint,
      token_endpoint_auth_methods_supported: ["client_secret_basic", "client_secret_post"],
    })
    this.client = new issuer.Client({
      client_id: clientId,
      client_secret: clientSecret,
      token_endpoint_auth_method: clientAuthentication,
    })
  }
```

<img width="1181" alt="image" src="https://github.com/panva/node-openid-client/assets/91847463/a5830607-0429-45c6-95e3-b81bdf17101f">

Steps to reproduce the behaviour:

1.  Using client-credentials and request a crowdstrike endpoint

**Expected behaviour**
The best option I can propose so far is having the possibility to override the expected code by the processResponse function

**Environment:**
 - openid-client version: [5.4.2]
 - node version: [18.0.4]

 - [x] the bug is happening on latest openid-client too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Since [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-5.1) says it should be 200 I believe this should be solved with your provider, not downstream in client packages.

**Comment by panva** [comment]
> Is there any option with node-oidc-client we can consider to override the 201 response

Not that I'm aware of. This is an IdP issue that should be solved by your provider. I won't extend and maintain an API surface so that providers can play loose with the standards.

**Comment by panva** [comment]
FWIW with https://github.com/panva/oauth4webapi you could instantiate a response with all of its properties and changed http status code before passing it to the appropriate handler.

It's a lower level API module and definitely not for everyone.
