### ISSUE TITLE
thrown error not handled (missing implementation)

### ISSUE THREAD

**Issue by pashva** [panva/node-openid-client#678]
**Describe the bug**

In client.js when we call the refresh function, it internally calls the grant function. There are possibilities when grant function will throw an error. In our refresh function this thrown error is never handled.
![image](https://github.com/panva/node-openid-client/assets/61597430/3ea15435-4f3d-44eb-bb62-0860dadc7df9)
Isn't a try catch needed around this block?
Steps to reproduce the behaviour:

1.  Issue a token 
2.  Revoke the token
3.  Try to refresh the token

**Expected behaviour**
In such cases, the error should be handled gracefully.
**Environment:**
 - openid-client version: [e.g. v5.6.5]

**Additional context**

 - [ ] the bug is happening on latest openid-client too.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
What would need to be handled? The error from grant is propagated to you. That's intended. If you wish to ignore errors try/catch around your calls to refresh.

**Comment by pashva** [comment]
The error is thrown from "grant" to "refresh", but refresh has to throw is back right?

**Comment by pashva** [comment]
Sorry, wrong implementation from my side
Thanks for the support!
