### ISSUE TITLE
update interface AuthenticateOptions to include redirect_uri

### ISSUE THREAD

**Issue by huineng** [panva/node-openid-client#679]
"openid-client": "^5.6.5",

Hi , I'm referring to this discussion

https://github.com/panva/node-openid-client/pull/132#issuecomment-432792388

especially where you use 

```
app.use('/init', (req, res, next) => {
    // figure out which redirect_uri to use and use it on the fly
    const redirect_uri = 'http://lvh.me:3000/oidc/cb';
    passport.authenticate('oidc', { redirect_uri })(req, res, next);
  });
```

nevertheless redirect_uri  is not available on the AuthenticateOptions interface
![image](https://github.com/panva/node-openid-client/assets/3482445/8119b799-b7b0-4ce7-97d8-909741330ca3)

can it be added ?

thanks

**Comment by panva** [comment]
Hi @huineng 

AuthenticateOptions interface is not from openid-client, it's from passport.
