### ISSUE TITLE
Localhost request errors (RequestError: connect ECONNREFUSED 127.0.0.1:3000)

### ISSUE THREAD

**Issue by s2t2** [panva/node-openid-client#68]
Hi, thank you for this package! I'm hoping you might be able to provide guidance on an error I'm seeing when I use it to authenticate against a locally-running identity provider (rails app running on `localhost:3000`). 

I notice when I start my node app, this package attempts to make various authentication requests to `127.0.0.1:3000` URLs, but these requests aren't able to find the identity provider server. The requests produce `RequestError: connect ECONNREFUSED 127.0.0.1:3000` errors (logs below):

```
--->> DEBUG=my-identity-sp:* npm start

> my-identity-sp@0.0.0 start /Users/username/projects/my-identity-sp
> nodemon ./bin/www

[nodemon] 1.14.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./bin/www`
CONFIGURATION ERROR { RequestError: connect ECONNREFUSED 127.0.0.1:3000
    at ClientRequest.req.once.err (/Users/username/projects/my-identity-sp/node_modules/openid-client/node_modules/got/index.js:219:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'RequestError',
  code: 'ECONNREFUSED',
  host: 'localhost:3000',
  hostname: 'localhost',
  method: 'GET',
  path: '/.well-known/openid-configuration',
  protocol: 'http:',
  url: 'http://localhost:3000/.well-known/openid-configuration' }
```

It makes sense that requests to `127.0.0.1:3000` produce errors, but I'm wondering why requests are being made to `127.0.0.1:3000` instead of `localhost:3000`.

When I visit `http://localhost:3000/.well-known/openid-configuration` in a browser, I get the expected response. Here is an abbreviated snippet from the identity provider's well-known config file:

```js
{
        ...
	"authorization_endpoint": "http://localhost:3000/openid_connect/authorize",
	"issuer": "http://localhost:3000/",
	"jwks_uri": "http://localhost:3000/api/openid_connect/certs",
	"token_endpoint": "http://localhost:3000/api/openid_connect/token",
	"userinfo_endpoint": "http://localhost:3000/api/openid_connect/userinfo",
	"end_session_endpoint": "http://localhost:3000/openid_connect/logout",
	...
}
```

Note: when I try manual discovery using hard-coded well-known config values, configuration works, but subsequent requests produce the same client error.

I've found a temporary work-around for this issue, running the identity provider using the following command: `rails s -b 0.0.0.0`, but it ends up producing other issues pertaining to how the identity provider runs, so I was hoping to learn more about the client request errors and how I might fix them.

Do you have any ideas on where the disconnect is? Thank you for your time.

**Comment by panva** [comment]
The RequestError you show is using host localhost:3000 which just resolves to 127.0.0.1. I'm afraid this has 0 to do with the client, since it just takes whatever input values you give it and runs with those. No transformations or resolving is happening within the client.

**Comment by panva** [comment]
The difference between your browser and openid-client doing the discovery request is the fact that if you have system wide proxies, your browser uses them, openid-client by default doesnt. Try switching the client to use `request` instead. https://github.com/panva/node-openid-client#proxy-settings

**Comment by s2t2** [comment]
This is helpful context. I will further investigate some of the approaches you mention. I may post subsequent comments here to detail the results of my investigation, but for now I am closing this issue to indicate my question has been answered. Thanks again.

**Comment by s2t2** [comment]
So, changing the request library didn't work, but I [ran some basic tests using `curl`](https://github.com/18F/identity-oidc-expressjs/issues/1#issuecomment-356130512) which confirmed the cause of the issue is the specific way my identity provider's server is configured. Thanks for helping me arrive at this diagnosis.
