### ISSUE TITLE
OPError: invalid_request (Timeout awaiting 'request' for 4000ms)

### ISSUE THREAD

**Issue by yaseen104** [panva/node-openid-client#684]
**Describe the bug**
We are seeing this error being thrown from openid-client.

**To Reproduce**
We are in version 5.6.2. While trying to use the client.callback(redirectUri, parameters[, checks[, extras]])
method we are seeing this issue.

      return await client.callback(currentCallbackUri, querystring, {
        code_verifier: codeVerifier,
        max_age: Configs.authenticationMaxAgeInSeconds // Max_Age for Auth0 authenticated session
      });

This is an intermittent issue.

**Expected behaviour**
We should not see this error and the token should be generated for Auth0

**Environment:**
 - openid-client version: [5.6.2]
 - node version: [v18.12.1]

**Additional context**
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment]
Intermitten timeouts are to be resolved on your network side of things. Nothing for the module to do or change.

**Comment by yaseen104** [comment]
@panva Do we know when this timeout occurs ? Like lack of network resources or max memory utilization? 
Or do you have any recommendation here ?

**Comment by yaseen104** [comment]
@panva Any reason you have tagged this as a setup-problem ?
Like what kind of setup are we missing?
