### ISSUE TITLE
Receiving a thrown error because xml response when using Issuer.discover.

### ISSUE THREAD

**Issue by JemiloII** [panva/node-openid-client#74]
As a preface, I'm new to openid.
So I'm using `Issuer.discover` docs recommends it. I noticed that any response received is using `JSON.parse()`, which throws an error because Steam is sending back xml, anyway I can have this method request for a json format back or at least not error on me?

```js
const Issuer = require('openid-client').Issuer;

Issuer.discover('http://steamcommunity.com/openid')
    .then(function (steamIssuer) {
        console.log('Discovered issuer', steamIssuer);
    });
```

**Comment by panva** [comment]
Steam is not providing an OpenID Connect interface, rather they use OpenID 2.0 (an obsolete specification). This client is only for the recent "Connect" family of providers.
