### ISSUE TITLE
TypeError: Client is not a constructor

### ISSUE THREAD

**Issue by jwilleke** [panva/node-openid-client#75]
When using the example as shown here:
https://github.com/panva/node-openid-client#manually-recommended

const client = new googleIssuer.Client({
    client_id: 'zELcpfANfgLqY7Oqas',
    client_secret: 'TQV5U29k1gHibH5bx1svbrlayBo0OSAvAbRT3UYW3Eerp[tgcrGadany3'
}); //, [keystore]); // => Client

Receive an error of:
TypeError: googleIssuer.Client is not a constructor

Perhaps I am missing something?

**Comment by panva** [comment]
perhaps, is googleIssuer an Issuer instance from a resolved promise?

**Comment by panva** [comment]
Looking into your source https://github.com/jwilleke/my-openid-client/blob/98ef9d6/index.js you are indeed not waiting for the promise to be resolved.

With basic promise api this is what the file should look like, keep in mind in node lts/carbon you can use the await keyword to simplify this.


```js
const GOOGLE_PROVIDER_URL = 'https://accounts.google.com'

const Issuer = require('openid-client').Issuer;

Issuer.discover(GOOGLE_PROVIDER_URL)
  .then(function(googleIssuer) {
    console.log('Discovered issuer: ', googleIssuer.metadata);

    const client = new googleIssuer.Client({
      client_id: '<CLIENT_ID>',
      client_secret: '<CLIENT_SECRET>'
    });
  });
```
