### ISSUE TITLE
"AssertionError [ERR_ASSERTION]: unexpected iss value" when validating Microsoft ID Tokens

### ISSUE THREAD

**Issue by Alex-d14** [panva/node-openid-client#76]
Hi,

I would like to report an error when validating a Microsoft ID Token with node-openid-client 1.19.4.

Error: "AssertionError [ERR_ASSERTION]: unexpected iss value".
OpenID config: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
Expected issuer: "https://login.microsoftonline.com/{tenantid}/v2.0"

Token sample:
```
{
  "ver": "2.0",
  "iss": "https://login.microsoftonline.com/9188040d-XXXX-XXXX-XXXX-XXXXXXXXXXXX/v2.0",
  "tid": "9188040d-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
  "(...)"
}
```

The "iss" value in this case is not constant (as it contains the tenant id) an thus can't be validated by a simple string comparison.

Best regards,
Alex.

**Comment by panva** [comment]
This is actually a valid assertion since microsoft does not follow the spec as it should. Since you know your expected iss values you can edit them on the fly. See #58
