### ISSUE TITLE
client_secret vs. jose_secret

### ISSUE THREAD

**Issue by JMS-1** [panva/node-openid-client#77]
I get an JWS with HS256 signature. I have the signature secret BUT this is different from the client_secret. Why can't I configure to use the client a key to verify the JWS which is different from the client_secret? Is this any kind of standard definition?

**Comment by panva** [comment]
I'm afraid you'll have to raise your issue another way, I don't get what is it you have an issue with.

**Comment by JMS-1** [comment]
Uh - sorry. Here's the thing: I'm getting a JWS through the autorization code flow which uses the signing algorithm HS256. But the openid-client rejects it since it will use the client_secret setting (from when the client instance was created) to verify the signature (see joseSecret() in client.js). In fact I know the secret with which the JWS was signed (an can verify it as valid through https://jwt.io/) but I see no (regular - dirt tricks are possible) way to inject this secret in the openid-client so that it is used for verification. I can't put it in the client_secret since then the server reports an unauthorized access (as it should).

My issue in node-jose (perhaps you saw it) shows that this won't work either since the providers hash key is less than 256 bits BUT if I get managed to change this (actually I could enforce the client secret to be the signature secret there as well but I really feel that this is the wrong way to go) it would be a good thing to allow a openid-client user to inject his/her very own key.

**Comment by panva** [comment]
There is no such a thing as a signature secret. 

1) the secret must be of a sufficient lenght to support these alga without buffers at the end of the secret. This should be enforced by the OP
2) When id tokens are signed using symmetrical alg it uses the secret, nothing else.

**Comment by panva** [comment]
Here you go > http://openid.net/specs/openid-connect-core-1_0.html#SymmetricKeyEntropy

> In Section 10.1 and Section 10.2, keys are derived from the client_secret value. Thus, when used with symmetric signing or encryption operations, client_secret values MUST contain sufficient entropy to generate cryptographically strong keys. Also, client_secret values MUST also contain at least the minimum of number of octets required for MAC keys for the particular algorithm used. So for instance, for HS256, the client_secret value MUST contain at least 32 octets (and almost certainly SHOULD contain more, since client_secret values are likely to use a restricted alphabet).
