### ISSUE TITLE
Please show error_description

### ISSUE THREAD

**Issue by c-yan** [panva/node-openid-client#79]
I use node-openid-client through passport strategy with [OneLogin](https://www.onelogin.com/).
I got an error like following:

> OpenIdConnectError: invalid_request
>    at Client.gotErrorHandler (C:\Users\user\Documents\xxx\node_modules\openid-clien\lib\error_handler.js:8:11)
>    at &lt;anonymous>
>    at process._tickCallback (internal/process/next_tick.js:188:7)

I did not know the cause of the error at all.
So, I inserted console.log(error); into https://github.com/panva/node-openid-client/blob/master/lib/passport_strategy.js#L169 and I got an error like following:

> { OpenIdConnectError: invalid_request
>     at Client.gotErrorHandler (C:\Users\user\Documents\xxx\node_modules\openid-client\lib\error_handler.js:8:11)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>   message: 'invalid_request',
>   error: 'invalid_request',
>   error_description: 'missing required parameter(s). (redirect_uri)',
>   state: undefined,
>   scope: undefined }

I was able to fix this so that the cause is understood.

I think that it is necessary to get error_description without changing the node-openid-client.
Would you consider improving?

**Comment by panva** [comment]
The error is passed to the strategy, and the properties as you see in your `console.log` are [assigned](https://github.com/panva/node-openid-client/blob/v1.19.4/lib/open_id_connect_error.js) on the object. To "get" the error_description property just reach out for it. I don't see how else can openid-client "show" it.

**Comment by c-yan** [comment]
I do not have confidence that I catch your suggestion correctly, so please let me ask a question for confirmation.
Do you mean that I can retrieve error object by rewriting properly the following [README.md](https://github.com/panva/node-openid-client/blob/master/README.md)'s code in "Usage with passport"?
> // authentication callback
> app.get('/auth/cb', passport.authenticate('oidc', { successRedirect: '/', failureRedirect: '/login' }));

**Comment by panva** [comment]
You should probably get familiar with passport and what it offers. At first glance in the docs you might utilize a `Custom Callback`.

> If the built-in options are not sufficient for handling an authentication request, a custom callback can be provided to allow the application to handle success or failure.

**Comment by c-yan** [comment]
I looked at the passport authenticate code and found the following note:

> * Note that if a callback is supplied, it becomes the application's
> * responsibility to log-in the user, establish a session, and otherwise perform
> * the desired operations.

This looks quite heavy.
What I want is just seeing details of an error, but now Custom Callback is required for node-openid-client, although no other strategies request for the same.
In other strategies, the stack trace is valid so I can clearly reach to where the error has been occurred, and the error message itself is also valid in many cases.
However, regarding this node-openid-client error, there are no contents in stack trace or in error messages.

https://github.com/panva/node-openid-client/blob/master/lib/open_id_connect_error.js#L12
May I suggest changing “message: body.error” of this line to “message: body.error + ":" + body.error_description"?

**Comment by panva** [comment]
Hi @c-yan, I was considering that after I understood what you're after. But this might very well be a breaking change for some people, the tests included since i myself am guilty of just checking the message and not reaching out for the code.

What to do...

**Comment by c-yan** [comment]
OK, I understand the situation.
I wrote the following code as a workaround:

    app.get('/auth/cb', (req, res, next) => {
        const options = { successRedirect: '/', failureRedirect: '/login' };
        passport.authenticate('oidc', options, (err, user, info) => {
            if (err) {
                console.log(`ERROR: ${err.error}: ${err.error_description}`);
                return next(err);
            }
            if (!user) return res.redirect(options.failureRedirect);
            req.logIn(user, err => {
                if (err) return next(err);
                return res.redirect(options.successRedirect);
            });
        })(req, res, next);
    });

I think I can proceed with this code for now.
Thanks!

**Comment by panva** [comment]
Hi @c-yan, I hope ^1.20.0 helps.

**Comment by c-yan** [comment]
It works well.
Thanks a lot!!
