### ISSUE TITLE
Logout route flow

### ISSUE THREAD

**Issue by telemmaite** [panva/node-openid-client#82]
Hello, I am a little puzzled by [example/app.js@router.get/logout](https://github.com/panva/node-openid-client/blob/master/example/app.js#L125)
when used together with [node-oidc-provider](https://github.com/panva/node-oidc-provider).

Once we hit /logout on the client, we will
1. Set local session as not logged in Line [127](https://github.com/panva/node-openid-client/blob/master/example/app.js#L127)
2. Delete local Tokens/session Line [134](https://github.com/panva/node-openid-client/blob/master/example/app.js#L134)
3. Revoke remote/issuer tokens at IDP Line [139](https://github.com/panva/node-openid-client/blob/master/example/app.js#L139)

And in the end redirect to IDP logout source Line [145](https://github.com/panva/node-openid-client/blob/master/example/app.js#L145).

The default [logoutSource](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#logoutsource) at `node-oidc-provider`
renders two buttons Yes/No for the question: `Do you want to logout from OP too?`

What does it mean when we click the No button, we are already logged out from RP but not OP?
So if we try to login from RP it will be quickly resolved as logged in OP and returned back to RP?

**Comment by panva** [comment]
Hi @telemmaite,

Removing your local RP session first is a good start.

From https://openid.net/specs/openid-connect-session-1_0.html

> 5.  RP-Initiated Logout
> At the logout endpoint, the OP SHOULD ask the End-User whether he wants to log out of the OP as well. If the End-User says "yes", then the OP MUST log out the End-User.

Now on the OP side of things clicking `No` means that the OP will only drop the specific RP-related session data, making it so as if the user never visited that RP before. Clicking `Yes` will wipe the OP session making as if the user never logged in the OP before.

**Comment by telemmaite** [comment]
Thanks @panva  it makes sense!

**Comment by panva** [comment]
Thank you @telemmaite
