### ISSUE TITLE
How to handle multiple issuers

### ISSUE THREAD

**Issue by theFroh** [panva/node-openid-client#84]
Apologies for putting what is effectively just a user question into the issue tracker!

I've been having some trouble working out the best way to handle multiple issuers, particularly during callback handling.

Looking at how a Client is tied closely to its parent Issuer, one method I considered was simply maintaining a list of acceptable Issuers, and iterating through them upon callback until validation passes (if it passes). Having [a squiz](https://auth0.com/docs/scopes/current) at what I could expect data-wise coming with the callback, however, I'd have thought a better option would be to instead only use Issuer that matches the callback `sub` claim's `iss`. The issue I have with this is that I can't find a way to simply decode the callback to retrieve this claim without also failing in `authorizationCallback` (as I must use a Client and Issuer that probably isn't the correct one).

The entire callback body would be decoded and validated by a client of the "correct" Issuer after identifying which Issuer to use.

Is there anything glaringly obvious that I'm thinking about, or doing, incorrectly here? 

Cheers for the great library!

P.S. while poking with this, I've put together a basic Typescript definition .d.ts that you may be interested in (lest it may later find its way onto DefinitelyTyped).

**Comment by panva** [comment]
Hi @theFroh,
tha glaringly obvious thing to do is also a best practice and a requirement for some OIDC profiles. Use unique callback routes for each issuer and even client should you have more.

Or push the issuer and client identifiers in your session / bind them to your provided state parameter.

**Comment by telemmaite** [comment]
I had similar problem. In the end I really needed to have a single central place to handle authentication.
But depending on the user email domain, you could get redirected to different IDP provider, from the main `node-oidc-provider`. So it integrated nicely with Azure IDP where I had to register as a callback only the Azure AD client used by `node-oidc-provider` which talks together as Service to service.

Flow is : 
1. Type email inside started /interaction/uuid session of `node-oidc-provider` 
2. Check the domain of this email - for certain domain redirect to /login in [passport-azure-ad](https://github.com/AzureAD/passport-azure-ad) route save session information that it is `node-oidc-provider` request 
3. Once the user completes authentication on Azure IDP the callback url points to /done inside `passport-azure-ad`
4. At this point `passport-azure-ad` validates whatever it is provided to the callback and creates a simple JWT token with information if the sign in was successfull then this token gets send as Service to Service back to `node-oidc-provider` interaction route which makes validation and if OK calls `oidc.interactionFinished` at this point I make a proxy user with claims coming from custom JWT.

In the end I have for example: 5x clients/apps calling -> 1x node oidc provider (5x client app registrations) -> 1x passport azure app -> 1x Azure IDP (1x client registration).

So as long you are `node-oidc-provider` client you dont need any extra setup to login with Azure, it is handled on the `node-oidc-provider` space.

**Comment by panva** [comment]
@telemmaite the two libraries aren't linked, it's great that you understood how to use them together but in @theFroh's case, its likely just having multiple IdPs and having to distinguish them on the way out. What you're describing also does not eliminate the possibility to implement the best practice for unique callback uris, as it doesn't matter where the call was started from, only the registered callback uri.

**Comment by theFroh** [comment]
Ah cheers, that's was my other option; separate callback endpoints. In this case I'm playing around with giving administrators the ability to add support for arbitrary IdP's; I'll just have to dynamically add callback endpoints as needed.

**Comment by G1itcher** [comment]
> Apologies for putting what is effectively just a user question into the issue tracker!
> 
> I've been having some trouble working out the best way to handle multiple issuers, particularly during callback handling.
> 
> Looking at how a Client is tied closely to its parent Issuer, one method I considered was simply maintaining a list of acceptable Issuers, and iterating through them upon callback until validation passes (if it passes). Having [a squiz](https://auth0.com/docs/scopes/current) at what I could expect data-wise coming with the callback, however, I'd have thought a better option would be to instead only use Issuer that matches the callback `sub` claim's `iss`. The issue I have with this is that I can't find a way to simply decode the callback to retrieve this claim without also failing in `authorizationCallback` (as I must use a Client and Issuer that probably isn't the correct one).
> 
> The entire callback body would be decoded and validated by a client of the "correct" Issuer after identifying which Issuer to use.
> 
> Is there anything glaringly obvious that I'm thinking about, or doing, incorrectly here?
> 
> Cheers for the great library!
> 
> P.S. while poking with this, I've put together a basic Typescript definition .d.ts that you may be interested in (lest it may later find its way onto DefinitelyTyped).

@theFroh 
Yes please on the Types, otherwise I'll have to make my own!

**Comment by ulrikstrid** [comment]
Opened a PR that solves this #148

**Comment by tetchel** [comment]
Hey @theFroh I'm also looking for typescript definitions for this library. If you want help putting together a PR for DefinitelyTyped I'd be willing to help out.

@panva Could we maybe created a separate issue for creating TypeScript definitions for this package?

**Comment by panva** [comment]
I'm happy to review them, but maintaining them i can't promise, that's an overhead i don't have the capacity for atm.

**Comment by panva** [comment]
Change of heart, i'll bundle definitions with 3.x i welcome you to validate them once out. I'm a typescript novice so i don't know if what i'm doing is "standard", that being said i tried to use the types and it worked for me.

It would be immensely helpful if you could check [this issue](https://github.com/panva/jose/issues/9) so that i can maybe avoid the same problems that may be there.
