### ISSUE TITLE
State mismatch, could not find a state in the session.

### ISSUE THREAD

**Issue by danielpa9708** [panva/node-openid-client#86]
```
state mismatch, could not find a state in the session, this is likely an environment setup issue, loaded session: undefined
```

Sometimes I have this error when trying to login in the app. This is very odd, as it works most of the time but sometimes fails. It says it's likely an environment setup issue, but I couldn't find any configuration to change that could fix the problem.

**Comment by panva** [comment]
If this works most of the time it likely means that a user might've cleared the cookies coming back to your client or the session was otherwise dropped. You can see that the loaded session was simply `undefined` and session persistance and loading is not part of any passport strategy

**Comment by danielpa9708** [comment]
@panva , I don't think the users are clearing the cookies, I have got the same error without clearing the cookies, and when I try to login again it worked, so has been hard to reproduce

**Comment by panva** [comment]
@danielpa9708 I understand your frustration -> However, please see, that the loaded session is `undefined`.

The strategy relies on sessions for storing and retrieving states for important validations but it's not providing the session mechanism - neither it's persistance nor the cookie handling.

**Comment by danielpa9708** [comment]
Thanks @panva, I'll double check my setup to see if the cookies are been cleared somehow
