### ISSUE TITLE
Example for AWS Cognito

### ISSUE THREAD

**Issue by ryan-kimber** [panva/node-openid-client#95]
I'm trying to use AWS Cognito as my user provider/issuer, but I am running into the client complaining that there is no id_token just before I expect my redirect logic to get called. 

I've tried using the https://cognito-identity.amazonaws.com/.well-known/openid-configuration to discover the correct configuration, but this config isn't specific to my own user pool, and URLs provided there are generic. 

Is there a working sample of using AWS Cognito?

**Comment by panva** [comment]
> but I am running into the client complaining that there is no id_token just before I expect my redirect logic to get called.

Well, if there's no id_token of course an openid connect library is going to fail it's callback validations.

I don't have a sample working with cognito since i don't believe AWS Cognito is an OpenID Provider with all it's MUST functionalities, if it was i believe they would have certified its openid connect behaviors.

**Comment by panva** [comment]
I got cognito to work just fine, i'm getting all responses the way I should...

Here's my code, as you can see nothing out of the ordinary, start a valid request, do a callback. Maybe your pool configuration is out of whack.

```js
const { Issuer } = require('openid-client');
const Koa = require('koa');
const Router = require('koa-router');

(async () => {
  const app = new Koa();
  const router = new Router();

  const issuer = await Issuer.discover('https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_PaHE1tWNZ');

  const client = new issuer.Client({
    client_id: 'redacted',
    client_secret: 'redacted',
    redirect_uris: ['https://rp.panva.me/cb'],
  });

  router.get('/init', async (ctx, next) => {
    ctx.body = `<a href="${client.authorizationUrl({
      redirect_uri: client.redirect_uris[0],
      scope: 'openid email',
    })}">login</a>`
  });

  router.get('/cb', async (ctx, next) => {
    try {
      const tokenset = await client.authorizationCallback(client.redirect_uris[0], ctx.query);
      ctx.body = tokenset;
    } catch (err) {
      ctx.body = err;
    }
  });

  app.use(router.routes());
  app.listen(3030);
})();
```

**Comment by ryan-kimber** [comment]
Thanks. That's quite helpful. 

Where did you find this URI? ('https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_PaHE1tWNZ')

**Comment by panva** [comment]
`eu-central-1_PaHE1tWNZ` is my pool id

**Comment by ryan-kimber** [comment]
And is this where the rest of the URL came from? 

![screen shot 2018-05-27 at 5 37 46 pm](https://user-images.githubusercontent.com/1018189/40590869-baaf63f8-61d4-11e8-8043-5d8ef1cf53f5.png)
