### ISSUE TITLE
SyntaxError: Unexpected token  in JSON at position 0, node_modules/openid-client/lib/client.js:666:43

### ISSUE THREAD

**Issue by qutus** [panva/node-openid-client#96]
Hi everyone. I'm using the lib to have capability to 'Login with google' on my project.

I'm using node v6.13.1 and openid-client v2.0.4.

I have this error when openid-client take care of fetching data from google, after the user authenticated himself on google and was redirected to my openId callback.

It happens only in production, no problem in dev/staging env.

I understand what is the problem(failed to parse response json body, see lib/client.js:666), but I can't find out the cause of it since I have no hand on this part, it's all on google <-> openid-client at this point of the authentication procedure.

My next step will be to debug with a fork of the openid-client lib directly in production. I'm exposing my case in case of someone experienced that.

```
 SyntaxError: Unexpected token  in JSON at position 0                                                
     at Object.parse (native)                                                                                                                                            
     at authenticatedPost.then.then.response (/.../node_modules/openid-client/lib/client.js:666:43)       
     at propagateAslWrapper (/usr/lib/node_modules/pm2/node_modules/async-listener/index.js:478:23)  
     at /usr/lib/node_modules/pm2/node_modules/async-listener/glue.js:188:31                                                                                      
     at /usr/lib/node_modules/pm2/node_modules/async-listener/index.js:515:70                                                                                 
     at /usr/lib/node_modules/pm2/node_modules/async-listener/glue.js:188:31                         
     at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:135:7)                
```

**Comment by panva** [comment]
You can use the same method to debug the responses as in [#90](https://github.com/panva/node-openid-client/issues/90#issuecomment-383278314). The way you initialize the Issuer and Client would be interesting to help.

**Comment by qutus** [comment]
Thanks for the reactivity Panva, and for the debug method !

I know that it is likely to be a configuration issue, but in my prototyping context, the configuration is the same in my staging env, my dev env, and my production env. It let me think that my configuration is totally okay.
I'm looking for specific production problems like nginx or firewall altering my packets.

I'll give feedback after a debug try.

**Comment by qutus** [comment]
At the moment I putted request in debug mode, it stopped bugging. 
I reverted request debug mode and It's also good.

Everything work fine, I have no explanation and can't investigate anymore :S

Sorry for the wast of time, tell me if you want me to close the issue.

Thanks for your help !
