### ISSUE TITLE
Query for node-oidc-client

### ISSUE THREAD

**Issue by jainmanoj** [panva/node-openid-client#98]
I am sorry as there is no mailing list, I am using this to post my query.

I want to use node-oidc-client as middleware for connecting to multiple IDPs (SAML / node-oidc-provider).
I was looking for some  applications which use node-oidc-client with multiple providers to protect applications

Can I use SAML authentication  / LDAP using OIDC.

Is there any example to demonstrate this capability.

**Comment by panva** [comment]
You can only use openid-client to connect to multiple openid providers.
